"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { Suspense, useState } from "react";

function OnboardingForm() {
  const params = useSearchParams(); const router = useRouter();
  const initial = params.get("track") === "pn" ? "PN" : "RN";
  const [track, setTrack] = useState(initial); const [timing, setTiming] = useState(""); const [confidence, setConfidence] = useState("");
  function next(){ if(timing&&confidence){ sessionStorage.setItem('npq_onboarding',JSON.stringify({track:track.toLowerCase(),timing,confidence})); router.push(`/auth?track=${track.toLowerCase()}`); } }
  return <main className="min-h-screen bg-slate-50"><div className="h-2 progress-gradient"/><div className="mx-auto max-w-2xl px-6 py-10"><a href="/" className="text-xl font-black text-[var(--deep-navy)]">NursePrep<span className="text-[var(--teal)]">IQ</span></a><div className="mt-8 rounded-[2rem] bg-white p-7 shadow-xl ring-1 ring-slate-200 md:p-10"><p className="text-sm font-black tracking-wider text-[var(--teal)]">STEP 1 • PERSONALIZE YOUR PREP</p><h1 className="mt-2 text-4xl font-black text-[var(--deep-navy)]">Tell us about your NCLEX goal.</h1><p className="mt-3 text-slate-600">We’ll use this to shape your dashboard and study plan.</p><label className="mt-8 block font-bold">Which NCLEX are you preparing for?</label><div className="mt-3 grid grid-cols-2 gap-3">{["RN","PN"].map(x=><button key={x} onClick={()=>setTrack(x)} className={`rounded-xl border p-4 font-extrabold ${track===x?"border-[var(--teal)] bg-cyan-50 text-[var(--teal)]":"border-slate-200"}`}>NCLEX-{x}®</button>)}</div><label className="mt-7 block font-bold">When do you plan to test?</label><select value={timing} onChange={e=>setTiming(e.target.value)} className="mt-3 w-full rounded-xl border border-slate-300 bg-white p-3.5"><option value="">Choose one</option><option>Within 30 days</option><option>1–2 months</option><option>3–6 months</option><option>Not scheduled yet</option></select><label className="mt-7 block font-bold">How confident do you feel right now?</label><select value={confidence} onChange={e=>setConfidence(e.target.value)} className="mt-3 w-full rounded-xl border border-slate-300 bg-white p-3.5"><option value="">Choose one</option><option>Not confident yet</option><option>Somewhat confident</option><option>Confident</option></select><button onClick={next} disabled={!timing||!confidence} className="mt-8 w-full rounded-xl bg-[var(--blue)] py-4 font-extrabold text-white shadow-lg shadow-blue-100 disabled:cursor-not-allowed disabled:opacity-40">Continue → Create Free Account</button><p className="mt-4 text-center text-xs text-slate-500">No credit card required.</p></div></div></main>;
}
export default function OnboardingPage(){ return <Suspense fallback={<main className="min-h-screen bg-slate-50"/>}><OnboardingForm/></Suspense>; }
