'use client';
import type {QuestionOption,ResponseConfig,StudentResponse} from '@/lib/questions/scoring';
type P={itemType:string;options:QuestionOption[];config:ResponseConfig;value:StudentResponse;disabled?:boolean;showResults?:boolean;onChange:(v:StudentResponse)=>void};
export default function QuestionResponse({itemType,options,config,value,disabled,showResults=false,onChange}:P){
 const toggle=(k:string)=>{const s=new Set(value.selected||[]);s.has(k)?s.delete(k):s.add(k);onChange({...value,selected:[...s]})};
 if(itemType==='multiple_response')return <div className="mt-6 space-y-3">{options.map(o=>{const chosen=(value.selected||[]).includes(o.option_key);const review=showResults?(o.is_correct?'border-emerald-400 bg-emerald-50':chosen?'border-rose-400 bg-rose-50':'border-slate-200 bg-white'):'border-slate-200 bg-white';return <label key={o.option_key} className={'flex gap-3 rounded-2xl border p-4 '+review}><input disabled={disabled} type="checkbox" checked={chosen} onChange={()=>toggle(o.option_key)}/><span><b>{o.option_key.toUpperCase()}.</b> {o.option_text}{showResults&&o.is_correct&&<b className="ml-2 text-emerald-700">✓ Correct</b>}{showResults&&chosen&&!o.is_correct&&<b className="ml-2 text-rose-700">✕ Incorrect</b>}</span></label>})}</div>;
 if(itemType==='matrix_grid')return <div className="mt-6 overflow-x-auto"><table className="w-full border-collapse"><thead><tr><th className="p-3 text-left">Finding</th>{(config.columns||[]).map(c=><th key={c.id} className="p-3">{c.label}</th>)}</tr></thead><tbody>{(config.rows||[]).map(r=>{const chosen=(value.matrix?.[r.id]||[])[0];return <tr key={r.id} className="border-t"><td className="p-3">{r.label}</td>{(config.columns||[]).map(col=>{const isKey=col.id===r.correct,isChosen=chosen===col.id;const review=disabled?(isKey?'bg-emerald-100 ring-1 ring-emerald-300':isChosen?'bg-rose-100 ring-1 ring-rose-300':''):'';return <td key={col.id} className={'p-3 text-center '+review}><input disabled={disabled} type="radio" name={r.id} checked={isChosen} onChange={()=>onChange({...value,matrix:{...(value.matrix||{}),[r.id]:[col.id]}})}/>{disabled&&isKey&&<span className="ml-2 font-black text-emerald-700">✓</span>}{disabled&&isChosen&&!isKey&&<span className="ml-2 font-black text-rose-700">✕</span>}</td>})}</tr>})}</tbody></table></div>;
 if(itemType==='cloze_dropdown')return <div className="mt-6 space-y-4">{(config.blanks||[]).map((b,n)=><label key={b.id} className="block font-bold">Blank {n+1}<select disabled={disabled} value={value.blanks?.[b.id]||''} onChange={e=>onChange({...value,blanks:{...(value.blanks||{}),[b.id]:e.target.value}})} className="ml-3 rounded-xl border p-3 font-normal"><option value="">Choose…</option>{b.options.map(x=><option key={x}>{x}</option>)}</select></label>)}</div>;
 if(itemType==='highlight')return <div className="mt-6 flex flex-wrap gap-2">{(config.segments||[]).map(s=>{const on=(value.highlights||[]).includes(s.id);return <button type="button" disabled={disabled} key={s.id} onClick={()=>{const a=new Set(value.highlights||[]);a.has(s.id)?a.delete(s.id):a.add(s.id);onChange({...value,highlights:[...a]})}} className={'rounded-lg border px-3 py-2 '+(on?'bg-yellow-200':'bg-white')}>{s.text}</button>})}</div>;
 if(itemType==='bow_tie')return <div className="mt-6 grid gap-4 md:grid-cols-3">{(config.groups||[]).map(g=><fieldset key={g.id} className="rounded-2xl border p-4"><legend className="font-black">{g.label} — choose {g.choose}</legend>{g.options.map(o=>{const chosen=(value.groups?.[g.id]||[]).includes(o.id);return <label key={o.id} className="mt-3 flex gap-2"><input disabled={disabled||(!chosen&&(value.groups?.[g.id]||[]).length>=g.choose)} type={g.choose===1?'radio':'checkbox'} name={g.id} checked={chosen} onChange={()=>{let a=[...(value.groups?.[g.id]||[])];a=g.choose===1?[o.id]:(chosen?a.filter(x=>x!==o.id):[...a,o.id]);onChange({...value,groups:{...(value.groups||{}),[g.id]:a}})}}/>{o.label}</label>})}</fieldset>)}</div>;
 return <div className="mt-6 space-y-3">{options.map(o=>{const chosen=value.selected?.[0]===o.option_key;const review=showResults?(o.is_correct?'border-emerald-400 bg-emerald-50':chosen?'border-rose-400 bg-rose-50':'border-slate-200 bg-white'):(chosen?'border-blue-500 bg-blue-50':'border-slate-200 bg-white');return <button type="button" key={o.option_key} disabled={disabled} onClick={()=>onChange({...value,selected:[o.option_key]})} className={'w-full rounded-2xl border p-4 text-left '+review}><b className="mr-3 uppercase">{o.option_key}</b>{o.option_text}{showResults&&o.is_correct&&<b className="ml-3 text-emerald-700">✓ Correct</b>}{showResults&&chosen&&!o.is_correct&&<b className="ml-3 text-rose-700">✕ Incorrect</b>}</button>})}</div>;
}
