-- NursePrepIQ 0008: Neurologic foundation question bank
-- 24 original pilot items: RN + PN across Stroke, Seizures, Increased ICP, Meningitis.
-- Calibrated to the 2026-2029 NCLEX RN/PN test-plan model; not copied NCSBN items.
-- Clinical editorial validation remains required before production certification.

do $$
declare
 topics text[]:=array['Stroke','Seizures','Increased Intracranial Pressure','Meningitis']; slugs text[]:=array['stroke','seizures','increased-icp','meningitis'];
 t text;slug text;role text;ti int;ri int;n int;qid uuid;vid uuid;stem text;correct_text text;w1 text;w2 text;w3 text;cj text;diff text;rationale text;memory text;focus text;trationale text;clientneed text;
begin
 for ti in 1..4 loop t:=topics[ti];slug:=slugs[ti]; for ri in 1..2 loop role:=case when ri=1 then 'rn' else 'pn' end;
  for n in 1..3 loop
   qid:=md5('npq-0008-'||role||'-'||slug||'-'||n)::uuid;vid:=md5('npq-0008-v-'||role||'-'||slug||'-'||n)::uuid;diff:=case when n=3 then 'hard' else 'medium' end;clientneed:=case when t='Meningitis' and n=2 then 'Safety and Infection Prevention and Control' else 'Physiological Adaptation' end;
   if role='rn' then focus:='RN comprehensive neurologic assessment, synthesis, prioritization, intervention, coordination, teaching, and evaluation.';trationale:='RN-specific because the item requires integration of neurologic findings into the broader nursing assessment, priority, intervention, or evaluation decision.';else focus:='PN focused neurologic data collection, monitoring, safety, reinforcement of the established plan, and prompt communication of significant change.';trationale:='PN-specific because the item emphasizes recognizing change, safe assigned care, monitoring, reinforcement, and timely escalation within the established plan.';end if;
   if t='Stroke' and n=1 then cj:='Recognize Cues';memory:='Stroke: sudden focal neurologic change is time-sensitive.';if role='rn' then stem:='The RN is assessing four clients. Which finding requires immediate evaluation for possible acute stroke?';correct_text:='A client with sudden facial droop, arm weakness, and difficulty speaking that began during breakfast.';else stem:='The LPN/VN is collecting data from four clients. Which new finding should be reported immediately as possible acute stroke?';correct_text:='Sudden facial droop with one-sided arm weakness and new difficulty speaking.';end if;w1:='Longstanding bilateral foot numbness documented with diabetic neuropathy.';w2:='A chronic mild hand tremor unchanged from baseline.';w3:='A client asking for help remembering a follow-up appointment.';rationale:='Sudden focal neurologic deficits are a time-sensitive change requiring immediate stroke evaluation.';
   elsif t='Stroke' and n=2 then cj:='Take Action';memory:='Suspected stroke: establish last-known-well, assess ABCs/neurologic status, and activate the stroke pathway.';if role='rn' then stem:='A client develops sudden unilateral weakness and aphasia. Which RN action is the priority?';correct_text:='Assess airway and neurologic status, determine the last-known-well time, and activate the facility stroke response.';else stem:='A client under LPN/VN care develops sudden unilateral weakness and difficulty speaking. What is the priority response?';correct_text:='Stay with the client, maintain safety, obtain focused neurologic and vital-sign data, and immediately notify or activate the facility response.';end if;w1:='Complete routine medication teaching before notifying anyone.';w2:='Offer food and fluids to determine whether swallowing is intact.';w3:='Reassess at the next scheduled vital-sign round.';rationale:='Acute stroke is time-sensitive; rapid assessment and activation should not be delayed by routine care or oral intake.';
   elsif t='Stroke' then cj:='Evaluate Outcomes';memory:='After stroke intervention, trend neurologic function—not one isolated sign.';if role='rn' then stem:='Which finding best helps the RN determine that a client with acute stroke is neurologically stable after intervention?';correct_text:='Level of consciousness, speech, motor strength, and vital signs remain stable or improve on serial assessments.';else stem:='Which finding should the LPN/VN document and communicate as evidence of neurologic stability after treatment for stroke?';correct_text:='Serial checks show stable or improving alertness, speech, motor strength, and vital signs.';end if;w1:='One blood-pressure reading improves while responsiveness declines.';w2:='The client sleeps more and becomes increasingly difficult to arouse.';w3:='Appetite improves while unilateral weakness suddenly worsens.';rationale:='Neurologic outcomes are evaluated by serial trends in consciousness, focal function, and physiologic stability.';
   elsif t='Seizures' and n=1 then cj:='Take Action';memory:='During a seizure: protect, position when possible, time it, observe, and do not restrain or place objects in the mouth.';if role='rn' then stem:='A hospitalized client begins a generalized tonic-clonic seizure. Which RN action is most appropriate?';correct_text:='Protect the client from injury, position to support the airway when possible, time and observe the seizure, and prepare for postictal assessment.';else stem:='A client begins a generalized tonic-clonic seizure while the LPN/VN is at the bedside. Which action is appropriate?';correct_text:='Protect the client from injury, support safe positioning and the airway when possible, time the seizure, and summon appropriate assistance.';end if;w1:='Insert a padded object between the teeth.';w2:='Hold the client firmly to stop extremity movement.';w3:='Leave the bedside to complete documentation before seeking help.';rationale:='Seizure first aid centers on injury prevention, airway-supportive positioning, observation, timing, and appropriate escalation.';
   elsif t='Seizures' and n=2 then cj:='Analyze Cues';memory:='Postictal recovery is expected; failure to recover or repeated seizures raises urgency.';if role='rn' then stem:='After a seizure, which finding should the RN interpret as requiring the most urgent reassessment?';correct_text:='The client does not regain expected responsiveness and has another seizure without meaningful recovery between events.';else stem:='After a seizure, which finding should the LPN/VN report most urgently?';correct_text:='The client fails to regain expected responsiveness and another seizure begins before meaningful recovery.';end if;w1:='Temporary fatigue that gradually improves during the postictal period.';w2:='A request to sleep after becoming progressively more responsive.';w3:='Muscle soreness after a seizure with otherwise improving status.';rationale:='Failure to recover between seizures can signal a prolonged seizure emergency and requires urgent response.';
   elsif t='Seizures' then cj:='Evaluate Outcomes';memory:='Antiseizure safety teaching: adherence, triggers, precautions, and when to seek help.';if role='rn' then stem:='Which client statement best indicates effective RN teaching about seizure management?';correct_text:='“I will take my antiseizure medicine consistently and follow my safety plan rather than stopping it when I feel well.”';else stem:='Which client statement best shows understanding after the LPN/VN reinforces the established seizure teaching plan?';correct_text:='“I will take my antiseizure medicine as directed and follow the safety instructions even when I have not had a seizure recently.”';end if;w1:='“I can stop the medicine whenever I have been seizure-free for a few days.”';w2:='“If a seizure occurs, someone should restrain my arms and legs.”';w3:='“Someone should put an object in my mouth during a seizure.”';rationale:='Consistent medication adherence and safe seizure precautions are core elements of seizure self-management.';
   elsif t='Increased Intracranial Pressure' and n=1 then cj:='Recognize Cues';memory:='ICP: a declining level of consciousness is a major warning sign.';if role='rn' then stem:='The RN is monitoring a client at risk for increased intracranial pressure. Which change is most concerning?';correct_text:='The client becomes progressively harder to arouse and responds more slowly than on the previous assessment.';else stem:='The LPN/VN is monitoring a client at risk for increased intracranial pressure. Which change should be reported immediately?';correct_text:='The client is increasingly difficult to arouse compared with the previous assessment.';end if;w1:='The client requests a dimmer room because of a mild headache.';w2:='The client reports being tired after physical therapy.';w3:='The client asks when family may visit.';rationale:='A worsening level of consciousness is an important early indicator of neurologic deterioration and increased ICP.';
   elsif t='Increased Intracranial Pressure' and n=2 then cj:='Generate Solutions';memory:='ICP nursing care avoids unnecessary pressure increases and supports venous drainage while preserving oxygenation/perfusion.';if role='rn' then stem:='The RN plans care for a stable client with increased intracranial pressure. Which approach is most appropriate?';correct_text:='Maintain prescribed head and neck alignment, reduce unnecessary stimulation, monitor neurologic trends, and avoid activities that unnecessarily increase intracranial pressure.';else stem:='The LPN/VN implements the established plan for a stable client with increased intracranial pressure. Which action is appropriate?';correct_text:='Maintain prescribed positioning and head alignment, reduce unnecessary stimulation, and perform ordered neurologic monitoring.';end if;w1:='Keep the neck sharply flexed to prevent movement.';w2:='Cluster every possible activity into one highly stimulating session regardless of response.';w3:='Encourage repeated straining to assess tolerance.';rationale:='Positioning, reduced stimulation, serial neurologic monitoring, and avoiding unnecessary ICP-provoking activity support neurologic stability.';
   elsif t='Increased Intracranial Pressure' then cj:='Analyze Cues';memory:='ICP deterioration is a trend: consciousness, pupils, motor response, and vital signs matter together.';if role='rn' then stem:='Which cluster should the RN interpret as strongest evidence of worsening intracranial pressure?';correct_text:='Declining responsiveness with new pupillary asymmetry and worsening motor response.';else stem:='Which cluster should the LPN/VN recognize as a significant neurologic change requiring immediate communication?';correct_text:='Decreasing responsiveness with a new pupil difference and worsening motor response.';end if;w1:='Stable alertness with unchanged pupils and motor strength.';w2:='A mild headache that improves while the neurologic examination remains unchanged.';w3:='A request for fewer visitors with otherwise stable findings.';rationale:='A concurrent decline in consciousness, pupillary response, and motor function strongly signals neurologic deterioration.';
   elsif t='Meningitis' and n=1 then cj:='Recognize Cues';memory:='Meningitis concern rises with fever plus meningeal/neurologic symptoms.';if role='rn' then stem:='Which assessment cluster should cause the RN to suspect an acute meningitis syndrome and prioritize further evaluation?';correct_text:='Fever, severe headache, neck stiffness, photophobia, and altered mental status.';else stem:='Which new cluster should the LPN/VN report promptly as concerning for meningitis?';correct_text:='Fever with severe headache, neck stiffness, photophobia, and a change in mental status.';end if;w1:='Chronic low-back pain with no fever or neurologic change.';w2:='Seasonal nasal congestion with normal mentation.';w3:='An isolated tension-type headache relieved by rest.';rationale:='Fever plus meningeal symptoms and altered mentation is a concerning acute neurologic/infectious pattern.';
   elsif t='Meningitis' and n=2 then cj:='Take Action';memory:='Suspected transmissible meningitis: protect others promptly while urgent evaluation/treatment proceeds.';if role='rn' then stem:='A client is admitted with suspected bacterial meningitis. Which nursing action should the RN prioritize while diagnostic evaluation and treatment proceed?';correct_text:='Initiate the indicated transmission-based precautions promptly and continue urgent neurologic and physiologic assessment.';else stem:='A client arrives with suspected bacterial meningitis. Which action is appropriate for the LPN/VN under the established facility protocol?';correct_text:='Implement the indicated transmission-based precautions promptly and report neurologic or physiologic deterioration immediately.';end if;w1:='Delay precautions until all diagnostic results are final.';w2:='Encourage unrestricted visitors before evaluating transmission risk.';w3:='Focus first on nonurgent discharge education.';rationale:='Prompt infection precautions reduce exposure risk and should occur alongside urgent assessment and treatment.';
   else cj:='Evaluate Outcomes';memory:='Meningitis improvement is judged by neurologic, temperature, hemodynamic, and symptom trends.';if role='rn' then stem:='Which finding best indicates to the RN that a client being treated for meningitis is clinically improving?';correct_text:='Mental status is clearer, fever is trending down, hemodynamics remain stable, and headache and neck discomfort are improving.';else stem:='Which finding should the LPN/VN document and communicate as evidence of improvement in a client being treated for meningitis?';correct_text:='The client is more alert, temperature is trending down, vital signs are stable, and headache and neck discomfort are improving.';end if;w1:='Fever decreases while the client becomes increasingly difficult to arouse.';w2:='Headache changes slightly while blood pressure falls and confusion worsens.';w3:='The client sleeps longer but is progressively less responsive when awakened.';rationale:='Meaningful improvement requires favorable neurologic and physiologic trends, not one isolated symptom.';end if;
   insert into public.questions(id,slug,lifecycle_status,current_version) values(qid,role||'-neuro-'||slug||'-'||n,'active',1) on conflict(id) do update set lifecycle_status='active',current_version=1;
   insert into public.question_versions(id,question_id,version,stem,item_type,exam_tracks,subject,topic,client_need,clinical_judgment_step,difficulty,rationale_correct,rationale_distractors,memory_rule,source_note,validation_status,professional_role_focus,track_rationale) values(vid,qid,1,stem,'single_best_answer',array[role],'Adult Health: Neurologic',t,clientneed,cj,diff,rationale,'The distractors represent stable/chronic findings, delayed responses, unsafe actions, or isolated findings that do not address the priority neurologic need.',memory,'Original NursePrepIQ pilot item calibrated to the 2026-2029 NCLEX test-plan framework and official item-writing principles. Not an NCSBN item. Clinical editorial validation required.','pilot',focus,trationale) on conflict(question_id,version) do nothing;
   insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(vid,'a',w1,false,'This is not the best response to the priority neurologic problem.',1),(vid,'b',correct_text,true,rationale,2),(vid,'c',w2,false,'This is lower priority, delayed, or inconsistent with the concerning trend.',3),(vid,'d',w3,false,'This does not address the most important current neurologic need.',4) on conflict(question_version_id,option_key) do nothing;
  end loop; end loop; end loop;
end $$;
