-- NursePrepIQ 0009: Renal & Urinary foundation bank
-- 24 original pilot items: 12 RN + 12 PN across AKI, CKD/Dialysis, UTI/Pyelonephritis, and Urinary Retention.
-- Original NursePrepIQ content calibrated to 2026-2029 NCLEX RN/PN test-plan principles; not NCSBN items.
-- Clinical editorial validation required before production certification.

do $$
declare
 topics text[]:=array['Acute Kidney Injury','Chronic Kidney Disease & Dialysis','UTI & Pyelonephritis','Urinary Retention']; slugs text[]:=array['aki','ckd-dialysis','uti-pyelonephritis','urinary-retention'];
 t text;slug text;role text;ti int;ri int;n int;qid uuid;vid uuid;stem text;correct_text text;w1 text;w2 text;w3 text;cj text;diff text;rationale text;memory text;focus text;trationale text;pos int;
begin
 for ti in 1..4 loop t:=topics[ti];slug:=slugs[ti]; for ri in 1..2 loop role:=case when ri=1 then 'rn' else 'pn' end;
  for n in 1..3 loop
   qid:=md5('npq-0009-'||role||'-'||slug||'-'||n)::uuid;vid:=md5('npq-0009-v-'||role||'-'||slug||'-'||n)::uuid;diff:=case when n=3 then 'hard' else 'medium' end;pos:=((ti+ri+n-3)%4)+1;
   if role='rn' then focus:='RN comprehensive renal assessment, synthesis of laboratory and clinical trends, prioritization, intervention, coordination, teaching, and evaluation.';trationale:='RN-specific because the decision requires comprehensive assessment and integration of renal, fluid, electrolyte, perfusion, or treatment findings.';else focus:='PN focused renal and urinary data collection, monitoring, safe assigned care, reinforcement of the established plan, and prompt reporting of significant change.';trationale:='PN-specific because the decision emphasizes focused monitoring, safe implementation, reinforcement, and timely communication within the established plan.';end if;
   if t='Acute Kidney Injury' and n=1 then cj:='Recognize Cues';memory:='AKI: falling urine output plus worsening fluid/electrolyte findings deserves attention.';stem:=case when role='rn' then 'The RN reviews findings for a client at risk for acute kidney injury. Which change requires the most immediate follow-up?' else 'The LPN/VN is monitoring a client at risk for acute kidney injury. Which change should be reported promptly?' end;correct_text:='Urine output has fallen markedly from baseline while edema and shortness of breath are increasing.';w1:='The client asks why intake and output are being measured.';w2:='The client reports mild fatigue after physical therapy.';w3:='Urine remains yellow without a new change in amount.';rationale:='A significant fall in urine output with increasing fluid-overload findings can indicate worsening renal function and physiologic instability.';
   elsif t='Acute Kidney Injury' and n=2 then cj:='Analyze Cues';memory:='In AKI, interpret potassium, fluid status, urine output, and perfusion together.';stem:=case when role='rn' then 'Which cluster should the RN interpret as the highest-priority deterioration in a client with acute kidney injury?' else 'Which cluster should the LPN/VN recognize as requiring immediate communication in a client with acute kidney injury?' end;correct_text:='Increasing weakness with a rising potassium trend, decreasing urine output, and new cardiac rhythm changes.';w1:='Stable creatinine trend with unchanged urine output and appetite.';w2:='Dry skin with stable vital signs and unchanged laboratory results.';w3:='A request for information about the renal diet.';rationale:='Hyperkalemia with rhythm changes and declining urine output can become life-threatening and requires urgent response.';
   elsif t='Acute Kidney Injury' then cj:='Evaluate Outcomes';memory:='Renal recovery is a trend: urine output, fluid status, electrolytes, and kidney-function markers move together.';stem:=case when role='rn' then 'Which trend best indicates to the RN that treatment for acute kidney injury is effective?' else 'Which trend should the LPN/VN document and communicate as evidence that a client with acute kidney injury is improving?' end;correct_text:='Urine output and fluid status improve while electrolyte abnormalities and kidney-function markers trend toward the desired range.';w1:='Edema worsens even though one laboratory value improves.';w2:='Urine output continues to decline while weight increases.';w3:='Potassium rises while the client reports feeling less tired.';rationale:='Improvement is demonstrated by coordinated favorable trends in renal output, volume status, electrolytes, and renal-function measures.';
   elsif t='Chronic Kidney Disease & Dialysis' and n=1 then cj:='Recognize Cues';memory:='Dialysis access: loss of thrill/bruit is an urgent access warning.';stem:=case when role='rn' then 'The RN assesses a client with a hemodialysis arteriovenous access. Which finding requires immediate follow-up?' else 'The LPN/VN checks a client’s hemodialysis arteriovenous access. Which finding should be reported immediately?' end;correct_text:='The previously palpable thrill is absent over the vascular access.';w1:='The client asks why blood pressure is avoided on the access arm.';w2:='A small healed scar is present near the access site.';w3:='The client reports being tired after the previous dialysis session.';rationale:='Loss of the expected thrill can indicate access occlusion and threatens dialysis access patency.';
   elsif t='Chronic Kidney Disease & Dialysis' and n=2 then cj:='Take Action';memory:='Protect the dialysis access: no compression, venipuncture, or blood pressure on the access arm.';stem:=case when role='rn' then 'Which action should the RN include when protecting a functioning hemodialysis arteriovenous access?' else 'Which action is appropriate for the LPN/VN caring for a client with a functioning hemodialysis arteriovenous access?' end;correct_text:='Protect the access arm from blood-pressure cuffs, venipuncture, and unnecessary compression while monitoring access patency.';w1:='Use the access arm first for routine blood-pressure measurements.';w2:='Apply prolonged tight compression over the access between treatments.';w3:='Use the access for routine venipuncture whenever peripheral access is difficult.';rationale:='Avoiding compression and invasive procedures on the access arm helps preserve vascular access function.';
   elsif t='Chronic Kidney Disease & Dialysis' then cj:='Evaluate Outcomes';memory:='After dialysis, evaluate volume, hemodynamics, symptoms, electrolytes, and access—not weight alone.';stem:=case when role='rn' then 'Which finding best indicates to the RN that a hemodialysis treatment achieved the intended clinical response without obvious instability?' else 'Which finding should the LPN/VN document as a favorable response after hemodialysis?' end;correct_text:='Fluid-overload symptoms lessen, weight moves toward the prescribed target, vital signs remain acceptable, and the access remains patent.';w1:='Weight decreases but the client develops worsening dizziness and hypotension.';w2:='Edema is unchanged and shortness of breath worsens.';w3:='The access loses its thrill after treatment.';rationale:='A favorable dialysis response includes improved volume status with physiologic stability and continued access patency.';
   elsif t='UTI & Pyelonephritis' and n=1 then cj:='Analyze Cues';memory:='Lower urinary symptoms plus fever/flank pain suggest upper-tract involvement.';stem:=case when role='rn' then 'Which findings should lead the RN to suspect that a urinary infection may involve the upper urinary tract?' else 'Which change should the LPN/VN report as concerning for progression of a urinary infection?' end;correct_text:='New fever, chills, flank pain, and worsening systemic symptoms accompany urinary complaints.';w1:='Mild urinary frequency occurs without fever or systemic symptoms.';w2:='The client asks how much fluid to drink after discharge.';w3:='Urine color is unchanged and vital signs remain stable.';rationale:='Fever, chills, flank pain, and systemic illness with urinary symptoms are concerning for pyelonephritis or more serious infection.';
   elsif t='UTI & Pyelonephritis' and n=2 then cj:='Generate Solutions';memory:='Urinary infection care combines prescribed treatment, hydration when appropriate, monitoring, and escalation for systemic deterioration.';stem:=case when role='rn' then 'Which plan is most appropriate for an otherwise stable client being treated for a urinary tract infection?' else 'Which action is appropriate when the LPN/VN reinforces the established plan for a stable client with a urinary tract infection?' end;correct_text:='Follow the prescribed antimicrobial plan, encourage fluids when not contraindicated, monitor symptoms, and teach the client to report worsening systemic signs.';w1:='Stop prescribed treatment as soon as urinary discomfort improves.';w2:='Restrict all fluids regardless of comorbid conditions or prescriptions.';w3:='Ignore new fever if urinary frequency has decreased.';rationale:='Effective management includes adherence to prescribed therapy, appropriate hydration, monitoring, and recognition of worsening infection.';
   elsif t='UTI & Pyelonephritis' then cj:='Evaluate Outcomes';memory:='Infection improvement means local symptoms and systemic signs improve together.';stem:=case when role='rn' then 'Which finding best indicates to the RN that treatment for pyelonephritis is effective?' else 'Which finding should the LPN/VN document as evidence that treatment for pyelonephritis is effective?' end;correct_text:='Fever and flank discomfort are resolving, vital signs are stable, and urinary symptoms are improving.';w1:='Urinary burning improves while fever and confusion worsen.';w2:='Flank pain increases despite a lower temperature reading.';w3:='The client reports less frequency but develops hypotension.';rationale:='Clinical improvement requires favorable local and systemic trends rather than improvement in one isolated symptom.';
   elsif t='Urinary Retention' and n=1 then cj:='Recognize Cues';memory:='Retention: think bladder fullness, inability to void, small frequent amounts, and rising residual volume.';stem:=case when role='rn' then 'Which assessment pattern should cause the RN to suspect acute urinary retention?' else 'Which finding should the LPN/VN report as concerning for urinary retention?' end;correct_text:='Increasing suprapubic fullness and discomfort with inability to void despite repeated urge.';w1:='A client voids an expected amount without discomfort.';w2:='Urine is pale yellow after increased oral fluids.';w3:='The client asks where the bathroom is located.';rationale:='Bladder distention, discomfort, urge, and inability to void are characteristic cues of urinary retention.';
   elsif t='Urinary Retention' and n=2 then cj:='Take Action';memory:='Suspected retention: assess bladder/voiding, follow the ordered protocol, and avoid delaying decompression when clinically indicated.';stem:=case when role='rn' then 'A postoperative client has not voided and reports increasing suprapubic pressure. Which RN action is appropriate?' else 'A postoperative client under LPN/VN care has not voided and reports increasing suprapubic pressure. Which action is appropriate?' end;correct_text:=case when role='rn' then 'Assess bladder distention and voiding history, use the ordered bladder-scan/retention protocol, and intervene or escalate based on findings.' else 'Collect focused voiding and bladder-distention data, follow the established bladder-scan/retention protocol, and report findings promptly.' end;w1:='Encourage the client to wait until the next shift before reassessment.';w2:='Give large amounts of fluid without considering orders or clinical status.';w3:='Document the complaint without assessing bladder status.';rationale:='Prompt focused assessment and use of the established retention protocol prevent prolonged bladder overdistention and complications.';
   else cj:='Evaluate Outcomes';memory:='Retention improvement = effective emptying plus relief, not simply one void.';stem:=case when role='rn' then 'Which finding best indicates that interventions for urinary retention have been effective?' else 'Which finding should the LPN/VN document as evidence that the established plan for urinary retention is effective?' end;correct_text:='The client voids effectively with relief of suprapubic discomfort and an acceptable post-void residual according to the plan.';w1:='The client passes a few drops but suprapubic fullness increases.';w2:='The urge to void disappears while bladder distention worsens.';w3:='The client drinks more fluid but remains unable to void.';rationale:='Effective bladder emptying is demonstrated by adequate voiding, symptom relief, and an acceptable residual measurement when assessed.';end if;
   insert into public.questions(id,slug,lifecycle_status,current_version) values(qid,role||'-renal-'||slug||'-'||n,'active',1) on conflict(id) do update set lifecycle_status='active',current_version=1;
   insert into public.question_versions(id,question_id,version,stem,item_type,exam_tracks,subject,topic,client_need,clinical_judgment_step,difficulty,rationale_correct,rationale_distractors,memory_rule,source_note,validation_status,professional_role_focus,track_rationale) values(vid,qid,1,stem,'single_best_answer',array[role],'Adult Health: Renal & Urinary',t,'Physiological Adaptation',cj,diff,rationale,'Each distractor is plausible but represents a stable finding, unsafe/delayed action, isolated improvement, or response that does not address the priority renal or urinary problem.',memory,'Original NursePrepIQ pilot item calibrated to current NCLEX test-plan and item-writing principles. Not an NCSBN item. Clinical editorial validation required.','pilot',focus,trationale) on conflict(question_id,version) do nothing;
   if pos=1 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(vid,'a',correct_text,true,rationale,1),(vid,'b',w1,false,'Does not address the priority finding or safest response.',2),(vid,'c',w2,false,'Lower priority or inconsistent with the concerning trend.',3),(vid,'d',w3,false,'Does not demonstrate the intended clinical response.',4) on conflict(question_version_id,option_key) do nothing;
   elsif pos=2 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(vid,'a',w1,false,'Does not address the priority finding or safest response.',1),(vid,'b',correct_text,true,rationale,2),(vid,'c',w2,false,'Lower priority or inconsistent with the concerning trend.',3),(vid,'d',w3,false,'Does not demonstrate the intended clinical response.',4) on conflict(question_version_id,option_key) do nothing;
   elsif pos=3 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(vid,'a',w1,false,'Does not address the priority finding or safest response.',1),(vid,'b',w2,false,'Lower priority or inconsistent with the concerning trend.',2),(vid,'c',correct_text,true,rationale,3),(vid,'d',w3,false,'Does not demonstrate the intended clinical response.',4) on conflict(question_version_id,option_key) do nothing;
   else insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(vid,'a',w1,false,'Does not address the priority finding or safest response.',1),(vid,'b',w2,false,'Lower priority or inconsistent with the concerning trend.',2),(vid,'c',w3,false,'Does not demonstrate the intended clinical response.',3),(vid,'d',correct_text,true,rationale,4) on conflict(question_version_id,option_key) do nothing; end if;
  end loop; end loop; end loop;
end $$;