-- NursePrepIQ 0021: clean the eight earliest cardiovascular foundation items.
-- No clinical/pilot validation is asserted and nothing is published by this migration.
begin;

update public.questions set lifecycle_status='pilot',updated_at=now()
where id::text like '81000000-0000-4000-8000-00000000000%';

-- ACS RN: replace giveaway choices with competing first-hour priorities.
update public.question_versions set stem='The RN receives a client with 25 minutes of substernal pressure, diaphoresis, nausea, BP 94/60 mm Hg, and new ST-segment changes. Which action should the RN prioritize while the chest-pain response is activated?',difficulty='hard',clinical_judgment_step='Take Action',rationale_correct='The client has ongoing ischemic symptoms with borderline perfusion and ECG change. Immediate focused reassessment and coordinated ACS response preserve time-sensitive treatment options while identifying instability.',rationale_distractors='All alternatives can occur in ACS care, but each either delays immediate physiologic assessment or assumes stability before the client has been reassessed.' where id='82000000-0000-4000-8000-000000000001';
update public.question_options set option_text=case option_key when 'a' then 'Obtain a complete cardiovascular risk-factor history before initiating further assessment.' when 'b' then 'Rapidly reassess vital signs and perfusion and continue the facility ACS response without delay.' when 'c' then 'Administer the next available prescribed medication before reassessing the falling blood pressure.' when 'd' then 'Prepare discharge-risk teaching while awaiting the first diagnostic results.' end,is_correct=(option_key='b'),rationale=case option_key when 'a' then 'Risk history matters, but it must not delay assessment of current hemodynamic instability.' when 'b' then 'This addresses immediate perfusion status while keeping the time-sensitive ACS pathway moving.' when 'c' then 'Medication decisions must account for the client’s current hemodynamics; reassessment cannot be skipped.' when 'd' then 'Teaching is inappropriate while acute ischemia and possible instability are being evaluated.' end where question_version_id='82000000-0000-4000-8000-000000000001';

-- ACS PN: focused change recognition and escalation.
update public.question_versions set stem='The LPN/VN is caring for a client being evaluated for acute coronary syndrome. Thirty minutes after the previous assessment, chest pressure increases from 3/10 to 7/10, the client is diaphoretic, and BP falls from 126/74 to 92/58 mm Hg. What is the priority action?',difficulty='hard',clinical_judgment_step='Recognize Cues',rationale_correct='The worsening symptoms and falling blood pressure represent a significant change from baseline. The LPN/VN should remain with the client, obtain focused data within scope, and immediately escalate according to the emergency plan.',rationale_distractors='The competing responses may be appropriate later, but none should delay communication of a worsening perfusion pattern.' where id='82000000-0000-4000-8000-000000000002';
update public.question_options set option_text=case option_key when 'a' then 'Repeat the pain score after completing the current medication pass.' when 'b' then 'Review the client’s dietary and activity history for possible triggers.' when 'c' then 'Remain with the client, obtain focused data within scope, and immediately notify/activate the RN or emergency response.' when 'd' then 'Document the change first so the trend is available when the RN is notified.' end,is_correct=(option_key='c'),rationale=case option_key when 'a' then 'The deterioration is already established; delaying escalation for routine work is unsafe.' when 'b' then 'Trigger assessment does not outrank a current pattern of worsening ischemia and hypotension.' when 'c' then 'This matches PN monitoring, safety, and prompt escalation responsibilities for acute deterioration.' when 'd' then 'Documentation is important but must not precede urgent communication.' end where question_version_id='82000000-0000-4000-8000-000000000002';

-- Dysrhythmia RN: require synthesis rather than spotting one obvious finding.
update public.question_versions set stem='The RN reviews four clients with new rhythm changes. Which client requires assessment first?',difficulty='hard',clinical_judgment_step='Prioritize Hypotheses',rationale_correct='A new rapid irregular rhythm accompanied by hypotension, confusion, cool skin, and chest discomfort indicates impaired perfusion and hemodynamic instability and outranks rhythm changes in otherwise stable clients.',rationale_distractors='A rhythm abnormality alone does not determine urgency; the client’s perfusion and symptoms establish priority.' where id='82000000-0000-4000-8000-000000000003';
update public.question_options set option_text=case option_key when 'a' then 'A client with occasional premature beats who is alert, normotensive, and denies symptoms.' when 'b' then 'A client with a rapid irregular rhythm, BP 82/50 mm Hg, new confusion, cool skin, and chest discomfort.' when 'c' then 'A client with a slow resting pulse who is sleeping, easily aroused, and has a stable blood pressure.' when 'd' then 'A client with a known chronic irregular rhythm whose rate and symptoms are unchanged from baseline.' end,is_correct=(option_key='b'),rationale=case option_key when 'a' then 'Ectopy deserves evaluation, but preserved perfusion makes this client less urgent.' when 'b' then 'The rhythm change is producing multisystem evidence of inadequate perfusion and requires immediate assessment.' when 'c' then 'A stable, asymptomatic resting bradycardic pattern is lower priority than shock-like findings.' when 'd' then 'An unchanged chronic pattern without deterioration is lower priority.' end where question_version_id='82000000-0000-4000-8000-000000000003';

-- Dysrhythmia PN.
update public.question_versions set stem='The LPN/VN notes a client with a known dysrhythmia is newly dizzy. BP has fallen from 118/70 to 88/54 mm Hg and the client becomes unsteady when sitting up. Which response is priority?',difficulty='hard',clinical_judgment_step='Take Action',rationale_correct='The change suggests reduced perfusion and creates an immediate fall risk. Focused assessment, safety measures, and prompt RN notification are required.',rationale_distractors='The other actions either delay escalation, add risk, or focus on a chronic diagnosis rather than the acute change.' where id='82000000-0000-4000-8000-000000000004';
update public.question_options set option_text=case option_key when 'a' then 'Assist the client to ambulate so the effect of activity on the rhythm can be assessed.' when 'b' then 'Compare the current rhythm with yesterday’s tracing before taking any safety action.' when 'c' then 'Keep the client safe, collect focused data within scope, and promptly report the blood-pressure and symptom change.' when 'd' then 'Encourage oral fluids first and reassess at the next scheduled vital-sign check.' end,is_correct=(option_key='c'),rationale=case option_key when 'a' then 'Ambulation increases injury risk in a dizzy, hypotensive client.' when 'b' then 'Rhythm comparison can follow immediate safety and escalation of the perfusion change.' when 'c' then 'This addresses both immediate injury prevention and timely communication of deterioration.' when 'd' then 'Empiric fluids and delayed reassessment are inappropriate without considering the cause and plan of care.' end where question_version_id='82000000-0000-4000-8000-000000000004';

-- Hypertension RN: make teaching evaluation less obvious.
update public.question_versions set stem='After hypertension teaching, which client statement requires the RN to clarify the plan before discharge?',difficulty='medium',clinical_judgment_step='Evaluate Outcomes',rationale_correct='Using normal home readings as permission to independently stop prescribed therapy reflects misunderstanding; controlled readings may represent treatment effectiveness.',rationale_distractors='The other statements reflect appropriate self-management concepts while allowing individualized instructions from the care team.' where id='82000000-0000-4000-8000-000000000005';
update public.question_options set option_text=case option_key when 'a' then 'I will record home readings at the times recommended and bring the log to follow-up visits.' when 'b' then 'If my readings stay normal for a week, I can stop the prescribed medicine and restart it if they rise.' when 'c' then 'I will ask before using over-the-counter products that may affect my blood pressure.' when 'd' then 'I will continue the lifestyle changes in my plan even when my readings improve.' end,is_correct=(option_key='b'),rationale=case option_key when 'a' then 'Structured home monitoring supports ongoing evaluation.' when 'b' then 'Prescribed antihypertensive therapy should not be stopped and restarted independently based on a short run of readings.' when 'c' then 'Checking potentially interacting or blood-pressure-raising products is appropriate.' when 'd' then 'Lifestyle measures remain important when blood pressure is controlled.' end where question_version_id='82000000-0000-4000-8000-000000000005';

-- Hypertension PN.
update public.question_versions set stem='The LPN/VN reinforces an established hypertension teaching plan. Which statement should be reported to the RN as an unresolved learning need?',difficulty='medium',clinical_judgment_step='Evaluate Outcomes',rationale_correct='Independent medication stopping and restarting based on a few home readings indicates misunderstanding requiring reinforcement and communication.',rationale_distractors='The other statements are consistent with safe adherence and monitoring within the established plan.' where id='82000000-0000-4000-8000-000000000006';
update public.question_options set option_text=case option_key when 'a' then 'I will keep a record of my home blood-pressure readings as instructed.' when 'b' then 'Once my readings are normal for several days, I can stop the medicine until they rise again.' when 'c' then 'I will call the clinic if I have the warning symptoms they told me to report.' when 'd' then 'I will keep follow-up appointments even when I feel well.' end,is_correct=(option_key='b'),rationale=case option_key when 'a' then 'This follows the established monitoring plan.' when 'b' then 'The statement shows unsafe misunderstanding of prescribed long-term therapy.' when 'c' then 'Reporting specified warning symptoms is appropriate.' when 'd' then 'Continued follow-up is part of safe chronic-disease management.' end where question_version_id='82000000-0000-4000-8000-000000000006';

-- PAD RN.
update public.question_versions set stem='The RN receives four reports about clients with peripheral arterial disease. Which finding requires the most urgent follow-up?',difficulty='hard',clinical_judgment_step='Prioritize Hypotheses',rationale_correct='A sudden cold, pale, painful foot with a newly absent pulse represents an acute change in arterial perfusion and threatens limb viability.',rationale_distractors='Chronic claudication and trophic skin changes matter, but an abrupt loss of perfusion is the time-critical finding.' where id='82000000-0000-4000-8000-000000000007';
update public.question_options set option_text=case option_key when 'a' then 'Calf discomfort occurs after walking two blocks and resolves after several minutes of rest.' when 'b' then 'A foot that was warm earlier is now cold and pale with sudden pain and a previously palpable pulse is no longer detected.' when 'c' then 'Hair growth is sparse over both lower legs and the skin is chronically shiny.' when 'd' then 'A client asks for help planning a gradual smoking-cessation strategy.' end,is_correct=(option_key='b'),rationale=case option_key when 'a' then 'Predictable exertional claudication is important but does not indicate sudden limb-threatening ischemia.' when 'b' then 'The abrupt neurovascular change is concerning for acute arterial occlusion and requires urgent action.' when 'c' then 'These are chronic arterial-insufficiency findings.' when 'd' then 'Risk-factor modification is important but is not an acute perfusion emergency.' end where question_version_id='82000000-0000-4000-8000-000000000007';

-- PAD PN.
update public.question_versions set stem='During focused neurovascular checks, the LPN/VN finds one foot is newly cool and pale, capillary refill is markedly slower than earlier, and the previously palpable pedal pulse is difficult to detect. What is the priority response?',difficulty='hard',clinical_judgment_step='Recognize Cues',rationale_correct='The clustered change from baseline suggests worsening arterial perfusion. The LPN/VN should protect the extremity, collect focused data within scope, and promptly escalate the finding.',rationale_distractors='The alternatives either delay recognition or use actions that can injure ischemic tissue or fail to address the acute change.' where id='82000000-0000-4000-8000-000000000008';
update public.question_options set option_text=case option_key when 'a' then 'Reassess at the end of the shift to determine whether the change persists.' when 'b' then 'Apply a heating pad to the foot to improve local circulation.' when 'c' then 'Compare focused neurovascular findings with baseline, protect the extremity, and promptly notify the RN.' when 'd' then 'Massage the foot and lower leg before repeating the pulse assessment.' end,is_correct=(option_key='c'),rationale=case option_key when 'a' then 'A sudden perfusion change requires prompt escalation, not delayed reassessment.' when 'b' then 'Direct heat can injure poorly perfused tissue and does not correct an acute arterial problem.' when 'c' then 'This appropriately recognizes deterioration, protects the limb, and escalates within PN scope.' when 'd' then 'Massage is not an appropriate response to suspected acute arterial compromise.' end where question_version_id='82000000-0000-4000-8000-000000000008';

-- Record only non-clinical gates that this cleanup can honestly establish.
insert into public.question_validation_events(question_id,question_version,gate,outcome,validator,notes,evidence)
select qv.question_id,qv.version,g.gate,'pass','NursePrepIQ automated cleanup',case g.gate when 'schema' then 'Existing SBA structure retained with four options and one keyed answer.' when 'editorial' then 'Stem, competing distractors, option-specific rationales, and RN/PN framing revised in 0021.' else 'Revised for application/clinical-judgment reasoning and entry-level RN/PN role framing; not a clinical accuracy attestation.' end,jsonb_build_object('migration','0021_cleanup_cardiovascular_foundation.sql','automated',true)
from public.question_versions qv cross join (values('schema'::text),('editorial'::text),('nclex_alignment'::text)) g(gate)
where qv.id::text like '82000000-0000-4000-8000-00000000000%'
and not exists(select 1 from public.question_validation_events e where e.question_id=qv.question_id and e.question_version=qv.version and e.gate=g.gate and e.outcome='pass');

commit;
