-- NursePrepIQ 0032: 100 original multidisciplinary NCLEX-style pilot questions
-- SAFETY: PILOT ONLY. No production publication or human/psychometric validation is asserted.
-- Design: 25 clinical scenarios x 4 role/reasoning variants = 100 items; 50 RN + 50 PN.
-- Covers all currently planned website categories and all six NCSBN clinical-judgment functions.
-- Evidence/alignment basis: 2026 NCLEX-RN/PN test plans and standard entry-level nursing safety principles.

begin;

do $$
declare
  s record; v int; idx int:=0; qid uuid; qvid uuid; role text; cj text; stem text; slug text;
  pos int; focus text; tracknote text;
begin
for s in select * from (values
('Fundamentals','Falls & Mobility','Safety and Infection Prevention and Control','An older adult becomes dizzy when standing after two days of poor intake. BP changes from 128/74 supine to 98/60 standing and gait is unsteady.','Assist the client back to a safe seated or supine position and reassess before ambulation.','Encourage independent walking to build tolerance.','Continue the planned shower and document the dizziness afterward.','Ask the client to remain standing until the dizziness passes.','The orthostatic drop with symptoms and unsteady gait creates an immediate fall risk; safety and reassessment come before mobility goals.'),
('Fundamentals','Pressure Injury Prevention','Basic Care and Comfort','A bedbound client has nonblanchable erythema over the sacrum and needs assistance with repositioning.','Offload pressure, reposition using an individualized schedule, inspect the skin, and address moisture and nutrition risks.','Massage the reddened area firmly at each turn.','Place a donut-shaped cushion directly under the sacrum.','Limit repositioning to avoid disturbing the client.','Nonblanchable erythema is an early pressure-injury cue; pressure relief and risk-factor management are priorities.'),
('Adult Health','Heart Failure','Physiological Adaptation','A client with heart failure gains 2.3 kg (5 lb) in 3 days and develops new orthopnea, bilateral crackles, and increasing ankle edema.','Recognize worsening fluid congestion and promptly escalate assessment and treatment of decompensated heart failure.','Reassure the client that weight gain is expected with reduced activity.','Encourage unrestricted oral fluids before reassessing lung sounds.','Delay follow-up until the next routine clinic visit.','Rapid weight gain plus orthopnea, crackles, and edema is a coherent pattern of worsening congestion requiring prompt action.'),
('Adult Health','Acute Coronary Syndrome','Physiological Adaptation','A client with coronary disease develops new crushing substernal pressure, diaphoresis, nausea, and ST-segment changes.','Treat the findings as possible acute myocardial ischemia and activate the established emergency/ACS response immediately.','Ask the client to rest quietly and reassess after the next meal.','Attribute the symptoms to anxiety because diaphoresis can occur with panic.','Complete routine medications before reporting the change.','New ischemic symptoms with ECG changes are time-sensitive and require immediate evaluation and treatment.'),
('Adult Health','Stroke','Physiological Adaptation','A client suddenly develops facial droop, right-arm weakness, and difficulty speaking; last-known-well was 35 minutes ago.','Activate the stroke response immediately and preserve the exact last-known-well time for time-sensitive evaluation.','Give oral fluids to determine whether swallowing is intact.','Allow the client to sleep and repeat the neurologic exam in one hour.','Administer a sedative for anxiety before further assessment.','Sudden focal neurologic deficits within a known time window require immediate stroke evaluation; oral intake and delays are unsafe.'),
('Adult Health','COPD','Physiological Adaptation','A client with COPD becomes increasingly drowsy; respirations are shallow, air movement is diminished, and oxygenation worsens despite prescribed therapy.','Recognize impending ventilatory failure and escalate immediately while supporting airway and oxygenation per the established plan.','Interpret the lower respiratory effort as improvement and reduce monitoring.','Encourage ambulation to mobilize secretions before reassessment.','Wait for the next scheduled respiratory treatment before reporting the change.','Drowsiness, shallow respirations, diminished airflow, and worsening oxygenation indicate dangerous ventilatory deterioration.'),
('Adult Health','Acute Kidney Injury','Reduction of Risk Potential','A client with acute kidney injury has decreasing urine output, potassium 6.3 mEq/L, new muscle weakness, and peaked T waves.','Treat the hyperkalemia with ECG changes as an immediate threat and escalate for urgent treatment.','Encourage a potassium-rich snack because urine output is low.','Wait for the next routine electrolyte panel to confirm the result.','Focus first on teaching about long-term renal diet choices.','Severe hyperkalemia with ECG changes can cause lethal dysrhythmias and outranks routine teaching or delayed confirmation.'),
('Pharmacology','Insulin Safety','Pharmacological and Parenteral Therapies','A client receiving insulin becomes diaphoretic, shaky, confused, and has a bedside glucose of 48 mg/dL.','Treat symptomatic hypoglycemia immediately using the appropriate glucose rescue route based on swallowing ability and consciousness.','Administer the scheduled rapid-acting insulin before treating the glucose.','Restrict carbohydrate intake until the next meal.','Recheck the glucose in two hours before intervening.','Symptomatic glucose of 48 mg/dL requires immediate treatment; delaying or giving more insulin can worsen neuroglycopenia.'),
('Pharmacology','Anticoagulant Safety','Pharmacological and Parenteral Therapies','A client taking an anticoagulant reports black tarry stools, dizziness, and new weakness; blood pressure is trending downward.','Suspect clinically significant bleeding and promptly escalate assessment while avoiding actions that could increase bleeding until prescriptions are clarified.','Reassure the client that dark stools are an expected medication effect.','Encourage vigorous ambulation to improve the dizziness.','Delay reporting until the next scheduled laboratory draw.','Melena with dizziness, weakness, and falling blood pressure suggests significant bleeding and possible hemodynamic compromise.'),
('Pharmacology','Opioid Safety','Pharmacological and Parenteral Therapies','After an opioid dose, a client is difficult to arouse, respirations are 7/min and shallow, and oxygen saturation is falling.','Support ventilation, summon immediate help, and follow the opioid-reversal/emergency protocol.','Let the client sleep because sedation is an expected opioid effect.','Give the next opioid dose early to prevent rebound pain.','Offer oral fluids and reassess respiratory rate in 30 minutes.','Marked sedation with bradypnea and hypoxemia indicates opioid-induced respiratory depression and requires immediate rescue.'),
('Mental Health','Suicide Safety','Psychosocial Integrity','A client with major depression says everyone would be better without them and reports a specific suicide plan with access to the means.','Initiate immediate suicide-safety precautions, maintain appropriate observation, and escalate for urgent risk evaluation.','Promise confidentiality so the client will continue talking.','Leave the client alone briefly to promote trust and independence.','Focus first on long-term coping-skills teaching.','Specific suicidal intent, plan, and access to means indicate high acute risk; immediate safety takes priority over privacy or teaching.'),
('Mental Health','Acute Mania','Psychosocial Integrity','A client with acute mania has slept 2 hours in 3 days, paces continuously, interrupts others, and is becoming increasingly irritable.','Reduce stimulation, use concise limit setting, support hydration/nutrition and rest, and monitor for escalating risk.','Encourage a competitive group activity to use excess energy.','Engage in a lengthy debate about unrealistic beliefs.','Provide unlimited choices to increase the client sense of control.','Acute mania requires a low-stimulation environment, clear limits, physiologic support, and safety monitoring.'),
('Mental Health','Alcohol Withdrawal','Physiological Adaptation','A hospitalized client who stopped heavy alcohol use 18 hours ago develops tremor, diaphoresis, agitation, tachycardia, and increasing disorientation.','Recognize evolving alcohol withdrawal and promptly escalate for protocol-based assessment and treatment to prevent seizures or delirium.','Assume the symptoms are simply anxiety about hospitalization.','Offer caffeinated beverages to improve alertness.','Delay assessment until the client has been abstinent for 72 hours.','Autonomic hyperactivity, tremor, agitation, and disorientation after cessation of heavy alcohol use are concerning for escalating withdrawal.'),
('Maternal & Newborn','Postpartum Hemorrhage','Physiological Adaptation','One hour after vaginal birth, a client saturates a pad in 15 minutes, has a boggy enlarged uterus, HR 118/min, and feels lightheaded.','Call for help, perform immediate uterine/fundal assessment and massage as indicated, and initiate the postpartum-hemorrhage protocol.','Reassure the client that heavy bleeding is expected during the first postpartum hour.','Encourage the client to ambulate to the bathroom alone.','Delay intervention until a complete blood count result is available.','Heavy rapid bleeding with a boggy uterus and tachycardia suggests uterine atony and postpartum hemorrhage requiring immediate response.'),
('Maternal & Newborn','Severe Preeclampsia','Reduction of Risk Potential','A pregnant client at 34 weeks has BP 168/112 mm Hg, severe persistent headache, visual changes, and right-upper-quadrant pain.','Recognize severe preeclampsia features and initiate urgent maternal-fetal evaluation and prescribed seizure-prevention/antihypertensive management.','Encourage walking to reduce blood pressure naturally.','Reassess at the next routine prenatal appointment.','Offer a high-sodium snack before repeating the blood pressure.','Severe-range blood pressure with neurologic and RUQ symptoms signals high risk for eclampsia and end-organ complications.'),
('Maternal & Newborn','Newborn Respiratory Distress','Physiological Adaptation','A newborn has persistent grunting, nasal flaring, intercostal retractions, and central cyanosis after initial stabilization.','Treat the findings as respiratory distress and escalate immediately for airway, oxygenation, and neonatal evaluation.','Swaddle tightly and postpone reassessment for one hour.','Feed the newborn orally to determine whether sucking improves color.','Document the findings as normal transition without further action.','Persistent grunting, retractions, flaring, and central cyanosis are abnormal and indicate impaired gas exchange.'),
('Pediatrics','Dehydration','Physiological Adaptation','A toddler with gastroenteritis is lethargic, has dry mucous membranes, capillary refill of 4 seconds, tachycardia, and markedly decreased urine output.','Recognize significant dehydration with impaired perfusion and escalate for prompt fluid assessment and replacement.','Offer only plain water and reassess the next day.','Assume decreased urine output is expected and needs no follow-up.','Prioritize toilet-training teaching before treating hydration.','Lethargy, delayed capillary refill, tachycardia, and oliguria indicate clinically important volume depletion and impaired perfusion.'),
('Pediatrics','Asthma Deterioration','Physiological Adaptation','A school-age child with asthma becomes exhausted and drowsy; wheezing is barely audible and air movement is markedly diminished.','Recognize a silent-chest pattern as impending respiratory failure and activate emergency support.','Interpret less wheezing as evidence the bronchodilator has fully worked.','Encourage the child to run briefly to assess exercise tolerance.','Delay escalation until the next peak-flow measurement is scheduled.','Decreasing wheeze with exhaustion, drowsiness, and poor air movement is ominous because airflow may be critically reduced.'),
('Pediatrics','Meningitis Precautions','Safety and Infection Prevention and Control','A child with fever, severe headache, neck stiffness, photophobia, and petechiae is being evaluated for bacterial meningitis.','Implement appropriate transmission-based precautions promptly while urgent diagnostic and antimicrobial management proceeds.','Wait for final culture results before using additional precautions.','Place the child in a common play area to reduce anxiety.','Delay notifying the care team until the rash fades.','Suspected bacterial meningitis requires prompt precautions and urgent treatment; waiting for culture confirmation can expose others and delay care.'),
('Management of Care','Delegation','Management of Care','An RN is assigning care for four stable clients to an experienced unlicensed assistive personnel.','Delegate routine predictable tasks such as scheduled vital signs on a stable client while the RN retains assessment, teaching, and clinical judgment.','Delegate initial assessment of a client with new chest pain.','Delegate evaluation of whether a diuretic improved heart-failure symptoms.','Delegate teaching a newly diagnosed client how to self-administer insulin.','UAP delegation is appropriate for routine predictable tasks; assessment, evaluation, and teaching require licensed nursing judgment.'),
('Management of Care','Assignment to LPN/VN','Management of Care','The charge RN is assigning clients to an experienced LPN/VN and an RN on a medical-surgical unit.','Assign the LPN/VN a stable client with predictable outcomes who needs routine medications, focused monitoring, and reinforcement of established teaching.','Assign a newly admitted unstable client requiring comprehensive assessment.','Assign a client with rapidly worsening respiratory status requiring care-plan revision.','Assign responsibility for initial discharge teaching for a complex new diagnosis.','Stable predictable care within the established plan is appropriate for LPN/VN assignment; unstable assessment and care-plan decisions remain with the RN.'),
('Safety & Infection Control','C. difficile','Safety and Infection Prevention and Control','A client has frequent watery diarrhea after recent antibiotics and testing is positive for Clostridioides difficile.','Use contact precautions and soap-and-water hand hygiene after care while following environmental cleaning and treatment protocols.','Rely on alcohol hand rub alone after direct care.','Place the client on airborne precautions in a negative-pressure room.','Share noncritical equipment between rooms without dedicated cleaning.','C. difficile spores require contact precautions, appropriate environmental disinfection, and soap-and-water hand hygiene after care.'),
('Safety & Infection Control','Blood Transfusion Reaction','Reduction of Risk Potential','Fifteen minutes after a blood transfusion begins, a client develops chills, fever, low back pain, dyspnea, and hypotension.','Stop the transfusion immediately, maintain IV access with appropriate compatible fluid/tubing per protocol, and notify the provider and blood bank.','Slow the transfusion and reassess after the unit is complete.','Give an antipyretic and continue the same blood product.','Discard the blood bag before the reaction workup is initiated.','This cluster is concerning for an acute transfusion reaction; the blood product must be stopped immediately and the reaction protocol initiated.'),
('NGN Clinical Judgment','Sepsis Deterioration','Physiological Adaptation','A client with pneumonia becomes confused, RR 30/min, HR 124/min, BP 86/50 mm Hg, urine output falls, and lactate is elevated.','Prioritize suspected sepsis with impaired perfusion and initiate the facility urgent sepsis response and resuscitation pathway.','Focus first on discharge teaching about pneumonia prevention.','Wait for hypotension to persist for several hours before escalating.','Treat the confusion as an expected effect of poor sleep.','Infection plus altered mentation, hypotension, tachypnea, oliguria, and elevated lactate indicates sepsis with threatened organ perfusion.'),
('NGN Clinical Judgment','Diabetic Ketoacidosis','Physiological Adaptation','A client with diabetes has glucose 486 mg/dL, deep rapid respirations, dehydration, abdominal pain, positive ketones, and metabolic acidosis.','Recognize diabetic ketoacidosis and prioritize protocol-based fluid resuscitation, insulin therapy, and close potassium monitoring.','Restrict fluids because the glucose is elevated.','Give only a long-acting insulin dose and reassess tomorrow.','Correct the acidosis with oral antacids before addressing dehydration.','Hyperglycemia, ketones, acidosis, dehydration, and Kussmaul respirations form the DKA pattern requiring urgent coordinated treatment.')
) as x(category,topic,client_need,cues,correct,w1,w2,w3,rationale)
loop
  for v in 1..4 loop
    idx:=idx+1;
    role:=case when v in (1,3) then 'rn' else 'pn' end;
    cj:=(array['Recognize Cues','Analyze Cues','Prioritize Hypotheses','Generate Solutions','Take Action','Evaluate Outcomes'])[((idx-1)%6)+1];
    pos:=((idx-1)%4)+1;
    slug:=format('0032-%s-%s-%s',role,regexp_replace(lower(s.topic),'[^a-z0-9]+','-','g'),v);
    stem:=case cj
      when 'Recognize Cues' then format('%s Which finding or interpretation should the %s recognize as most important?',s.cues,upper(role))
      when 'Analyze Cues' then format('%s How should the %s analyze this cluster of findings?',s.cues,upper(role))
      when 'Prioritize Hypotheses' then format('%s Which clinical problem should the %s prioritize?',s.cues,upper(role))
      when 'Generate Solutions' then format('%s Which plan best addresses the priority problem for the %s?',s.cues,upper(role))
      when 'Take Action' then format('%s Which action should the %s take first?',s.cues,upper(role))
      else format('%s Which response or outcome would best show that the %s priority management is appropriate?',s.cues,upper(role)) end;
    if role='rn' then
      focus:='RN comprehensive assessment, prioritization, intervention, coordination, teaching, and evaluation.';
      tracknote:='RN framing requires comprehensive assessment and independent nursing judgment within entry-level RN scope.';
    else
      focus:='PN focused data collection, safe implementation of the established plan, monitoring, reinforcement, and prompt reporting.';
      tracknote:='PN framing emphasizes recognition, focused monitoring, established interventions, and timely escalation within entry-level PN scope.';
    end if;
    qid:=md5('npq-'||slug)::uuid; qvid:=md5('npq-v-'||slug)::uuid;
    insert into public.questions(id,slug,lifecycle_status,current_version) values(qid,slug,'pilot',1)
      on conflict on constraint questions_slug_key do update set lifecycle_status='pilot',updated_at=now(),current_version=1;
    insert into public.question_versions(id,question_id,version,stem,item_type,exam_tracks,subject,topic,client_need,clinical_judgment_step,difficulty,rationale_correct,rationale_distractors,memory_rule,source_note,validation_status,professional_role_focus,track_rationale)
    values(qvid,qid,1,stem,'single_best_answer',array[role],s.category,s.topic,s.client_need,cj,case when v=1 then 'medium' else 'hard' end,s.rationale,
      'Each distractor is clinically plausible in a nearby context but either delays response, misreads the cue cluster, exceeds safe delegation, or fails to address the immediate priority.',
      'Cluster cues, identify the immediate threat, then choose the safest scope-appropriate response.',
      'Original NursePrepIQ pilot item. Alignment basis: 2026 NCLEX-RN/PN test-plan clinical-judgment and Client Needs framework; clinical editorial review required before production. Not an NCSBN item.',
      'pilot',focus,tracknote)
    on conflict(question_id,version) do update set stem=excluded.stem,validation_status='pilot' returning id into qvid;
    delete from public.question_options where question_version_id=qvid;
    if pos=1 then
      insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values
      (qvid,'a',s.correct,true,s.rationale,1),(qvid,'b',s.w1,false,'This response delays or misdirects care and does not address the highest-priority cue cluster.',2),(qvid,'c',s.w2,false,'This option may sound reasonable in another context but is unsafe or lower priority for the findings presented.',3),(qvid,'d',s.w3,false,'This response fails to address the immediate physiologic, safety, or scope-of-practice priority.',4);
    elsif pos=2 then
      insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values
      (qvid,'a',s.w1,false,'This response delays or misdirects care and does not address the highest-priority cue cluster.',1),(qvid,'b',s.correct,true,s.rationale,2),(qvid,'c',s.w2,false,'This option may sound reasonable in another context but is unsafe or lower priority for the findings presented.',3),(qvid,'d',s.w3,false,'This response fails to address the immediate physiologic, safety, or scope-of-practice priority.',4);
    elsif pos=3 then
      insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values
      (qvid,'a',s.w1,false,'This response delays or misdirects care and does not address the highest-priority cue cluster.',1),(qvid,'b',s.w2,false,'This option may sound reasonable in another context but is unsafe or lower priority for the findings presented.',2),(qvid,'c',s.correct,true,s.rationale,3),(qvid,'d',s.w3,false,'This response fails to address the immediate physiologic, safety, or scope-of-practice priority.',4);
    else
      insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values
      (qvid,'a',s.w1,false,'This response delays or misdirects care and does not address the highest-priority cue cluster.',1),(qvid,'b',s.w2,false,'This option may sound reasonable in another context but is unsafe or lower priority for the findings presented.',2),(qvid,'c',s.w3,false,'This response fails to address the immediate physiologic, safety, or scope-of-practice priority.',3),(qvid,'d',s.correct,true,s.rationale,4);
    end if;
  end loop;
end loop;
end $$;

commit;
