-- NursePrepIQ 0033: second 100-question multidisciplinary NCLEX-style pilot batch
-- SAFETY: PILOT ONLY. No human, clinical, pilot-performance, or psychometric validation is asserted.
-- Design: 25 new clinical scenarios x 4 RN/PN reasoning variants = 100 original items; 50 RN + 50 PN.
-- Coverage: every website category plus all six NCSBN clinical-judgment functions.
-- Evidence/alignment basis: 2026 NCLEX-RN/PN test-plan framework and standard entry-level nursing safety principles.

begin;

do $$
declare
 s record; v int; idx int:=0; qid uuid; qvid uuid; role text; cj text; stem text; slug text; pos int; opt text[]; rat text[];
begin
for s in select * from (values
('Fundamentals','Aspiration Prevention','Safety and Infection Prevention and Control','An older adult with a recent stroke coughs and develops a wet voice after taking a sip of water before a swallowing screen.','Stop oral intake, position safely, assess respiratory status, and obtain swallowing evaluation before further oral intake.','Offer a straw so liquids bypass the front of the mouth.','Encourage several more sips to determine whether coughing resolves.','Place food at the bedside so the client can practice independently.','Coughing and a wet voice after swallowing are aspiration cues; stopping oral intake and protecting the airway are safer than further trials.'),
('Fundamentals','Postoperative Mobility','Basic Care and Comfort','A postoperative client becomes pale and dizzy on first ambulation; heart rate rises from 82 to 116/min and blood pressure falls from 126/76 to 92/58 mm Hg.','Assist the client to sit or lie down safely, reassess, and escalate persistent hemodynamic instability before further ambulation.','Continue walking because early mobility prevents complications.','Ask the client to stand still until the blood pressure normalizes.','Document the event and retry ambulation without reassessment later.','Symptomatic hypotension and tachycardia during ambulation create immediate fall and perfusion risks requiring safe positioning and reassessment.'),
('Adult Health','GI Bleeding','Physiological Adaptation','A client with a history of peptic ulcer disease has coffee-ground emesis, melena, heart rate 122/min, blood pressure 88/54 mm Hg, and cool clammy skin.','Prioritize possible major gastrointestinal hemorrhage with shock and activate urgent resuscitation and bleeding evaluation.','Offer clear liquids to replace the fluid lost in emesis.','Give an oral antacid and reassess after it takes effect.','Delay escalation until a stool occult-blood result is available.','Overt GI bleeding with hypotension, tachycardia, and cool skin indicates threatened circulation and requires immediate resuscitative care.'),
('Adult Health','Hyperglycemic Crisis','Physiological Adaptation','An older adult with type 2 diabetes is profoundly dehydrated and confused; glucose is 812 mg/dL, serum osmolality is high, and ketones are minimal.','Recognize hyperosmolar hyperglycemic state and prioritize protocol-based fluid resuscitation with careful electrolyte and glucose management.','Restrict fluids because hyperglycemia causes osmotic diuresis.','Treat only with a bedtime long-acting insulin dose.','Encourage ambulation to improve glucose utilization.','Extreme hyperglycemia, hyperosmolality, dehydration, and neurologic change with minimal ketosis are characteristic of HHS and require urgent fluid-centered management.'),
('Adult Health','Tension Pneumothorax','Physiological Adaptation','After central-line placement, a client develops sudden severe dyspnea, unilateral absent breath sounds, hypotension, tachycardia, and increasing respiratory distress.','Suspect tension pneumothorax and activate emergency response for immediate decompression while supporting oxygenation.','Place the client flat and wait for a routine chest radiograph.','Encourage coughing and deep breathing for presumed atelectasis.','Reassess in 30 minutes after giving an oral analgesic.','Abrupt unilateral absent breath sounds with respiratory distress and shock after an invasive thoracic procedure is a time-critical tension pneumothorax pattern.'),
('Adult Health','Digoxin Toxicity','Reduction of Risk Potential','A client taking digoxin reports nausea and yellow-green visual changes; heart rate is 46/min and potassium is abnormal after several days of poor intake.','Hold the medication and promptly escalate suspected digoxin toxicity for rhythm, electrolyte, and drug-level evaluation.','Give the dose with food to reduce nausea.','Double the next dose if the pulse rises above 60/min.','Reassure the client that color-vision changes are expected.','GI symptoms, visual disturbance, and marked bradycardia are classic toxicity cues; electrolyte disturbance can increase dysrhythmia risk.'),
('Pharmacology','Heparin Complication','Pharmacological and Parenteral Therapies','A client receiving unfractionated heparin has a platelet count fall from 228,000 to 92,000/mm3 and develops new unilateral leg pain and swelling.','Suspect heparin-induced thrombocytopenia, stop heparin per protocol, and urgently notify the prescriber for alternative anticoagulation evaluation.','Continue heparin because thrombosis proves the dose is too low.','Massage the painful leg to improve venous return.','Wait for the platelet count to fall below 20,000/mm3 before reporting.','A substantial platelet fall with new thrombosis during heparin exposure is concerning for HIT, a prothrombotic emergency requiring heparin cessation.'),
('Pharmacology','ACE Inhibitor Safety','Pharmacological and Parenteral Therapies','A client newly taking an ACE inhibitor develops lip and tongue swelling with hoarseness and difficulty swallowing.','Treat the findings as angioedema, stop the medication, and activate emergency airway evaluation.','Reassure the client that facial swelling is an expected transient effect.','Give the next dose with food and observe for improvement.','Schedule a routine clinic visit next month.','Tongue/lip swelling with hoarseness can rapidly obstruct the airway and is a serious ACE-inhibitor adverse reaction.'),
('Pharmacology','Lithium Toxicity','Pharmacological Therapies','A client taking lithium develops coarse tremor, vomiting, ataxia, slurred speech, and increasing confusion after several days of diarrhea.','Hold lithium and urgently evaluate for toxicity, dehydration, renal function, and serum lithium concentration.','Give the lithium early because diarrhea lowers absorption.','Recommend sodium restriction to reduce fluid retention.','Encourage strenuous exercise to improve coordination.','GI losses can raise lithium concentration; coarse tremor, ataxia, dysarthria, and confusion are concerning toxicity findings.'),
('Mental Health','Serotonin Syndrome','Physiological Adaptation','After serotonergic medications are combined, a client develops agitation, diaphoresis, fever, diarrhea, hyperreflexia, and inducible clonus.','Suspect serotonin toxicity, stop serotonergic agents, and escalate urgently for supportive management and complication monitoring.','Interpret the findings as expected antidepressant activation.','Administer another serotonergic dose to reduce agitation.','Encourage vigorous exercise to reduce muscle stiffness.','Autonomic instability, hyperreflexia, clonus, fever, and agitation after serotonergic exposure form a serotonin-syndrome pattern.'),
('Mental Health','Panic Attack','Psychosocial Integrity','A client in the emergency department is hyperventilating, trembling, and saying they are dying; medical causes of acute cardiopulmonary symptoms are being evaluated.','Remain with the client, use brief calm statements, reduce stimulation, and coach slower breathing while continuing appropriate medical assessment.','Leave the client alone so dependence does not develop.','Give detailed teaching about long-term cognitive therapy during peak panic.','Challenge the fear as irrational and insist the client stop hyperventilating.','During acute panic, presence, simple communication, reduced stimulation, and physiologic safety are more effective than complex teaching or confrontation.'),
('Mental Health','Antipsychotic Emergency','Physiological Adaptation','A client taking an antipsychotic develops high fever, severe generalized rigidity, confusion, tachycardia, and labile blood pressure.','Suspect neuroleptic malignant syndrome, hold the antipsychotic, and activate urgent medical treatment.','Give the next antipsychotic dose early to control confusion.','Encourage ambulation to relieve rigidity.','Reassure the client that fever is a common harmless effect.','Hyperthermia, severe rigidity, altered mental status, and autonomic instability after antipsychotic exposure are characteristic of NMS.'),
('Maternal & Newborn','Umbilical Cord Prolapse','Physiological Adaptation','Immediately after rupture of membranes, fetal heart rate falls to 70/min and a loop of umbilical cord is visible at the vaginal opening.','Call for emergency assistance, relieve pressure on the cord with appropriate positioning/manual elevation, and prepare for urgent birth.','Push the cord back into the uterus and leave the client supine.','Encourage the client to walk to improve fetal descent.','Wait for a full 10-minute fetal tracing before notifying the obstetric team.','Cord prolapse with fetal bradycardia threatens fetal oxygenation; relieving compression and expediting birth are immediate priorities.'),
('Maternal & Newborn','Magnesium Toxicity','Reduction of Risk Potential','A client receiving magnesium sulfate for severe preeclampsia has respirations 8/min, absent patellar reflexes, and decreasing level of consciousness.','Stop magnesium, summon urgent assistance, support respirations, and prepare to administer the prescribed antidote calcium gluconate.','Increase the magnesium infusion because reflexes are absent.','Place the client alone in a dark room and reassess in one hour.','Encourage oral fluids as the only intervention.','Respiratory depression, absent reflexes, and CNS depression indicate magnesium toxicity and require immediate cessation and reversal support.'),
('Maternal & Newborn','Neonatal Hypoglycemia','Reduction of Risk Potential','A newborn of a diabetic parent is jittery, lethargic, feeding poorly, and has a bedside glucose below the facility treatment threshold.','Initiate the neonatal hypoglycemia protocol promptly with feeding or IV glucose based on severity and clinical status, then reassess glucose.','Delay treatment until the newborn develops seizures.','Give sterile water because it contains no excess calories.','Keep the newborn NPO for six hours to rest the gastrointestinal tract.','Symptomatic neonatal hypoglycemia can cause neurologic injury and requires prompt glucose treatment and reassessment.'),
('Pediatrics','Epiglottitis','Physiological Adaptation','A child has high fever, severe sore throat, drooling, muffled voice, inspiratory stridor, and sits leaning forward.','Keep the child calm, avoid throat instrumentation, and activate expert airway management immediately.','Use a tongue depressor to inspect the throat thoroughly.','Force the child to lie flat for a complete examination.','Offer oral fluids to assess swallowing before calling for help.','Drooling, stridor, tripod positioning, and muffled voice suggest critical upper-airway obstruction; agitation or throat examination can precipitate complete obstruction.'),
('Pediatrics','Seizure Safety','Safety and Infection Prevention and Control','A hospitalized child develops a generalized tonic-clonic seizure while in bed.','Protect the child from injury, position to support airway when feasible, time the seizure, and summon appropriate help without restraining or placing objects in the mouth.','Insert a padded tongue blade between the teeth.','Hold the extremities firmly to stop the movements.','Give oral medication during the convulsion.','Seizure care prioritizes airway and injury prevention; restraint and objects or oral intake during convulsions can cause harm.'),
('Pediatrics','Intussusception','Physiological Adaptation','An infant has episodic severe crying with knees drawn to the abdomen, vomiting, lethargy between episodes, and red currant-jelly stool.','Recognize possible intussusception and escalate urgently for diagnostic and reduction treatment while monitoring perfusion.','Treat the stool as expected from dietary iron and discharge the infant.','Give a laxative for presumed constipation.','Delay evaluation until abdominal pain becomes continuous.','Intermittent colicky pain, vomiting, lethargy, and bloody mucus stool are classic for bowel telescoping with ischemia risk.'),
('Management of Care','Prioritization','Management of Care','At change of shift, the RN receives four clients: one with chronic back pain requesting medication, one awaiting discharge teaching, one with new stridor after thyroid surgery, and one with stable atrial fibrillation.','Assess the client with new postoperative stridor first because airway compromise can progress rapidly.','See the client requesting chronic pain medication first because pain is subjective.','Complete discharge teaching first to prevent delay in transportation.','Assess the client with stable chronic atrial fibrillation before the postoperative client.','New stridor after neck surgery signals possible airway obstruction and outranks stable or non-life-threatening needs.'),
('Management of Care','Change in Condition','Management of Care','An LPN/VN reports that a previously stable client is newly confused, oxygen saturation has fallen from 96% to 88%, and respiratory rate is 30/min.','The RN should immediately assess the client and direct urgent interventions because the new findings indicate acute deterioration.','Ask the LPN/VN to document the findings and recheck them at the end of shift.','Delegate the comprehensive assessment to unlicensed assistive personnel.','Wait until routine rounds because the client was stable earlier.','Acute neurologic and respiratory changes require RN assessment and timely escalation rather than delayed or inappropriate delegation.'),
('Safety & Infection Control','Neutropenia Safety','Safety and Infection Prevention and Control','A client receiving chemotherapy has an absolute neutrophil count of 400/mm3 and an oral temperature of 38.3 C (100.9 F).','Treat fever with severe neutropenia as an emergency and promptly initiate the facility neutropenic-fever evaluation and antimicrobial pathway.','Give a rectal suppository for fever before notifying the provider.','Wait for visible signs of infection because neutropenic clients often have fever.','Bring fresh flowers to improve the room environment.','Severe neutropenia blunts inflammatory signs; fever may be the only sign of life-threatening infection and requires rapid evaluation and treatment.'),
('Safety & Infection Control','Tuberculosis Isolation','Safety and Infection Prevention and Control','A client with weight loss, night sweats, hemoptysis, and an upper-lobe cavitary lesion is admitted with suspected pulmonary tuberculosis.','Place the client in airborne infection isolation and use appropriate respiratory protection while diagnostic evaluation proceeds.','Use contact precautions only because tuberculosis spreads by surfaces.','Place the client in a positive-pressure room.','Delay isolation until sputum culture confirms tuberculosis.','Suspected infectious pulmonary tuberculosis requires prompt airborne precautions and appropriate room airflow/respiratory protection before confirmation.'),
('Safety & Infection Control','Central Line Infection','Reduction of Risk Potential','A client with a central venous catheter develops fever, rigors, hypotension, and new confusion during an infusion.','Stop nonessential infusion as appropriate, assess urgently for catheter-related bloodstream infection/sepsis, obtain ordered cultures, and initiate the sepsis pathway.','Assume the chills are caused by room temperature and add blankets only.','Flush the line rapidly to clear possible contamination.','Wait for redness at the insertion site before reporting systemic symptoms.','Fever, rigors, hypotension, and confusion in a client with central access suggest bloodstream infection with sepsis risk even without local redness.'),
('NGN Clinical Judgment','Compartment Syndrome','Physiological Adaptation','A client with a tibial fracture in a cast has escalating pain despite analgesia, pain with passive toe stretch, tense swelling, and new paresthesia.','Recognize evolving compartment syndrome and escalate immediately for pressure-relieving evaluation while avoiding delay from routine pain treatment.','Elevate the extremity high above the heart and reassess tomorrow.','Apply additional circumferential compression over the cast.','Reassure the client that severe pain is expected after every fracture.','Pain out of proportion, pain with passive stretch, tense swelling, and sensory change indicate threatened tissue perfusion requiring emergency treatment.'),
('NGN Clinical Judgment','Anaphylaxis','Physiological Adaptation','Minutes after receiving an antibiotic, a client develops diffuse hives, wheezing, throat tightness, hypotension, and tachycardia.','Recognize anaphylaxis and immediately activate emergency response with first-line epinephrine and airway/circulatory support per protocol.','Give an oral antihistamine and wait one hour before reassessment.','Continue the antibiotic slowly because rash alone is common.','Ask the client to walk to improve blood pressure.','Airway symptoms, bronchospasm, skin findings, and hypotension after exposure indicate anaphylaxis requiring immediate epinephrine and resuscitative support.')
) as x(category,topic,client_need,cues,correct,w1,w2,w3,rationale)
loop
 for v in 1..4 loop
  idx:=idx+1; role:=case when v in (1,3) then 'rn' else 'pn' end;
  cj:=(array['Recognize Cues','Analyze Cues','Prioritize Hypotheses','Generate Solutions','Take Action','Evaluate Outcomes'])[((idx-1)%6)+1];
  pos:=((idx-1)%4)+1;
  slug:=format('0033-%s-%s-%s',role,regexp_replace(lower(s.topic),'[^a-z0-9]+','-','g'),v);
  stem:=case cj when 'Recognize Cues' then format('%s Which cue or interpretation should the %s recognize as most important?',s.cues,upper(role)) when 'Analyze Cues' then format('%s How should the %s analyze this cluster of findings?',s.cues,upper(role)) when 'Prioritize Hypotheses' then format('%s Which clinical problem should the %s prioritize?',s.cues,upper(role)) when 'Generate Solutions' then format('%s Which plan best addresses the priority problem for the %s?',s.cues,upper(role)) when 'Take Action' then format('%s Which action should the %s take first?',s.cues,upper(role)) else format('%s Which response would best demonstrate appropriate %s management of the priority problem?',s.cues,upper(role)) end;
  qid:=md5('npq-'||slug)::uuid; qvid:=md5('npq-v-'||slug)::uuid;
  opt:=array[s.correct,s.w1,s.w2,s.w3]; rat:=array[s.rationale,'This response delays or misdirects care and does not address the highest-priority safety threat.','This choice is plausible in a different context but conflicts with the current cue cluster and priority physiology.','This action does not provide the timely assessment, escalation, or treatment required by the client findings.'];
  insert into public.questions(id,slug,lifecycle_status,current_version) values(qid,slug,'pilot',1) on conflict(slug) do update set lifecycle_status='pilot',updated_at=now(),current_version=1;
  insert into public.question_versions(id,question_id,version,stem,item_type,exam_tracks,subject,topic,client_need,clinical_judgment_step,difficulty,rationale_correct,rationale_distractors,memory_rule,source_note,validation_status,professional_role_focus,track_rationale)
  values(qvid,qid,1,stem,'single_best_answer',array[role],s.category,s.topic,s.client_need,cj,case when idx%5=0 then 'medium' else 'hard' end,s.rationale,'Incorrect options represent delay, unsafe implementation, misinterpretation of deterioration, or a lower-priority response that does not resolve the immediate clinical threat.',null,'Original NursePrepIQ pilot item aligned to the 2026 NCLEX RN/PN test-plan framework; not an NCSBN item. Requires clinical/editorial validation before production.','pilot',case when role='rn' then 'RN comprehensive assessment, prioritization, intervention, coordination, teaching, and evaluation.' else 'PN focused data collection, safe implementation of the established plan, monitoring, reinforcement, and prompt reporting.' end,case when role='rn' then 'RN framing requires comprehensive assessment and independent nursing judgment within entry-level RN scope.' else 'PN framing emphasizes recognition, focused monitoring, established interventions, and timely escalation within entry-level PN scope.' end)
  on conflict(question_id,version) do update set stem=excluded.stem returning id into qvid;
  delete from public.question_options where question_version_id=qvid;
  for i in 0..3 loop
   insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order)
   values(qvid,chr(97+i),opt[((i-pos+4)%4)+1],i=pos-1,rat[((i-pos+4)%4)+1],i+1);
  end loop;
 end loop;
end loop;
end $$;

commit;
