-- NursePrepIQ 0040: 108 original multidisciplinary RN/PN pilot questions
-- Generated from production-plan conventions: 18 scenarios x all six NCJMM functions.
-- SAFETY: PILOT ONLY. No human/psychometric validation or production promotion.
begin;
do $$
declare s record; j int; idx int:=0; role text; cj text; qslug text; qid uuid; qvid uuid; stem text; correct_text text; wrong1 text; wrong2 text; wrong3 text; rc text; pos int;
begin
for s in select * from (values
('Fundamentals','Orthostatic Fall Risk','Safety and Infection Prevention and Control','An older adult becomes dizzy on standing after an antihypertensive; blood pressure falls from 132/76 supine to 98/60 standing.','The positional blood-pressure drop with dizziness is the priority cue because it signals orthostatic intolerance and immediate fall risk.','Orthostatic hypotension with immediate fall risk','Assist with position changes, reassess vital signs, and implement fall precautions before ambulation.','Keep the client seated or supine, call for assistance, and reassess before ambulation.','The client stands without dizziness, maintains stable blood pressure, and ambulates safely with prescribed assistance.'),
('Fundamentals','Pressure Injury Prevention','Basic Care and Comfort','A bedbound client has nonblanchable sacral erythema, intact skin, moisture exposure, and limited ability to reposition.','Nonblanchable erythema over a pressure point is the priority cue because it indicates early pressure injury.','Early pressure injury with ongoing pressure and moisture risk','Offload the sacrum, establish repositioning, manage moisture, and reassess the skin.','Reposition the client to offload the sacrum and initiate the prevention plan.','Sacral erythema does not progress, skin remains intact, and pressure and moisture exposure are reduced.'),
('Adult Health','Heart Failure Deterioration','Physiological Adaptation','A client with heart failure develops new dyspnea at rest, bilateral crackles, oxygen saturation 88%, and increasing work of breathing.','The new respiratory findings cluster as acute pulmonary congestion with impaired oxygenation.','Acute decompensated heart failure with pulmonary congestion','Position upright, support oxygenation per protocol, perform focused assessment, and escalate promptly.','Position upright, apply prescribed oxygen, and escalate based on severity.','Work of breathing decreases, oxygen saturation improves toward target, and crackles and dyspnea lessen.'),
('Adult Health','Acute Ischemic Stroke','Reduction of Risk Potential','A client suddenly develops facial droop, unilateral arm weakness, and difficulty speaking; last-known-well was 35 minutes ago.','Sudden focal neurologic deficits with a recent known last-known-well time indicate a time-sensitive stroke emergency.','Acute stroke requiring immediate stroke-pathway evaluation','Activate the stroke pathway, verify glucose and last-known-well time, and prepare for urgent imaging.','Activate the facility stroke response immediately while maintaining airway and safety.','Neurologic status is rapidly evaluated, imaging is obtained without avoidable delay, and deterioration is promptly addressed.'),
('Pharmacology','Opioid Respiratory Depression','Pharmacological and Parenteral Therapies','Thirty minutes after IV opioid administration, a postoperative client is difficult to arouse, respiratory rate is 7/min, and oxygen saturation is falling.','Marked sedation with bradypnea after an opioid is the priority cue for opioid-induced respiratory depression.','Opioid-induced respiratory depression','Support airway and breathing, stop further opioid exposure, summon help, and give reversal medication per order or protocol.','Stimulate the client, support ventilation, call for immediate help, and prepare or administer naloxone as authorized.','Respiratory rate and level of consciousness improve without recurrent respiratory depression.'),
('Pharmacology','Insulin Hypoglycemia','Pharmacological Therapies','A client who received rapid-acting insulin becomes shaky, diaphoretic, confused, and has a bedside glucose of 52 mg/dL.','Adrenergic and neuroglycopenic symptoms with glucose 52 mg/dL confirm clinically significant hypoglycemia.','Acute hypoglycemia after insulin','Treat hypoglycemia promptly according to consciousness and swallowing ability, then recheck glucose.','If swallowing is safe, give rapid-acting carbohydrate immediately and recheck glucose per protocol.','Glucose rises to target and shakiness, diaphoresis, and confusion resolve without recurrence.'),
('Mental Health','Suicide Risk','Psychosocial Integrity','A depressed client says the family would be better without them, is giving away possessions, and reports access to a firearm at home.','Hopelessness, preparatory behavior, and access to a lethal means indicate elevated and potentially imminent suicide risk.','High suicide risk requiring immediate safety intervention','Maintain direct safety observation, restrict hazards, complete focused suicide-risk assessment, and escalate care.','Stay with the client, initiate suicide-safety precautions, and notify the responsible clinician immediately.','The client remains safe, lethal means are addressed, and a documented safety and disposition plan is established.'),
('Mental Health','Acute Mania','Psychosocial Integrity','A client with mania has slept two hours in three days, paces continuously, interrupts others, and is too distracted to sit for meals.','Severe sleep loss, psychomotor activation, and inability to sustain nutrition indicate escalating mania with physiologic risk.','Acute mania with impaired sleep and nutrition','Reduce stimulation, set concise limits, support sleep, and provide portable nutrition and fluids.','Move the client to a lower-stimulation setting and use concise consistent limits while addressing hydration and nutrition.','The client sleeps longer, accepts adequate fluids and nutrition, and demonstrates reduced psychomotor agitation.'),
('Maternal & Newborn','Postpartum Hemorrhage','Physiological Adaptation','One hour after vaginal birth, a client saturates a perineal pad in 15 minutes; the uterus is boggy and displaced above the umbilicus.','Heavy bleeding with a boggy enlarged uterus strongly suggests uterine atony, with possible bladder distention contributing.','Postpartum hemorrhage from uterine atony','Perform fundal massage, assess bladder status, quantify blood loss, and activate hemorrhage treatment as indicated.','Begin firm fundal massage and call for assistance while continuing hemorrhage assessment.','The uterus becomes firm and midline, bleeding decreases, and maternal vital signs remain stable.'),
('Maternal & Newborn','Preeclampsia Severe Features','Reduction of Risk Potential','A pregnant client at 35 weeks has blood pressure 168/112, severe persistent headache, visual spots, and right upper-quadrant pain.','Severe hypertension with neurologic and hepatic warning symptoms indicates preeclampsia with severe features and seizure or stroke risk.','Preeclampsia with severe features','Institute seizure precautions, perform focused maternal-fetal assessment, and urgently initiate prescribed management.','Place the client in a safe monitored setting, initiate seizure precautions, and urgently notify the obstetric team.','Blood pressure moves below the severe range, neurologic symptoms improve, and no seizure or maternal-fetal deterioration occurs.'),
('Pediatrics','Pediatric Dehydration','Physiological Adaptation','A toddler with gastroenteritis has dry mucous membranes, no tears, capillary refill 4 seconds, tachycardia, and markedly decreased urine output.','Delayed perfusion, tachycardia, and oliguria indicate clinically significant dehydration with impaired circulating volume.','Moderate-to-severe dehydration with compromised perfusion','Assess perfusion and weight, begin prescribed rehydration based on severity, and closely monitor urine output and response.','Escalate promptly for fluid replacement while monitoring perfusion, mental status, and urine output.','Capillary refill and heart rate normalize, urine output improves, and mucous membranes become moist.'),
('Pediatrics','Croup Respiratory Distress','Physiological Adaptation','A preschool child with a barking cough develops stridor at rest, suprasternal retractions, and increasing agitation.','Stridor at rest with retractions signals significant upper-airway obstruction; agitation can worsen obstruction.','Moderate-to-severe croup with threatened airway','Keep the child calm, minimize distress, support oxygenation, and give prescribed corticosteroid or nebulized epinephrine as indicated.','Keep the child with the caregiver in a position of comfort, minimize agitation, and obtain urgent respiratory treatment.','Stridor at rest and retractions diminish, oxygenation remains adequate, and the child becomes less distressed.'),
('Management of Care','Delegation Unstable Client','Management of Care','An RN is assigning care; one client has new chest pressure and diaphoresis while another needs routine bathing and two have stable scheduled care.','A new potentially ischemic symptom represents an unstable change that requires RN assessment rather than delegation.','Unstable client requiring RN assessment before routine delegated care','The RN personally assesses the client with new chest symptoms and delegates predictable routine tasks to appropriate staff.','Assess the client with new chest pressure immediately and delegate the stable hygiene task to assistive personnel.','The unstable client receives timely RN assessment while delegated stable tasks are completed safely within staff scope.'),
('Management of Care','PN Escalation','Coordinated Care','A PN caring for a postoperative client notes new confusion, heart rate 122/min, blood pressure 88/54, and cool clammy skin.','Acute confusion with hypotension and tachycardia indicates possible shock and requires immediate escalation.','Possible postoperative shock requiring rapid RN or provider escalation','Provide immediate focused supportive care within PN scope and rapidly report or escalate the unstable findings.','Remain with the client, obtain focused vital and perfusion data, and immediately notify the RN or activate escalation.','The client receives rapid higher-level assessment and stabilization without delay from routine tasks.'),
('Safety & Infection Control','C difficile Precautions','Safety and Infection Prevention and Control','A hospitalized client develops frequent watery diarrhea after antibiotics and has a positive C. difficile test.','Antibiotic exposure, watery diarrhea, and a positive test indicate C. difficile infection with contact-transmission risk.','C. difficile infection requiring transmission-based precautions','Initiate contact precautions, dedicate equipment, use sporicidal environmental cleaning, and follow current hand-hygiene guidance.','Place the client on contact precautions and ensure dedicated equipment and appropriate environmental cleaning.','Transmission precautions are consistently followed, diarrhea improves, hydration is maintained, and avoidable cross-transmission does not occur.'),
('Safety & Infection Control','Central Line Infection Prevention','Safety and Infection Prevention and Control','Before accessing a central venous catheter, the nurse notices the needleless connector was touched with an ungloved hand after skin contact.','The contaminated connector is a direct infection-risk cue and must be disinfected before line access.','Risk for central-line bloodstream infection from a contaminated access hub','Disinfect the connector using approved antiseptic and required friction and dry time before accessing the line.','Do not access the line until the connector has been properly disinfected and allowed to dry.','The line is accessed aseptically and the client develops no signs of catheter-related infection.'),
('NGN Clinical Judgment','Sepsis Unfolding Cues','Physiological Adaptation','An older adult with pneumonia becomes newly confused; temperature 39.2 C, heart rate 126, respiratory rate 30, blood pressure 86/50, and urine output is falling.','Infection plus hypotension, altered mentation, tachypnea, and oliguria indicates sepsis with organ hypoperfusion and possible septic shock.','Sepsis with circulatory and organ dysfunction','Activate the sepsis pathway, obtain ordered specimens without delaying treatment, begin prescribed resuscitation, and monitor perfusion.','Activate urgent sepsis management and begin protocol-directed resuscitation while obtaining required assessments and specimens.','Perfusion improves with rising blood pressure and urine output and improving mentation without new organ dysfunction.'),
('NGN Clinical Judgment','Hyperkalemia Deterioration','Reduction of Risk Potential','A client with kidney failure reports weakness; potassium is 6.6 mEq/L and the ECG shows new peaked T waves.','Severe hyperkalemia with ECG changes is immediately dangerous because of malignant dysrhythmia risk.','Hyperkalemia with cardiac electrical instability','Use continuous cardiac monitoring, urgently notify the provider, and prepare or give prescribed stabilizing and potassium-lowering therapies.','Initiate continuous cardiac monitoring and urgent hyperkalemia treatment per orders or protocol without delay.','ECG abnormalities resolve and serum potassium falls toward a safe range without dysrhythmia.')
) as x(category,topic,client_need,cues,analysis,hypothesis,solution,action,outcome)
loop
 role:=case when idx%2=0 then 'rn' else 'pn' end;
 for j in 1..6 loop
  idx:=idx+1; cj:=(array['Recognize Cues','Analyze Cues','Prioritize Hypotheses','Generate Solutions','Take Action','Evaluate Outcomes'])[j]; pos:=((idx-1)%4)+1;
  qslug:=format('0040-%s-%s-%s',role,regexp_replace(lower(s.topic),'[^a-z0-9]+','-','g'),j);
  if cj='Recognize Cues' then stem:=s.cues||' Which cue should the '||upper(role)||' identify as most clinically significant?'; correct_text:=s.analysis; wrong1:='A stable chronic finding unchanged from baseline is the most urgent cue.'; wrong2:='Routine discharge teaching is more urgent than the acute findings.'; wrong3:='Current abnormal findings can be deferred until one more diagnostic result is available.'; rc:=s.analysis||' Recognition prioritizes acute physiologic or safety threats over stable findings and routine teaching.';
  elsif cj='Analyze Cues' then stem:=s.cues||' Which interpretation best connects this cluster of findings for the '||upper(role)||'?'; correct_text:=s.analysis; wrong1:='The findings are unrelated expected variations without a meaningful clinical pattern.'; wrong2:='The findings primarily reflect a long-term knowledge deficit rather than an acute problem.'; wrong3:='The safest interpretation is to wait for all diagnostic results before connecting the current cues.'; rc:=s.analysis||' Analyze Cues requires linking related findings into a coherent clinical pattern.';
  elsif cj='Prioritize Hypotheses' then stem:=s.cues||' Which hypothesis should the '||upper(role)||' prioritize?'; correct_text:=s.hypothesis; wrong1:='A stable chronic problem that does not explain the new change in condition.'; wrong2:='Deficient knowledge as the immediate priority despite acute physiologic or safety findings.'; wrong3:='No priority problem can be identified until every routine assessment is complete.'; rc:='The best-supported urgent hypothesis is '||s.hypothesis||'. It explains the cue cluster and carries greater immediate risk.';
  elsif cj='Generate Solutions' then stem:=s.cues||' Which plan best addresses the priority problem for the '||upper(role)||'?'; correct_text:=s.solution; wrong1:='Delay intervention until the next routine assessment confirms the trend.'; wrong2:='Focus first on nonurgent teaching and comfort before addressing the acute change.'; wrong3:='Use a plan that omits monitoring, escalation, and the immediate safety threat.'; rc:=s.solution||' This plan directly addresses the priority threat and includes timely monitoring or escalation.';
  elsif cj='Take Action' then stem:=s.cues||' Which action should the '||upper(role)||' take first?'; correct_text:=s.action; wrong1:='Complete routine documentation before responding to the change in condition.'; wrong2:='Leave the client to obtain nonurgent supplies before initiating immediate safety measures.'; wrong3:='Wait for the next scheduled vital-sign check before responding to the abnormal findings.'; rc:=s.action||' Immediate threats are addressed before routine documentation, teaching, or delayed reassessment.';
  else stem:=s.cues||' After priority management, which outcome best indicates an effective response?'; correct_text:=s.outcome; wrong1:='Routine documentation is complete even though the original abnormal findings persist.'; wrong2:='The client can repeat teaching while the acute physiologic or safety problem remains unchanged.'; wrong3:='No additional assessment is performed even though the original priority cues continue.'; rc:=s.outcome||' Evaluate Outcomes compares the response with the desired physiologic or safety goal.'; end if;
  qid:=md5('npq-factory-'||qslug)::uuid; qvid:=md5('npq-factory-v-'||qslug)::uuid;
  insert into public.questions(id,slug,lifecycle_status,current_version) values(qid,qslug,'pilot',1) on conflict on constraint questions_slug_key do update set updated_at=now() returning id into qid;
  insert into public.question_versions(id,question_id,version,stem,item_type,exam_tracks,subject,topic,client_need,clinical_judgment_step,difficulty,rationale_correct,rationale_distractors,memory_rule,source_note,validation_status,professional_role_focus,track_rationale)
  values(qvid,qid,1,stem,'single_best_answer',array[role],s.category,s.topic,s.client_need,cj,case when idx%3=1 then 'medium' else 'hard' end,rc,'Each distractor is plausible in a nearby context but delays care, lowers the priority, misinterprets the cue cluster, or fails to answer the assigned clinical-judgment task.','Match the response to the clinical-judgment task: recognize, analyze, prioritize, plan, act, then evaluate.','Original NursePrepIQ pilot item aligned to the 2026 NCLEX RN/PN Client Needs and clinical-judgment framework. Clinical review required before production. Not an NCSBN item.','pilot',case when role='rn' then 'RN comprehensive assessment, prioritization, intervention, coordination, teaching, and evaluation.' else 'PN focused data collection, safe implementation, monitoring, reinforcement, and prompt reporting.' end,case when role='rn' then 'RN framing emphasizes comprehensive assessment and independent nursing judgment within entry-level RN scope.' else 'PN framing emphasizes focused monitoring, established interventions, and timely escalation within entry-level PN scope.' end)
  on conflict(question_id,version) do update set stem=excluded.stem,validation_status='pilot' returning id into qvid;
  delete from public.question_options where question_version_id=qvid;
  if pos=1 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',correct_text,true,rc,1),(qvid,'b',wrong1,false,'Lower priority or mismatched to the clinical-judgment task.',2),(qvid,'c',wrong2,false,'Plausible nearby concern but it does not address the immediate priority.',3),(qvid,'d',wrong3,false,'This delays, misdirects, or incompletely addresses the priority problem.',4);
  elsif pos=2 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',wrong1,false,'Lower priority or mismatched to the clinical-judgment task.',1),(qvid,'b',correct_text,true,rc,2),(qvid,'c',wrong2,false,'Plausible nearby concern but it does not address the immediate priority.',3),(qvid,'d',wrong3,false,'This delays, misdirects, or incompletely addresses the priority problem.',4);
  elsif pos=3 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',wrong1,false,'Lower priority or mismatched to the clinical-judgment task.',1),(qvid,'b',wrong2,false,'Plausible nearby concern but it does not address the immediate priority.',2),(qvid,'c',correct_text,true,rc,3),(qvid,'d',wrong3,false,'This delays, misdirects, or incompletely addresses the priority problem.',4);
  else insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',wrong1,false,'Lower priority or mismatched to the clinical-judgment task.',1),(qvid,'b',wrong2,false,'Plausible nearby concern but it does not address the immediate priority.',2),(qvid,'c',wrong3,false,'This delays, misdirects, or incompletely addresses the priority problem.',3),(qvid,'d',correct_text,true,rc,4); end if;
 end loop;
end loop;
end $$;
commit;
-- Cleaned/rekeyed from the audited 108-item factory set to avoid collision with the existing production 0038 batch.
-- Expected: 108 pilot questions; 54 RN/54 PN; 18 per NCJMM function; A/B/C/D=27 each; 72 hard/36 medium.
