-- NursePrepIQ 0045: next 108 original multidisciplinary RN/PN pilot questions
-- 18 NEW clinical scenarios x all six NCJMM functions. Every website category represented.
-- SAFETY: PILOT/UNVALIDATED ONLY. No human/psychometric validation claimed. No auto-publication.
begin;
do $$
declare s record; j int; idx int:=0; role text; cj text; qslug text; qid uuid; qvid uuid; stem text; correct_text text; wrong1 text; wrong2 text; wrong3 text; rc text; pos int;
begin
for s in select * from (values
('Fundamentals','Aspiration During Feeding','Basic Care and Comfort','An older adult with dysphagia begins coughing and develops a wet voice while being assisted with lunch.','Coughing and a wet voice during swallowing are immediate aspiration cues and require stopping oral intake.','Impaired swallowing with acute aspiration risk','Stop oral intake, position upright, assess airway and swallowing safety, and obtain appropriate evaluation before resuming feeding.','Stop the feeding, keep the client upright, and assess respiratory status and swallowing safety.','The client remains free of cough, wet voice, desaturation, and other aspiration signs with the revised feeding plan.'),
('Fundamentals','Postoperative Urinary Retention','Basic Care and Comfort','Six hours after surgery, a client reports suprapubic pressure and inability to void; the lower abdomen is distended and a bladder scan shows 620 mL.','Suprapubic distention, inability to void, and a large bladder volume indicate postoperative urinary retention.','Acute urinary retention with bladder overdistention','Confirm retention, use noninvasive measures if appropriate, and follow the prescribed catheterization protocol while monitoring output.','Address the bladder distention promptly according to the retention protocol and reassess comfort and urine output.','The bladder empties without complication, discomfort resolves, and spontaneous voiding resumes as expected.'),
('Adult Health','Upper GI Bleed Deterioration','Physiological Adaptation','A client with melena becomes pale and dizzy; heart rate is 124/min and blood pressure falls to 88/52 mm Hg.','Melena with tachycardia, hypotension, pallor, and dizziness indicates significant blood loss with impaired perfusion.','Acute gastrointestinal hemorrhage with hypovolemic instability','Support circulation, obtain rapid focused assessment, maintain IV access, prepare ordered resuscitation, and escalate urgently.','Keep the client safe, assess perfusion, and activate urgent management for suspected hemorrhagic instability.','Blood pressure and mentation improve, heart rate trends down, and there is no evidence of ongoing hemodynamic deterioration.'),
('Adult Health','Tension Pneumothorax','Physiological Adaptation','After central-line placement, a client develops sudden severe dyspnea, absent breath sounds on the right, hypotension, and increasing restlessness.','Sudden unilateral absent breath sounds with respiratory distress and hypotension after line placement suggests tension pneumothorax.','Tension pneumothorax causing obstructive shock','Provide immediate oxygenation support, summon emergency help, and prepare for urgent decompression without delaying for routine testing.','Activate emergency response, support airway and oxygenation, and prepare for immediate decompression.','Breath sounds and ventilation improve, blood pressure stabilizes, and respiratory distress rapidly decreases.'),
('Pharmacology','Digoxin Toxicity','Pharmacological and Parenteral Therapies','A client taking digoxin reports nausea and yellow-green vision; pulse is 48/min and potassium is 3.0 mEq/L.','Bradycardia, visual disturbance, nausea, and hypokalemia in a client taking digoxin strongly suggest toxicity.','Digoxin toxicity with dysrhythmia risk','Hold further digoxin, assess rhythm and relevant laboratory values, notify the prescriber, and prepare prescribed toxicity management.','Withhold the digoxin and promptly report the bradycardia and toxicity findings while monitoring cardiac status.','Heart rate stabilizes, toxicity symptoms resolve, and electrolyte abnormalities are corrected without dysrhythmia.'),
('Pharmacology','Heparin Bleeding','Pharmacological and Parenteral Therapies','A client receiving IV unfractionated heparin develops gross hematuria and oozing from venipuncture sites; aPTT is markedly above target.','Active bleeding plus excessive anticoagulation indicates heparin-associated hemorrhage requiring immediate action.','Heparin-associated bleeding from excessive anticoagulation','Stop or hold heparin per protocol, assess bleeding and hemodynamic status, notify the prescriber, and prepare reversal therapy if ordered.','Stop the heparin infusion per protocol and urgently report the bleeding while assessing circulation.','Visible bleeding stops, coagulation values return toward target, and the client remains hemodynamically stable.'),
('Mental Health','Serotonin Syndrome','Psychosocial Integrity','After a serotonergic medication increase, a client becomes agitated and diaphoretic with tremor, hyperreflexia, clonus, temperature 39.1 C, and tachycardia.','Hyperthermia, autonomic activation, hyperreflexia, and clonus after serotonergic exposure indicate serotonin toxicity.','Serotonin syndrome with risk for rapid physiologic deterioration','Stop serotonergic exposure, institute supportive cooling and monitoring, and obtain urgent medical evaluation and treatment.','Hold serotonergic medication and escalate immediately while supporting temperature, airway, and circulation.','Temperature, agitation, clonus, and autonomic instability resolve without organ injury.'),
('Mental Health','Alcohol Withdrawal Escalation','Psychosocial Integrity','Twelve hours after admission, a client who drinks heavily becomes tremulous, anxious, diaphoretic, hypertensive, and reports visual hallucinations.','Tremor, autonomic hyperactivity, anxiety, and hallucinations after alcohol cessation indicate escalating withdrawal.','Acute alcohol withdrawal with seizure and delirium risk','Institute withdrawal monitoring and safety precautions, administer protocol-directed treatment, and escalate for worsening symptoms.','Initiate the withdrawal protocol promptly, protect the client from injury, and report escalating symptoms.','Autonomic signs and agitation decrease, orientation improves, and the client remains free of seizure or delirium.'),
('Maternal & Newborn','Umbilical Cord Prolapse','Physiological Adaptation','Immediately after rupture of membranes, fetal heart rate falls to 70/min and a loop of umbilical cord is visible at the vaginal opening.','Acute fetal bradycardia with a visible cord after membrane rupture indicates cord prolapse and cord compression.','Umbilical cord prolapse causing acute fetal hypoxia','Relieve pressure on the cord, call for obstetric emergency assistance, position to reduce compression, and prepare for urgent birth.','Call for help and immediately elevate the presenting part off the cord while positioning to reduce compression.','Fetal perfusion is supported while definitive delivery occurs without avoidable delay.'),
('Maternal & Newborn','Newborn Hypoglycemia','Reduction of Risk Potential','A large-for-gestational-age newborn is jittery, has poor feeding, and has a bedside glucose of 32 mg/dL.','Jitteriness and poor feeding with glucose 32 mg/dL indicate symptomatic neonatal hypoglycemia.','Symptomatic neonatal hypoglycemia','Treat promptly according to neonatal hypoglycemia protocol, support feeding when safe, and recheck glucose after intervention.','Initiate prescribed hypoglycemia treatment immediately and reassess glucose and symptoms.','Glucose rises into the target range, jitteriness resolves, and feeding becomes effective without recurrence.'),
('Pediatrics','Epiglottitis Airway Risk','Physiological Adaptation','A child has high fever, drooling, muffled voice, inspiratory stridor, and sits leaning forward refusing to lie down.','Drooling, tripod positioning, muffled voice, and stridor indicate critical upper-airway obstruction consistent with epiglottitis.','Impending airway obstruction from suspected epiglottitis','Keep the child calm and upright, avoid throat manipulation, provide controlled oxygen support, and summon expert airway assistance.','Do not inspect the throat; keep the child calm and obtain immediate advanced airway support.','The airway remains patent with improving oxygenation and no sudden obstruction during definitive treatment.'),
('Pediatrics','DKA Cerebral Edema Warning','Reduction of Risk Potential','A child being treated for diabetic ketoacidosis develops a new severe headache, decreasing level of consciousness, and bradycardia.','New headache, declining consciousness, and bradycardia during DKA treatment are warning signs of cerebral edema.','Cerebral edema complicating DKA treatment','Treat the neurologic change as an emergency, notify the critical-care team, protect the airway, and prepare prescribed cerebral-edema therapy.','Escalate immediately for suspected cerebral edema while supporting airway and neurologic monitoring.','Neurologic status stabilizes or improves without progression to herniation or respiratory compromise.'),
('Management of Care','Blood Transfusion Reaction Delegation','Management of Care','An RN supervising a transfusion is told that the client now has chills, flank pain, and dyspnea 15 minutes after blood administration began.','Acute chills, flank pain, and dyspnea shortly after transfusion suggest a serious transfusion reaction requiring RN action.','Acute transfusion reaction requiring immediate RN assessment','The RN stops the transfusion, maintains IV access with appropriate fluid/tubing, assesses the client, and activates the reaction protocol.','The RN personally responds, stops the transfusion, and begins the facility transfusion-reaction procedure.','Symptoms are promptly evaluated and treated, the incompatible product is not restarted, and the client remains hemodynamically stable.'),
('Management of Care','Post-Fall Assignment Priority','Coordinated Care','During shift change, one client has just fallen and reports new hip pain, while other assigned clients need scheduled medications and routine dressing changes.','A new fall with pain is an acute change requiring prompt licensed-nurse assessment before routine scheduled tasks.','Possible injury after a fall requiring immediate assessment','Prioritize assessment of the fallen client, maintain safety, and redistribute or defer routine stable tasks appropriately.','Assess the client who fell before proceeding with routine care and escalate findings according to policy.','The client receives timely injury assessment and appropriate escalation while routine care is safely redistributed.'),
('Safety & Infection Control','Airborne Tuberculosis Isolation','Safety and Infection Prevention and Control','A coughing client with weight loss, night sweats, and an upper-lobe cavitary lesion arrives from the emergency department before tuberculosis is excluded.','The symptom pattern and cavitary lesion create a high suspicion for pulmonary tuberculosis with airborne transmission risk.','Suspected pulmonary tuberculosis requiring airborne precautions','Place the client in appropriate airborne isolation, use a fit-tested respirator, limit transport, and follow diagnostic precautions.','Initiate airborne precautions immediately and place the client in an airborne infection isolation room when available.','Airborne precautions are maintained consistently and no preventable exposure occurs while diagnostic evaluation proceeds.'),
('Safety & Infection Control','Needlestick Exposure','Safety and Infection Prevention and Control','A nurse sustains a hollow-bore needlestick immediately after drawing blood from a client with unknown bloodborne-pathogen status.','A fresh hollow-bore needlestick is a significant occupational blood exposure requiring immediate first aid and time-sensitive evaluation.','Occupational bloodborne-pathogen exposure','Wash the site, report immediately, obtain prompt exposure evaluation and source testing per policy, and initiate indicated prophylaxis without delay.','Wash the puncture site and immediately begin the occupational-exposure protocol.','The exposure is documented and evaluated promptly, indicated prophylaxis begins within the recommended window, and follow-up testing is arranged.'),
('NGN Clinical Judgment','Acute Compartment Syndrome','Physiological Adaptation','A client with a new lower-leg cast reports escalating pain despite analgesia; pain increases with passive toe movement and the foot feels tense with new paresthesia.','Pain out of proportion, pain with passive stretch, tense swelling, and paresthesia indicate evolving compartment syndrome.','Acute compartment syndrome threatening limb perfusion','Perform urgent neurovascular assessment, keep the limb at heart level, notify the surgical team immediately, and prepare for pressure-relieving treatment.','Treat the findings as a limb-threatening emergency and obtain immediate surgical evaluation.','Pain and neurovascular findings improve after definitive pressure relief, with preserved motor and sensory function.'),
('NGN Clinical Judgment','Adrenal Crisis','Physiological Adaptation','A client with chronic adrenal insufficiency who has been vomiting is weak and confused; blood pressure is 78/46, sodium 126, potassium 5.8, and glucose 54 mg/dL.','Profound hypotension with hyponatremia, hyperkalemia, hypoglycemia, and illness in adrenal insufficiency indicates adrenal crisis.','Adrenal crisis with shock and metabolic instability','Support circulation, obtain urgent labs as feasible, and administer prescribed stress-dose glucocorticoid, isotonic fluid, and glucose without delay.','Activate emergency management and begin prescribed fluid, glucocorticoid, and glucose replacement promptly.','Blood pressure, mentation, glucose, sodium, and potassium trend toward safe ranges without recurrent shock.')
) as x(category,topic,client_need,cues,analysis,hypothesis,solution,action,outcome)
loop
 role:=case when idx%2=0 then 'rn' else 'pn' end;
 for j in 1..6 loop
  idx:=idx+1; cj:=(array['Recognize Cues','Analyze Cues','Prioritize Hypotheses','Generate Solutions','Take Action','Evaluate Outcomes'])[j]; pos:=((idx-1)%4)+1;
  qslug:=format('0045-%s-%s-%s',role,regexp_replace(lower(s.topic),'[^a-z0-9]+','-','g'),j);
  if cj='Recognize Cues' then stem:=s.cues||' Which finding should the '||upper(role)||' recognize as most important to the immediate clinical picture?'; correct_text:=s.analysis; wrong1:='A stable baseline characteristic is more important than the new change in condition.'; wrong2:='The client''s long-term teaching needs are the most time-sensitive finding.'; wrong3:='The abnormal findings should be considered routine until the next scheduled assessment.'; rc:=s.analysis||' Recognition requires identifying the cue with the strongest connection to immediate physiologic or safety risk.';
  elsif cj='Analyze Cues' then stem:=s.cues||' Which interpretation best explains the combined findings?'; correct_text:=s.analysis; wrong1:='The findings are expected and do not form a clinically meaningful pattern.'; wrong2:='The findings are best explained by anxiety alone despite the objective abnormalities.'; wrong3:='The findings cannot be interpreted until all routine diagnostic studies are complete.'; rc:=s.analysis||' The clustered subjective and objective cues support this interpretation more strongly than benign or delayed explanations.';
  elsif cj='Prioritize Hypotheses' then stem:=s.cues||' Which problem should the '||upper(role)||' treat as the priority hypothesis?'; correct_text:=s.hypothesis; wrong1:='A chronic problem that does not account for the acute cue cluster.'; wrong2:='A knowledge deficit despite evidence of a current physiologic or safety threat.'; wrong3:='A minor comfort problem that would not explain the objective deterioration.'; rc:='The priority hypothesis is '||s.hypothesis||' because it best explains the acute cues and carries the greatest immediate risk.';
  elsif cj='Generate Solutions' then stem:=s.cues||' Which plan is most appropriate for the priority problem?'; correct_text:=s.solution; wrong1:='Reassess at the next routine interval before changing the current plan of care.'; wrong2:='Complete nonurgent teaching first, then address the acute findings if they persist.'; wrong3:='Use comfort measures alone without focused monitoring or escalation.'; rc:=s.solution||' The plan addresses the suspected cause, immediate safety, monitoring, and timely escalation rather than delaying definitive care.';
  elsif cj='Take Action' then stem:=s.cues||' Which action should the '||upper(role)||' take first?'; correct_text:=s.action; wrong1:='Document the findings completely before initiating an intervention.'; wrong2:='Leave the client to finish another stable client''s routine care before responding.'; wrong3:='Wait for the next scheduled set of vital signs before escalating the change.'; rc:=s.action||' The first action addresses the immediate threat before routine documentation, stable-client tasks, or delayed reassessment.';
  else stem:=s.cues||' After treatment is initiated, which finding best demonstrates that the priority problem is improving?'; correct_text:=s.outcome; wrong1:='The charting is complete although the original abnormal findings remain unchanged.'; wrong2:='The client verbalizes teaching while the acute physiologic problem persists.'; wrong3:='No reassessment is performed because the planned intervention has already been started.'; rc:=s.outcome||' Effective evaluation compares the post-intervention state with measurable physiologic and safety goals.'; end if;
  qid:=md5('npq-0045-'||qslug)::uuid; qvid:=md5('npq-0045-v-'||qslug)::uuid;
  insert into public.questions(id,slug,lifecycle_status,current_version) values(qid,qslug,'pilot',1) on conflict on constraint questions_slug_key do update set updated_at=now() returning id into qid;
  insert into public.question_versions(id,question_id,version,stem,item_type,exam_tracks,subject,topic,client_need,clinical_judgment_step,difficulty,rationale_correct,rationale_distractors,memory_rule,source_note,validation_status,professional_role_focus,track_rationale)
  values(qvid,qid,1,stem,'single_best_answer',array[role],s.category,s.topic,s.client_need,cj,case when idx%3=1 then 'medium' else 'hard' end,rc,'The distractors represent common but unsafe reasoning errors: downgrading an acute cue, substituting a nearby concern, delaying escalation, or evaluating process rather than patient response.','Match the response to the NCJMM function and prioritize acute physiologic or safety threats over routine care.','Original NursePrepIQ pilot item aligned to the 2026 NCLEX RN/PN Client Needs and NCJMM framework; AI/editorial review required before any promotion. Not an NCSBN item.','pilot',case when role='rn' then 'RN comprehensive assessment, prioritization, intervention, coordination, teaching, and evaluation.' else 'PN focused data collection, implementation of established care, monitoring, reinforcement, and prompt escalation.' end,case when role='rn' then 'RN framing emphasizes comprehensive assessment and nursing judgment within entry-level RN scope.' else 'PN framing emphasizes focused monitoring, safe implementation, and timely escalation within entry-level PN scope.' end)
  on conflict(question_id,version) do update set stem=excluded.stem,validation_status='pilot' returning id into qvid;
  delete from public.question_options where question_version_id=qvid;
  if pos=1 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',correct_text,true,rc,1),(qvid,'b',wrong1,false,'This response underweights the acute cue cluster.',2),(qvid,'c',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',3),(qvid,'d',wrong3,false,'This delays or incompletely addresses the priority threat.',4);
  elsif pos=2 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',wrong1,false,'This response underweights the acute cue cluster.',1),(qvid,'b',correct_text,true,rc,2),(qvid,'c',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',3),(qvid,'d',wrong3,false,'This delays or incompletely addresses the priority threat.',4);
  elsif pos=3 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',wrong1,false,'This response underweights the acute cue cluster.',1),(qvid,'b',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',2),(qvid,'c',correct_text,true,rc,3),(qvid,'d',wrong3,false,'This delays or incompletely addresses the priority threat.',4);
  else insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',wrong1,false,'This response underweights the acute cue cluster.',1),(qvid,'b',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',2),(qvid,'c',wrong3,false,'This delays or incompletely addresses the priority threat.',3),(qvid,'d',correct_text,true,rc,4); end if;
 end loop;
end loop;
if idx<>108 then raise exception '0045 expected 108 questions, generated %',idx; end if;
end $$;
commit;
-- Expected structural distribution: 108 pilot; 54 RN/54 PN; 18 per NCJMM function; A/B/C/D=27 each; 72 hard/36 medium.
-- Category distribution: 12 each Fundamentals, Adult Health, Pharmacology, Mental Health, Maternal & Newborn, Pediatrics, Management of Care, Safety & Infection Control, NGN Clinical Judgment.