-- NursePrepIQ 0050: next 108 original multidisciplinary RN/PN pilot questions; closes Musculoskeletal/Sensory gaps
-- 18 NEW clinical scenarios x all six NCJMM functions. Every website category represented.
-- SAFETY: PILOT/UNVALIDATED ONLY. No human/psychometric validation claimed. No auto-publication.
begin;
do $$
declare s record; j int; idx int:=0; role text; cj text; qslug text; qid uuid; qvid uuid; stem text; correct_text text; wrong1 text; wrong2 text; wrong3 text; rc text; pos int;
begin
for s in select * from (values
('Adult Health','Acute Limb Ischemia','Physiological Adaptation','A client with atrial fibrillation develops sudden severe left-leg pain; the foot is pale, cool, pulseless, and numb.','Sudden pain, pallor, coolness, sensory change, and absent pulse indicate acutely threatened arterial perfusion.','Acute arterial occlusion with limb-threatening ischemia','Perform urgent neurovascular assessment, protect the limb, notify the vascular team immediately, and prepare for reperfusion treatment.','Treat the findings as a vascular emergency and obtain immediate vascular evaluation.','Perfusion improves with return of pulse or Doppler flow, warmer color, improved sensation, and reduced ischemic pain.'),
('Adult Health','Hip Fracture Neurovascular Risk','Reduction of Risk Potential','An older adult with a displaced hip fracture reports increasing pain; the affected foot becomes cool with delayed capillary refill and weaker pedal pulse.','New distal coolness, delayed refill, and weaker pulse suggest worsening neurovascular compromise beyond expected fracture pain.','Neurovascular compromise associated with hip fracture','Reassess distal circulation, sensation, and movement; maintain alignment and escalate the change promptly.','Perform focused neurovascular assessment and immediately report the new perfusion change.','Distal perfusion remains intact or improves, with stable pulse, warmth, sensation, and movement.'),
('Adult Health','Retinal Detachment','Reduction of Risk Potential','A client reports sudden flashes of light, many new floaters, and a dark curtain moving across one eye without pain.','Flashes, new floaters, and a curtain-like visual field defect are classic warning cues for retinal detachment.','Retinal detachment threatening vision','Protect the affected eye from further strain and arrange urgent ophthalmologic evaluation and treatment.','Treat the sudden visual-field loss as an emergency and obtain immediate ophthalmologic evaluation.','The retina is evaluated and treated without avoidable delay and further visual-field loss is prevented.'),
('Adult Health','Acute Angle Closure Glaucoma','Physiological Adaptation','A client develops severe unilateral eye pain, headache, nausea, blurred vision with halos, and a red eye with a fixed mid-dilated pupil.','Severe painful red eye with halos, nausea, and a fixed mid-dilated pupil indicates acute angle-closure glaucoma.','Acute angle-closure glaucoma with rapidly rising intraocular pressure','Obtain emergency ophthalmic treatment and administer prescribed pressure-lowering therapy without delay.','Escalate immediately for emergency pressure-lowering treatment and ophthalmologic care.','Eye pain and nausea decrease and intraocular pressure moves toward a safe range without additional vision loss.'),
('Fundamentals','Traction Alignment','Basic Care and Comfort','A client in skeletal traction has the affected leg rotated, one weight resting on the floor, and the rope displaced from the pulley groove.','Traction is ineffective when weights are not freely suspended and the line of pull is disrupted.','Loss of therapeutic traction and body alignment','Restore prescribed alignment, ensure ropes move freely in pulley grooves, and keep weights hanging unobstructed.','Correct the traction setup so the line of pull is maintained and all prescribed weights hang freely.','Body alignment is maintained and the traction system provides continuous unobstructed prescribed pull.'),
('Fundamentals','Hearing Aid Communication','Basic Care and Comfort','An older adult with hearing loss repeatedly misunderstands discharge teaching despite wearing hearing aids in a noisy room.','Environmental noise and communication technique can impair comprehension even when hearing aids are in place.','Communication barrier related to hearing impairment','Reduce background noise, face the client, speak clearly at a normal pace, and verify understanding using teach-back.','Move to a quiet setting, face the client, and repeat teaching clearly with teach-back.','The client accurately explains the instructions and demonstrates improved communication without repeated misunderstanding.'),
('Pharmacology','Warfarin Major Bleeding','Pharmacological and Parenteral Therapies','A client taking warfarin has black stools, dizziness, blood pressure 90/56 mm Hg, and an INR of 6.8.','Melena, hypotension, dizziness, and markedly supratherapeutic INR indicate significant anticoagulant-associated bleeding.','Major warfarin-associated hemorrhage','Hold warfarin, support circulation, notify the prescriber urgently, and prepare prescribed reversal and bleeding management.','Treat the bleeding as an emergency, hold warfarin, and initiate urgent reversal/support measures as prescribed.','Bleeding stops, hemodynamics stabilize, and coagulation values move toward the therapeutic or safe range.'),
('Pharmacology','Lithium Toxicity','Pharmacological and Parenteral Therapies','A client taking lithium develops vomiting, coarse tremor, ataxia, slurred speech, and increasing confusion after several days of dehydration.','GI symptoms with coarse tremor, ataxia, dysarthria, and confusion after dehydration strongly suggest lithium toxicity.','Lithium toxicity with neurologic deterioration','Hold lithium, assess hydration and renal status, obtain urgent lithium level and electrolytes, and escalate for toxicity treatment.','Withhold lithium and obtain urgent medical evaluation while supporting hydration and neurologic safety.','Neurologic symptoms improve and lithium concentration declines without seizure, dysrhythmia, or renal deterioration.'),
('Mental Health','Neuroleptic Malignant Syndrome','Physiological Adaptation','A client taking an antipsychotic develops high fever, severe generalized rigidity, confusion, diaphoresis, and autonomic instability.','Hyperthermia, lead-pipe rigidity, altered mental status, and autonomic instability after antipsychotic exposure indicate neuroleptic malignant syndrome.','Neuroleptic malignant syndrome with life-threatening hyperthermia','Stop the causative medication, provide aggressive supportive care and cooling, and obtain emergency medical treatment.','Hold the antipsychotic and activate emergency treatment while supporting airway, circulation, temperature, and hydration.','Temperature and rigidity decrease, autonomic status stabilizes, and renal and other organ complications are avoided.'),
('Mental Health','Panic Attack Immediate Care','Psychosocial Integrity','A client in the clinic suddenly becomes intensely fearful, hyperventilates, trembles, and says, “I am dying,” while unable to follow complex directions.','Severe anxiety with hyperventilation and inability to process complex information is consistent with an acute panic episode after immediate medical threats are assessed.','Acute panic with impaired ability to process information','Remain with the client, reduce stimulation, use brief calm statements, and coach slow breathing while assessing safety and physical status.','Stay with the client and use short calm directions in a low-stimulation setting.','Respiratory rate and distress decrease and the client can again process information and engage in coping strategies.'),
('Maternal & Newborn','Shoulder Dystocia','Physiological Adaptation','During vaginal birth the fetal head delivers but retracts against the perineum and the shoulders do not deliver with usual gentle traction.','Retraction of the delivered head with failure of shoulder delivery is a key cue for shoulder dystocia.','Shoulder dystocia causing risk of fetal hypoxia and birth injury','Call for obstetric assistance and initiate established shoulder-dystocia maneuvers without fundal pressure.','Activate the shoulder-dystocia response and assist with prescribed maneuvers immediately.','The shoulders and infant are delivered promptly with neonatal assessment and no avoidable delay from ineffective maneuvers.'),
('Maternal & Newborn','Newborn Respiratory Distress','Physiological Adaptation','A newborn at 20 minutes of life has persistent grunting, nasal flaring, intercostal retractions, and central cyanosis.','Persistent grunting, flaring, retractions, and central cyanosis indicate significant neonatal respiratory compromise.','Neonatal respiratory distress with impaired oxygenation','Support thermoregulation and airway, assess oxygenation, provide prescribed respiratory support, and escalate neonatal care immediately.','Initiate neonatal respiratory support and urgent evaluation while maintaining warmth and airway patency.','Work of breathing and cyanosis decrease and oxygenation reaches the prescribed target without deterioration.'),
('Pediatrics','Meningococcal Meningitis','Safety and Infection Prevention and Control','A school-age child has fever, severe headache, neck stiffness, photophobia, and a rapidly spreading petechial rash.','Meningeal symptoms with a rapidly spreading petechial rash suggest meningococcal disease and risk for rapid deterioration and transmission.','Suspected meningococcal meningitis with sepsis risk','Initiate droplet precautions, support stabilization, and obtain urgent medical evaluation and prescribed antimicrobial treatment.','Place the child on droplet precautions and activate urgent evaluation and treatment.','Hemodynamic and neurologic status stabilize while appropriate isolation and definitive treatment are maintained.'),
('Pediatrics','Intussusception','Physiological Adaptation','An infant has episodic severe crying with knees drawn to the abdomen, vomiting, lethargy between episodes, and currant-jelly stool.','Intermittent colicky pain, vomiting, lethargy, and blood-mucus stool strongly suggest intussusception.','Intussusception with bowel obstruction and ischemia risk','Keep the infant NPO, assess hydration and perfusion, establish prescribed IV support, and prepare for urgent reduction.','Escalate for urgent reduction while maintaining NPO status and supporting hydration and perfusion.','Abdominal pain and obstruction resolve, perfusion remains stable, and stool pattern returns toward normal without perforation.'),
('Management of Care','Fresh Postoperative Deterioration Assignment','Management of Care','At shift start, an RN must choose which client to assess first: one two hours after abdominal surgery now restless with heart rate 128/min and falling blood pressure, while three others have stable scheduled needs.','New restlessness, tachycardia, and falling blood pressure soon after surgery indicate possible hemorrhage or shock and require immediate RN assessment.','Unstable postoperative client with possible hemorrhagic shock','The RN immediately assesses the unstable postoperative client and delegates or defers predictable stable care.','Assess the newly unstable postoperative client first and redistribute routine tasks to appropriate staff.','The unstable client receives rapid assessment and escalation while stable clients continue to receive appropriate delegated care.'),
('Safety & Infection Control','Chemical Splash to Eye','Safety and Infection Prevention and Control','A nurse accidentally splashes a caustic cleaning solution into one eye and immediately reports burning and tearing.','A caustic ocular exposure requires immediate irrigation; delaying for paperwork or detailed examination can increase tissue injury.','Chemical eye exposure with risk of ocular injury','Begin continuous eye irrigation immediately, remove contact lenses if easily possible, and activate occupational/emergency evaluation.','Start copious eye irrigation at once before completing incident documentation.','Ocular pH and symptoms improve with prompt irrigation and appropriate follow-up evaluation is completed.'),
('NGN Clinical Judgment','Spinal Cord Compression','Physiological Adaptation','A client with metastatic cancer develops new severe back pain, bilateral leg weakness, numbness, and new urinary retention.','New back pain with bilateral neurologic deficits and bladder dysfunction suggests spinal cord compression.','Malignant spinal cord compression threatening permanent neurologic function','Institute safety precautions, perform focused neurologic assessment, and obtain emergency oncologic/neurosurgical evaluation and prescribed treatment.','Treat the new neurologic deficits as an emergency and obtain immediate higher-level evaluation.','Neurologic function stabilizes or improves and further motor, sensory, and bladder deterioration is prevented.'),
('NGN Clinical Judgment','Anaphylaxis After Antibiotic','Physiological Adaptation','Minutes after an IV antibiotic begins, a client develops diffuse hives, wheezing, facial swelling, and blood pressure 76/42 mm Hg.','Rapid skin, airway, respiratory, and circulatory findings after medication exposure indicate anaphylaxis.','Anaphylactic shock with airway compromise','Stop the exposure, activate emergency response, give intramuscular epinephrine per protocol, support airway and circulation, and prepare additional treatment.','Activate emergency response and administer IM epinephrine promptly while supporting airway, breathing, and circulation.','Wheezing and swelling decrease, blood pressure improves, and oxygenation stabilizes without biphasic deterioration.')
) as x(category,topic,client_need,cues,analysis,hypothesis,solution,action,outcome)
loop
 role:=case when idx%2=0 then 'rn' else 'pn' end;
 for j in 1..6 loop
  idx:=idx+1; cj:=(array['Recognize Cues','Analyze Cues','Prioritize Hypotheses','Generate Solutions','Take Action','Evaluate Outcomes'])[j]; pos:=((idx-1)%4)+1;
  qslug:=format('0050-%s-%s-%s',role,regexp_replace(lower(s.topic),'[^a-z0-9]+','-','g'),j);
  if cj='Recognize Cues' then stem:=s.cues||' Which finding should the '||upper(role)||' recognize as most important to the immediate clinical picture?'; correct_text:=s.analysis; wrong1:='A stable baseline characteristic is more important than the new change in condition.'; wrong2:='The client''s long-term teaching needs are the most time-sensitive finding.'; wrong3:='The abnormal findings should be considered routine until the next scheduled assessment.'; rc:=s.analysis||' Recognition requires identifying the cue with the strongest connection to immediate physiologic or safety risk.';
  elsif cj='Analyze Cues' then stem:=s.cues||' Which interpretation best explains the combined findings?'; correct_text:=s.analysis; wrong1:='The findings are expected and do not form a clinically meaningful pattern.'; wrong2:='The findings are best explained by anxiety alone despite the objective abnormalities.'; wrong3:='The findings cannot be interpreted until all routine diagnostic studies are complete.'; rc:=s.analysis||' The clustered subjective and objective cues support this interpretation more strongly than benign or delayed explanations.';
  elsif cj='Prioritize Hypotheses' then stem:=s.cues||' Which problem should the '||upper(role)||' treat as the priority hypothesis?'; correct_text:=s.hypothesis; wrong1:='A chronic problem that does not account for the acute cue cluster.'; wrong2:='A knowledge deficit despite evidence of a current physiologic or safety threat.'; wrong3:='A minor comfort problem that would not explain the objective deterioration.'; rc:='The priority hypothesis is '||s.hypothesis||' because it best explains the acute cues and carries the greatest immediate risk.';
  elsif cj='Generate Solutions' then stem:=s.cues||' Which plan is most appropriate for the priority problem?'; correct_text:=s.solution; wrong1:='Reassess at the next routine interval before changing the current plan of care.'; wrong2:='Complete nonurgent teaching first, then address the acute findings if they persist.'; wrong3:='Use comfort measures alone without focused monitoring or escalation.'; rc:=s.solution||' The plan addresses the suspected cause, immediate safety, monitoring, and timely escalation rather than delaying definitive care.';
  elsif cj='Take Action' then stem:=s.cues||' Which action should the '||upper(role)||' take first?'; correct_text:=s.action; wrong1:='Document the findings completely before initiating an intervention.'; wrong2:='Leave the client to finish another stable client''s routine care before responding.'; wrong3:='Wait for the next scheduled set of vital signs before escalating the change.'; rc:=s.action||' The first action addresses the immediate threat before routine documentation, stable-client tasks, or delayed reassessment.';
  else stem:=s.cues||' After treatment is initiated, which finding best demonstrates that the priority problem is improving?'; correct_text:=s.outcome; wrong1:='The charting is complete although the original abnormal findings remain unchanged.'; wrong2:='The client verbalizes teaching while the acute physiologic problem persists.'; wrong3:='No reassessment is performed because the planned intervention has already been started.'; rc:=s.outcome||' Effective evaluation compares the post-intervention state with measurable physiologic and safety goals.'; end if;
  qid:=md5('npq-0050-'||qslug)::uuid; qvid:=md5('npq-0050-v-'||qslug)::uuid;
  insert into public.questions(id,slug,lifecycle_status,current_version) values(qid,qslug,'pilot',1) on conflict on constraint questions_slug_key do update set updated_at=now() returning id into qid;
  insert into public.question_versions(id,question_id,version,stem,item_type,exam_tracks,subject,topic,client_need,clinical_judgment_step,difficulty,rationale_correct,rationale_distractors,memory_rule,source_note,validation_status,professional_role_focus,track_rationale)
  values(qvid,qid,1,stem,'single_best_answer',array[role],s.category,s.topic,s.client_need,cj,case when idx%3=1 then 'medium' else 'hard' end,rc,'The distractors represent common but unsafe reasoning errors: downgrading an acute cue, substituting a nearby concern, delaying escalation, or evaluating process rather than patient response.','Match the response to the NCJMM function and prioritize acute physiologic or safety threats over routine care.','Original NursePrepIQ pilot item aligned to the 2026 NCLEX RN/PN Client Needs and NCJMM framework; AI/editorial review required before any promotion. Not an NCSBN item.','pilot',case when role='rn' then 'RN comprehensive assessment, prioritization, intervention, coordination, teaching, and evaluation.' else 'PN focused data collection, implementation of established care, monitoring, reinforcement, and prompt escalation.' end,case when role='rn' then 'RN framing emphasizes comprehensive assessment and nursing judgment within entry-level RN scope.' else 'PN framing emphasizes focused monitoring, safe implementation, and timely escalation within entry-level PN scope.' end)
  on conflict(question_id,version) do update set stem=excluded.stem,validation_status='pilot' returning id into qvid;
  delete from public.question_options where question_version_id=qvid;
  if pos=1 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',correct_text,true,rc,1),(qvid,'b',wrong1,false,'This response underweights the acute cue cluster.',2),(qvid,'c',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',3),(qvid,'d',wrong3,false,'This delays or incompletely addresses the priority threat.',4);
  elsif pos=2 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',wrong1,false,'This response underweights the acute cue cluster.',1),(qvid,'b',correct_text,true,rc,2),(qvid,'c',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',3),(qvid,'d',wrong3,false,'This delays or incompletely addresses the priority threat.',4);
  elsif pos=3 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',wrong1,false,'This response underweights the acute cue cluster.',1),(qvid,'b',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',2),(qvid,'c',correct_text,true,rc,3),(qvid,'d',wrong3,false,'This delays or incompletely addresses the priority threat.',4);
  else insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',wrong1,false,'This response underweights the acute cue cluster.',1),(qvid,'b',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',2),(qvid,'c',wrong3,false,'This delays or incompletely addresses the priority threat.',3),(qvid,'d',correct_text,true,rc,4); end if;
 end loop;
end loop;
if idx<>108 then raise exception '0050 expected 108 questions, generated %',idx; end if;
end $$;
commit;
-- Expected structural distribution: 108 pilot; 54 RN/54 PN; 18 per NCJMM function; A/B/C/D=27 each; 72 hard/36 medium.
-- Category distribution: 12 each Fundamentals, Adult Health, Pharmacology, Mental Health, Maternal & Newborn, Pediatrics, Management of Care, Safety & Infection Control, NGN Clinical Judgment.