-- NursePrepIQ 0053: next 108 original multidisciplinary RN/PN pilot questions; expands emergency, safety, delegation, maternal, pediatric, pharmacology, and NGN coverage
-- 18 NEW clinical scenarios x all six NCJMM functions. Every website category represented.
-- SAFETY: PILOT/UNVALIDATED ONLY. No human/psychometric validation claimed. No auto-publication.
begin;
do $$
declare s record; j int; idx int:=0; role text; cj text; qslug text; qid uuid; qvid uuid; stem text; correct_text text; wrong1 text; wrong2 text; wrong3 text; rc text; pos int;
begin
for s in select * from (values
('Adult Health','Acute Aortic Dissection','Physiological Adaptation','A client develops abrupt severe tearing chest pain radiating to the back with unequal arm blood pressures and a new weak left radial pulse.','Abrupt tearing chest-to-back pain with pulse and blood-pressure asymmetry signals possible aortic dissection and threatened organ perfusion.','Acute aortic dissection','Limit exertion, obtain immediate emergency cardiovascular evaluation, closely monitor perfusion, and prepare prescribed anti-impulse and definitive therapy.','Treat the presentation as a cardiovascular emergency and activate immediate evaluation while maintaining strict monitoring.','Pain and hemodynamics stabilize without new neurologic, renal, or limb perfusion deficits.'),
('Adult Health','Acute Compartment Syndrome','Reduction of Risk Potential','Six hours after tibial fracture fixation, a client reports escalating pain despite analgesia and pain with passive toe extension; the lower leg feels tense.','Pain out of proportion, pain with passive stretch, and tense swelling are early high-risk cues for compartment syndrome even before pulses disappear.','Acute compartment syndrome threatening limb viability','Perform urgent neurovascular assessment, avoid constrictive positioning, and immediately escalate for compartment-pressure evaluation and possible fasciotomy.','Report the findings immediately and prepare for emergency evaluation rather than waiting for pulse loss.','Pain and neurovascular findings improve after timely decompression, with preserved motor and sensory function.'),
('Adult Health','Myasthenic Respiratory Weakness','Physiological Adaptation','A client with myasthenia gravis develops increasing difficulty swallowing, a weak cough, shallow respirations, and inability to count beyond a few numbers in one breath.','Bulbar weakness, weak cough, and declining respiratory endurance indicate impending ventilatory failure.','Myasthenic crisis with respiratory compromise','Prioritize airway and ventilation assessment, obtain respiratory support, keep suction available, and escalate immediately for higher-level care.','Activate urgent respiratory support and monitor ventilatory function rather than focusing on routine medication teaching.','Ventilation and airway protection stabilize without aspiration or respiratory arrest.'),
('Adult Health','Acute Kidney Injury Hyperkalemia','Physiological Adaptation','A client with acute kidney injury has potassium 6.7 mEq/L, increasing weakness, and new peaked T waves on the cardiac monitor.','Severe hyperkalemia plus ECG changes indicates immediate risk of lethal dysrhythmia.','Life-threatening hyperkalemia associated with acute kidney injury','Place on continuous cardiac monitoring, notify the provider urgently, and prepare prescribed membrane stabilization and potassium-lowering therapy.','Treat the ECG-changing hyperkalemia immediately and prepare emergency potassium-lowering interventions.','Cardiac rhythm remains stable and serum potassium falls toward a safe range.'),
('Fundamentals','Postoperative Atelectasis Prevention','Basic Care and Comfort','A stable client on postoperative day one has shallow respirations and diminished bibasilar breath sounds after avoiding coughing because of incisional discomfort.','Shallow breathing and diminished bases after surgery suggest poor lung expansion and risk for atelectasis.','Postoperative impaired lung expansion','Provide pain-control support, reposition upright, encourage coughing/deep breathing and incentive spirometry, and mobilize as appropriate.','Assist the client to improve lung expansion with upright positioning, pulmonary hygiene, and prescribed ambulation.','Breath sounds and inspiratory effort improve and oxygenation remains stable without fever or respiratory deterioration.'),
('Fundamentals','Pressure Injury Offloading','Basic Care and Comfort','A bedbound client has nonblanchable redness over the sacrum and frequently slides down in bed, creating moisture and shear.','Nonblanchable erythema plus pressure, moisture, and shear indicates early pressure injury requiring immediate prevention measures.','Early pressure injury with ongoing mechanical risk','Offload the sacrum, establish regular repositioning, manage moisture, reduce shear, and support nutrition and skin assessment.','Relieve pressure and shear now and institute a consistent repositioning and moisture-management plan.','The area does not progress to deeper tissue injury and surrounding skin remains intact.'),
('Pharmacology','ACE Inhibitor Angioedema','Pharmacological and Parenteral Therapies','A client taking lisinopril develops sudden lip and tongue swelling, hoarse voice, and difficulty swallowing without a rash.','Orofacial swelling with voice and swallowing changes while taking an ACE inhibitor suggests angioedema with airway threat.','ACE inhibitor associated angioedema','Stop the ACE inhibitor, prioritize airway assessment, activate emergency care, and prepare advanced airway support as needed.','Treat the swelling as an airway emergency and discontinue the ACE inhibitor.','Airway remains patent, swelling resolves, and the causative medication is documented for avoidance.'),
('Pharmacology','Vancomycin Infusion Reaction','Pharmacological and Parenteral Therapies','During a rapid IV vancomycin infusion, a client develops flushing and pruritus of the face and upper torso with stable blood pressure and no wheezing.','Flushing and pruritus during rapid vancomycin infusion with stable airway and hemodynamics are consistent with an infusion-related reaction.','Vancomycin infusion reaction','Stop or slow the infusion per protocol, assess airway and hemodynamics, notify the prescriber, and resume only as safely prescribed.','Pause the infusion and assess the client, then follow the prescribed slower-infusion management plan.','Flushing and itching resolve without progression to airway or circulatory compromise.'),
('Mental Health','Serotonin Toxicity Recognition','Physiological Adaptation','A client taking serotonergic medications develops agitation, diaphoresis, fever, diarrhea, hyperreflexia, and inducible clonus.','Hyperreflexia and clonus with autonomic and mental-status changes strongly support serotonin toxicity.','Serotonin syndrome','Stop serotonergic agents, provide urgent supportive care and cooling, and escalate for medical treatment and monitoring.','Withhold serotonergic medications and obtain emergency medical evaluation for serotonin toxicity.','Temperature, neuromuscular findings, and autonomic instability resolve without organ injury.'),
('Mental Health','Command Hallucinations Safety','Psychosocial Integrity','A client with psychosis quietly tells the nurse, “The voice keeps ordering me to stab my roommate,” and says the command is becoming harder to resist.','A specific violent command with decreasing ability to resist creates immediate risk to others and requires direct safety intervention.','Acute violence risk related to command hallucinations','Stay with the client, separate potential targets, remove access to weapons, directly assess intent and ability to resist, and activate the treatment team.','Prioritize immediate safety by maintaining observation and separating the client from the potential victim while escalating care.','No harm occurs and the client reports reduced command intensity or improved ability to resist with treatment.'),
('Maternal & Newborn','Uterine Tachysystole With Oxytocin','Reduction of Risk Potential','A laboring client receiving oxytocin has six contractions in 10 minutes with recurrent late fetal heart-rate decelerations.','Excessive uterine activity with recurrent late decelerations indicates impaired fetal oxygenation associated with oxytocin stimulation.','Oxytocin-associated uterine tachysystole with fetal intolerance','Stop oxytocin, reposition to improve uteroplacental perfusion, provide indicated supportive measures, and notify the obstetric team promptly.','Discontinue oxytocin and initiate intrauterine resuscitative measures immediately.','Contraction frequency decreases and the fetal heart-rate pattern returns toward reassuring features.'),
('Maternal & Newborn','Placental Abruption','Physiological Adaptation','A pregnant client at 35 weeks develops sudden constant abdominal pain, a rigid tender uterus, dark vaginal bleeding, and fetal tachycardia.','Painful bleeding with uterine rigidity and fetal compromise suggests placental abruption rather than painless placenta previa.','Placental abruption with maternal hemorrhage and fetal compromise','Stabilize maternal circulation, obtain urgent obstetric evaluation, monitor fetal status, and prepare for rapid delivery as indicated.','Activate emergency obstetric management while supporting maternal circulation and continuous fetal assessment.','Maternal hemodynamics stabilize and definitive delivery occurs without avoidable delay if fetal or maternal status remains compromised.'),
('Pediatrics','Epiglottitis Airway Safety','Physiological Adaptation','A child has high fever, drooling, muffled voice, inspiratory stridor, and sits leaning forward while refusing to lie down.','Drooling, tripod positioning, muffled voice, and stridor indicate possible epiglottitis with risk of sudden airway obstruction.','Acute upper-airway obstruction from suspected epiglottitis','Keep the child calm and upright, avoid throat examination, provide controlled oxygen as tolerated, and activate an expert airway team.','Do not inspect the throat; maintain a calm environment and obtain immediate advanced airway support.','Airway patency and oxygenation are maintained without provoking complete obstruction.'),
('Pediatrics','Sickle Cell Splenic Sequestration','Physiological Adaptation','A young child with sickle cell disease becomes pale and lethargic with tachycardia, abdominal fullness, and a rapidly enlarging spleen.','Acute pallor, tachycardia, lethargy, and splenic enlargement suggest sequestration with potentially severe intravascular volume loss.','Acute splenic sequestration crisis','Assess perfusion, establish urgent vascular access and monitoring, notify the pediatric team, and prepare prescribed volume and transfusion support.','Treat the child as hemodynamically unstable and obtain immediate emergency evaluation and circulatory support.','Perfusion and hemoglobin stabilize and splenic enlargement does not progress to shock.'),
('Management of Care','Delegation of Stable Ostomy Care','Management of Care','An RN is caring for four clients and must delegate one task to an experienced assistive personnel: routine emptying and measurement of output from an established ostomy in a stable client is due.','Routine nonassessment care for a stable client can be delegated when the RN retains assessment, teaching, and evaluation responsibilities.','Appropriate delegation of predictable ostomy output care','Delegate routine emptying and measurement with clear parameters for reporting abnormal output or skin concerns.','Assign the stable routine ostomy-output task to trained assistive personnel and retain evaluation responsibility.','The task is completed accurately and abnormal findings, if present, are promptly reported to the RN.'),
('Safety & Infection Control','Airborne Isolation Suspected Tuberculosis','Safety and Infection Prevention and Control','A client with weeks of cough, night sweats, weight loss, and blood-streaked sputum arrives in a crowded clinic waiting area.','The symptom cluster raises concern for pulmonary tuberculosis and requires source control and airborne precautions before diagnostic confirmation.','Suspected infectious pulmonary tuberculosis','Place a mask on the client for source control, move to an airborne infection isolation room, and use appropriate respiratory protection.','Separate the client from the waiting area and initiate airborne precautions immediately.','Potential exposures are minimized while diagnostic testing and treatment proceed under appropriate isolation.'),
('NGN Clinical Judgment','Septic Shock Despite Fluids','Physiological Adaptation','A client with suspected infection remains hypotensive at 78/44 mm Hg with lactate 5.1 mmol/L, confusion, and cool mottled skin after the prescribed initial fluid resuscitation.','Persistent hypotension, elevated lactate, altered mentation, and mottling after fluids indicate ongoing shock and inadequate tissue perfusion.','Septic shock requiring escalation of hemodynamic support','Continue sepsis management, obtain continuous monitoring, and prepare prescribed vasopressor therapy while reassessing perfusion and source control.','Escalate immediately for vasopressor and critical-care support while continuing sepsis treatment.','Mean arterial pressure and perfusion improve, lactate trends downward, and mental status and urine output recover.'),
('NGN Clinical Judgment','Diabetic Ketoacidosis Cerebral Edema Warning','Reduction of Risk Potential','A child being treated for diabetic ketoacidosis develops a new severe headache, slowing heart rate, irritability, and decreasing level of consciousness.','New headache, bradycardia, irritability, and declining consciousness during DKA treatment are warning signs of cerebral edema.','Cerebral edema complicating pediatric DKA treatment','Recognize the neurologic emergency, notify the treatment team immediately, minimize delays, and prepare prescribed hyperosmolar therapy and airway support.','Treat the neurologic change as suspected cerebral edema and activate emergency treatment immediately.','Neurologic status stabilizes without progression to herniation or respiratory failure.')
) as x(category,topic,client_need,cues,analysis,hypothesis,solution,action,outcome)
loop
 role:=case when idx%2=0 then 'rn' else 'pn' end;
 for j in 1..6 loop
  idx:=idx+1; cj:=(array['Recognize Cues','Analyze Cues','Prioritize Hypotheses','Generate Solutions','Take Action','Evaluate Outcomes'])[j]; pos:=((idx-1)%4)+1;
  qslug:=format('0053-%s-%s-%s',role,regexp_replace(lower(s.topic),'[^a-z0-9]+','-','g'),j);
  if cj='Recognize Cues' then stem:=s.cues||' Which finding should the '||upper(role)||' recognize as most important to the immediate clinical picture?'; correct_text:=s.analysis; wrong1:='A stable baseline characteristic is more important than the new change in condition.'; wrong2:='The client''s long-term teaching needs are the most time-sensitive finding.'; wrong3:='The abnormal findings should be considered routine until the next scheduled assessment.'; rc:=s.analysis||' Recognition requires identifying the cue with the strongest connection to immediate physiologic or safety risk.';
  elsif cj='Analyze Cues' then stem:=s.cues||' Which interpretation best explains the combined findings?'; correct_text:=s.analysis; wrong1:='The findings are expected and do not form a clinically meaningful pattern.'; wrong2:='The findings are best explained by anxiety alone despite the objective abnormalities.'; wrong3:='The findings cannot be interpreted until all routine diagnostic studies are complete.'; rc:=s.analysis||' The clustered subjective and objective cues support this interpretation more strongly than benign or delayed explanations.';
  elsif cj='Prioritize Hypotheses' then stem:=s.cues||' Which problem should the '||upper(role)||' treat as the priority hypothesis?'; correct_text:=s.hypothesis; wrong1:='A chronic problem that does not account for the acute cue cluster.'; wrong2:='A knowledge deficit despite evidence of a current physiologic or safety threat.'; wrong3:='A minor comfort problem that would not explain the objective deterioration.'; rc:='The priority hypothesis is '||s.hypothesis||' because it best explains the acute cues and carries the greatest immediate risk.';
  elsif cj='Generate Solutions' then stem:=s.cues||' Which plan is most appropriate for the priority problem?'; correct_text:=s.solution; wrong1:='Reassess at the next routine interval before changing the current plan of care.'; wrong2:='Complete nonurgent teaching first, then address the acute findings if they persist.'; wrong3:='Use comfort measures alone without focused monitoring or escalation.'; rc:=s.solution||' The plan addresses the suspected cause, immediate safety, monitoring, and timely escalation rather than delaying definitive care.';
  elsif cj='Take Action' then stem:=s.cues||' Which action should the '||upper(role)||' take first?'; correct_text:=s.action; wrong1:='Document the findings completely before initiating an intervention.'; wrong2:='Leave the client to finish another stable client''s routine care before responding.'; wrong3:='Wait for the next scheduled set of vital signs before escalating the change.'; rc:=s.action||' The first action addresses the immediate threat before routine documentation, stable-client tasks, or delayed reassessment.';
  else stem:=s.cues||' After treatment is initiated, which finding best demonstrates that the priority problem is improving?'; correct_text:=s.outcome; wrong1:='The charting is complete although the original abnormal findings remain unchanged.'; wrong2:='The client verbalizes teaching while the acute physiologic problem persists.'; wrong3:='No reassessment is performed because the planned intervention has already been started.'; rc:=s.outcome||' Effective evaluation compares the post-intervention state with measurable physiologic and safety goals.'; end if;
  qid:=md5('npq-0053-'||qslug)::uuid; qvid:=md5('npq-0053-v-'||qslug)::uuid;
  insert into public.questions(id,slug,lifecycle_status,current_version) values(qid,qslug,'pilot',1) on conflict on constraint questions_slug_key do update set updated_at=now() returning id into qid;
  insert into public.question_versions(id,question_id,version,stem,item_type,exam_tracks,subject,topic,client_need,clinical_judgment_step,difficulty,rationale_correct,rationale_distractors,memory_rule,source_note,validation_status,professional_role_focus,track_rationale)
  values(qvid,qid,1,stem,'single_best_answer',array[role],s.category,s.topic,s.client_need,cj,case when idx%3=1 then 'medium' else 'hard' end,rc,'The distractors represent common but unsafe reasoning errors: downgrading an acute cue, substituting a nearby concern, delaying escalation, or evaluating process rather than patient response.','Match the response to the NCJMM function and prioritize acute physiologic or safety threats over routine care.','Original NursePrepIQ pilot item aligned to the 2026 NCLEX RN/PN Client Needs and NCJMM framework; AI/editorial review required before any promotion. Not an NCSBN item.','pilot',case when role='rn' then 'RN comprehensive assessment, prioritization, intervention, coordination, teaching, and evaluation.' else 'PN focused data collection, implementation of established care, monitoring, reinforcement, and prompt escalation.' end,case when role='rn' then 'RN framing emphasizes comprehensive assessment and nursing judgment within entry-level RN scope.' else 'PN framing emphasizes focused monitoring, safe implementation, and timely escalation within entry-level PN scope.' end)
  on conflict(question_id,version) do update set stem=excluded.stem,validation_status='pilot' returning id into qvid;
  delete from public.question_options where question_version_id=qvid;
  if pos=1 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',correct_text,true,rc,1),(qvid,'b',wrong1,false,'This response underweights the acute cue cluster.',2),(qvid,'c',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',3),(qvid,'d',wrong3,false,'This delays or incompletely addresses the priority threat.',4);
  elsif pos=2 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',wrong1,false,'This response underweights the acute cue cluster.',1),(qvid,'b',correct_text,true,rc,2),(qvid,'c',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',3),(qvid,'d',wrong3,false,'This delays or incompletely addresses the priority threat.',4);
  elsif pos=3 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',wrong1,false,'This response underweights the acute cue cluster.',1),(qvid,'b',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',2),(qvid,'c',correct_text,true,rc,3),(qvid,'d',wrong3,false,'This delays or incompletely addresses the priority threat.',4);
  else insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',wrong1,false,'This response underweights the acute cue cluster.',1),(qvid,'b',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',2),(qvid,'c',wrong3,false,'This delays or incompletely addresses the priority threat.',3),(qvid,'d',correct_text,true,rc,4); end if;
 end loop;
end loop;
if idx<>108 then raise exception '0053 expected 108 questions, generated %',idx; end if;
end $$;
commit;
-- Expected structural distribution: 108 pilot; 54 RN/54 PN; 18 per NCJMM function; A/B/C/D=27 each; 72 hard/36 medium.
-- Category distribution: 12 each Fundamentals, Adult Health, Pharmacology, Mental Health, Maternal & Newborn, Pediatrics, Management of Care, Safety & Infection Control, NGN Clinical Judgment.