-- NursePrepIQ 0054: next 108 original multidisciplinary RN/PN pilot questions; expands acute care, pharmacology, maternal, pediatric, delegation, infection-control, and NGN coverage
-- 18 NEW clinical scenarios x all six NCJMM functions. Every website category represented.
-- SAFETY: PILOT/UNVALIDATED ONLY. No human/psychometric validation claimed. No auto-publication.
begin;
do $$
declare s record; j int; idx int:=0; role text; cj text; qslug text; qid uuid; qvid uuid; stem text; correct_text text; wrong1 text; wrong2 text; wrong3 text; rc text; pos int;
begin
for s in select * from (values
('Adult Health','Acute Ischemic Stroke','Physiological Adaptation','A client suddenly develops right facial droop, right arm weakness, and expressive aphasia; the last-known-well time was 35 minutes ago.','Sudden focal neurologic deficits with a known recent onset require immediate stroke activation and time-sensitive brain imaging.','Acute ischemic stroke','Activate the stroke pathway, determine exact last-known-well time, assess glucose and neurologic status, and expedite noncontrast brain imaging and reperfusion evaluation.','Initiate the stroke response immediately and expedite imaging rather than delaying for routine admission tasks.','Neurologic status is rapidly evaluated and eligible reperfusion treatment is delivered within the appropriate time window.'),
('Adult Health','Upper GI Hemorrhage','Physiological Adaptation','A client has repeated coffee-ground emesis, black tarry stool, heart rate 124/min, blood pressure 88/52 mm Hg, and cool clammy skin.','GI bleeding plus tachycardia, hypotension, and cool clammy skin indicates significant blood loss with impaired perfusion.','Acute upper gastrointestinal hemorrhage with hypovolemic shock','Prioritize airway and circulation, establish large-bore vascular access, obtain ordered blood studies and type/crossmatch, and escalate for urgent resuscitation and endoscopic management.','Treat the client as unstable from hemorrhage and initiate immediate circulatory support and emergency evaluation.','Blood pressure and perfusion stabilize, bleeding is controlled, and hemoglobin and mental status stop deteriorating.'),
('Adult Health','Tension Pneumothorax','Physiological Adaptation','After chest trauma, a client develops severe dyspnea, absent breath sounds on the right, hypotension, distended neck veins, and worsening cyanosis.','Unilateral absent breath sounds with shock and venous distention after trauma suggests tension pneumothorax causing obstructive shock.','Tension pneumothorax','Activate emergency response, support oxygenation, and prepare for immediate decompression followed by definitive chest drainage.','Treat the findings as tension pneumothorax and obtain immediate decompression without waiting for routine imaging.','Ventilation and blood pressure improve after decompression and definitive pleural drainage.'),
('Adult Health','Addisonian Crisis','Physiological Adaptation','A client with adrenal insufficiency has vomiting, profound weakness, blood pressure 78/46 mm Hg, sodium 126 mEq/L, potassium 5.9 mEq/L, and glucose 58 mg/dL.','Shock with hyponatremia, hyperkalemia, hypoglycemia, and known adrenal insufficiency indicates adrenal crisis.','Acute adrenal crisis','Support circulation with prescribed isotonic fluids, correct hypoglycemia, administer prescribed IV glucocorticoid, and monitor electrolytes and hemodynamics closely.','Initiate emergency fluid, glucose, and glucocorticoid treatment as prescribed.','Blood pressure and glucose normalize and electrolyte abnormalities improve without dysrhythmia or recurrent shock.'),
('Fundamentals','Aspiration During Enteral Feeding','Reduction of Risk Potential','During tube feeding, a client begins coughing forcefully, becomes dyspneic, and oxygen saturation falls from 96% to 86%.','Acute coughing, dyspnea, and desaturation during enteral feeding suggest aspiration and immediate respiratory compromise.','Aspiration associated with enteral feeding','Stop the feeding, position to protect the airway, assess respiratory status, provide indicated oxygen/suction support, and escalate promptly.','Stop the feeding immediately and address airway and oxygenation before troubleshooting the feeding system.','Oxygenation and respiratory effort improve without progression to respiratory failure.'),
('Fundamentals','Postoperative Urinary Retention','Elimination and Exchange','Eight hours after surgery, a client reports suprapubic pressure and inability to void despite repeated attempts; the lower abdomen is distended.','Inability to void with suprapubic fullness after anesthesia suggests postoperative urinary retention.','Postoperative urinary retention','Assess bladder volume with the available noninvasive method, promote privacy and normal voiding measures when appropriate, and catheterize if prescribed based on findings.','Assess for bladder retention before repeatedly encouraging oral fluids or ambulation alone.','Bladder distention resolves and urine is eliminated without avoidable overdistention or injury.'),
('Pharmacology','Digoxin Toxicity','Pharmacological and Parenteral Therapies','A client taking digoxin reports nausea and yellow-green visual changes; apical pulse is 48/min and potassium is low.','GI symptoms, visual disturbance, bradycardia, and hypokalemia raise concern for digoxin toxicity.','Digoxin toxicity','Hold digoxin, obtain urgent medication level and electrolytes, monitor cardiac rhythm, and notify the prescriber for toxicity management.','Withhold digoxin and obtain immediate clinical evaluation rather than administering the scheduled dose.','Heart rate and rhythm stabilize and toxicity symptoms resolve as digoxin and electrolyte abnormalities are corrected.'),
('Pharmacology','Heparin Associated Bleeding','Pharmacological and Parenteral Therapies','A client receiving IV unfractionated heparin develops hematuria, oozing from venipuncture sites, and a markedly prolonged aPTT.','Active bleeding with excessive anticoagulation while receiving heparin requires prompt cessation and reversal assessment.','Heparin-associated hemorrhage','Stop the heparin infusion, assess hemodynamic status and bleeding, notify the prescriber, and prepare prescribed protamine reversal.','Stop heparin immediately and initiate urgent bleeding and reversal management.','Bleeding decreases and coagulation parameters return toward the intended range without hemodynamic compromise.'),
('Mental Health','Alcohol Withdrawal Delirium','Physiological Adaptation','Two days after hospital admission, a client with heavy alcohol use becomes severely agitated, disoriented, diaphoretic, tremulous, and reports seeing insects on the wall.','Autonomic hyperactivity, agitation, disorientation, tremor, and visual hallucinations after alcohol cessation suggest severe withdrawal with delirium.','Alcohol withdrawal delirium','Institute seizure and fall precautions, reduce stimulation, assess withdrawal severity, and administer prescribed withdrawal treatment with close monitoring.','Treat the presentation as severe alcohol withdrawal requiring urgent medication and safety management.','Agitation and autonomic instability decrease without seizure, injury, or progression of delirium.'),
('Mental Health','Acute Mania Limit Setting','Psychosocial Integrity','A client with acute mania is intrusive, loudly interrupts peers, attempts to organize other clients, and becomes irritable when redirected.','Intrusiveness, pressured behavior, poor boundaries, and irritability require consistent structure and low-stimulation limit setting.','Acute mania with impaired boundaries and escalating stimulation','Use brief clear limits, reduce environmental stimulation, redirect consistently, and provide structured opportunities for activity and rest.','Set concise consistent limits and redirect the client to a lower-stimulation activity.','The client follows boundaries with less escalation and participates in structured care without disrupting or harming others.'),
('Maternal & Newborn','Umbilical Cord Prolapse','Physiological Adaptation','Immediately after rupture of membranes, fetal heart rate falls to 70/min and a loop of umbilical cord is visible at the vaginal opening.','Sudden profound fetal bradycardia with a visible cord after membrane rupture indicates cord prolapse and cord compression.','Umbilical cord prolapse','Call for emergency obstetric assistance, manually relieve pressure on the presenting part, position to reduce compression, and prepare for emergency birth.','Relieve cord compression immediately while activating the emergency delivery response.','Fetal heart rate improves or is supported until rapid definitive delivery occurs.'),
('Maternal & Newborn','Newborn Hypoglycemia','Reduction of Risk Potential','A large-for-gestational-age newborn is jittery and lethargic two hours after birth; bedside glucose is 32 mg/dL.','Jitteriness, lethargy, risk status, and low glucose indicate symptomatic neonatal hypoglycemia requiring prompt treatment.','Symptomatic newborn hypoglycemia','Maintain warmth, initiate feeding or prescribed glucose therapy based on severity and protocol, and recheck glucose promptly.','Treat the low glucose immediately according to neonatal protocol rather than delaying for routine newborn care.','Glucose rises to the target range and jitteriness and lethargy resolve without seizure or recurrent hypoglycemia.'),
('Pediatrics','Severe Dehydration From Gastroenteritis','Physiological Adaptation','A toddler with vomiting and diarrhea is lethargic with dry mucous membranes, no tears, capillary refill 4 seconds, tachycardia, and markedly decreased urine output.','Lethargy, delayed refill, tachycardia, oliguria, and marked dryness indicate severe volume depletion and impaired perfusion.','Severe pediatric dehydration with hypovolemia','Obtain vascular or emergency access, begin prescribed isotonic fluid resuscitation, monitor perfusion and electrolytes, and reassess frequently.','Prioritize circulatory volume restoration and urgent reassessment.','Capillary refill, mental status, heart rate, and urine output improve with rehydration.'),
('Pediatrics','Status Asthmaticus Warning','Physiological Adaptation','A child with severe asthma becomes increasingly drowsy; wheezing becomes barely audible despite marked retractions and oxygen saturation remains low after initial bronchodilator treatment.','Decreasing air movement and drowsiness in severe asthma are ominous signs of fatigue and impending respiratory failure, not improvement.','Impending respiratory failure from status asthmaticus','Activate emergency respiratory support, continue prescribed intensive bronchodilator and anti-inflammatory therapy, and prepare for advanced airway management.','Escalate immediately for impending respiratory failure rather than interpreting quieter wheezing as improvement.','Mental status, air movement, oxygenation, and work of breathing improve without respiratory arrest.'),
('Management of Care','Unstable Client Delegation','Management of Care','An RN working with an LPN/VN and assistive personnel has four clients; one client develops new chest pressure, diaphoresis, and hypotension while routine medications and hygiene are also due.','New chest pressure with diaphoresis and hypotension represents instability requiring RN assessment; predictable routine tasks can be redistributed.','Priority management of an acutely unstable client','The RN immediately assesses the unstable client and delegates stable routine care within team members’ roles.','The RN takes the unstable client and redistributes predictable tasks to appropriate staff.','The unstable client receives immediate assessment and escalation while routine care continues safely through appropriate delegation.'),
('Safety & Infection Control','Clostridioides difficile Precautions','Safety and Infection Prevention and Control','A hospitalized client has frequent watery diarrhea and a positive test for toxigenic Clostridioides difficile.','Confirmed C. difficile diarrhea requires contact precautions and environmental measures effective against spores.','C. difficile infection with transmission risk','Use contact precautions, gloves and gown, soap-and-water hand hygiene when indicated, dedicated equipment, and sporicidal environmental cleaning.','Initiate contact precautions and spore-focused infection-control measures immediately.','Transmission risk is reduced and precautions remain correctly applied throughout infectious diarrhea.'),
('NGN Clinical Judgment','Sepsis Recognition','Physiological Adaptation','An older adult with pneumonia becomes confused, respiratory rate 30/min, heart rate 118/min, blood pressure 86/50 mm Hg, and urine output falls sharply.','Infection with acute mental-status change, hypotension, tachypnea, tachycardia, and oliguria indicates organ dysfunction and sepsis with shock risk.','Sepsis with impaired tissue perfusion','Activate sepsis management, obtain indicated cultures and lactate without delaying treatment, administer prescribed antimicrobials and fluids, and reassess perfusion.','Escalate immediately and initiate the sepsis treatment pathway.','Blood pressure, mentation, urine output, and lactate trend improve with timely treatment.'),
('NGN Clinical Judgment','Hyperkalemia ECG Deterioration','Physiological Adaptation','A client with renal failure has potassium 7.1 mEq/L and develops widening QRS complexes after earlier peaked T waves.','Severe hyperkalemia with progressive ECG changes signals imminent malignant dysrhythmia.','Life-threatening hyperkalemia with cardiac conduction instability','Maintain continuous cardiac monitoring, activate emergency treatment, and administer prescribed membrane-stabilizing and potassium-shifting/removal therapies.','Treat the ECG changes immediately as a life-threatening electrolyte emergency.','QRS duration and rhythm normalize and potassium decreases toward a safe range without cardiac arrest.')
) as x(category,topic,client_need,cues,analysis,hypothesis,solution,action,outcome)
loop
 role:=case when idx%2=0 then 'rn' else 'pn' end;
 for j in 1..6 loop
  idx:=idx+1; cj:=(array['Recognize Cues','Analyze Cues','Prioritize Hypotheses','Generate Solutions','Take Action','Evaluate Outcomes'])[j]; pos:=((idx-1)%4)+1;
  qslug:=format('0054-%s-%s-%s',role,regexp_replace(lower(s.topic),'[^a-z0-9]+','-','g'),j);
  if cj='Recognize Cues' then stem:=s.cues||' Which finding should the '||upper(role)||' recognize as most important to the immediate clinical picture?'; correct_text:=s.analysis; wrong1:='A stable baseline characteristic is more important than the new change in condition.'; wrong2:='The client''s long-term teaching needs are the most time-sensitive finding.'; wrong3:='The abnormal findings should be considered routine until the next scheduled assessment.'; rc:=s.analysis||' Recognition requires identifying the cue with the strongest connection to immediate physiologic or safety risk.';
  elsif cj='Analyze Cues' then stem:=s.cues||' Which interpretation best explains the combined findings?'; correct_text:=s.analysis; wrong1:='The findings are expected and do not form a clinically meaningful pattern.'; wrong2:='The findings are best explained by anxiety alone despite the objective abnormalities.'; wrong3:='The findings cannot be interpreted until all routine diagnostic studies are complete.'; rc:=s.analysis||' The clustered subjective and objective cues support this interpretation more strongly than benign or delayed explanations.';
  elsif cj='Prioritize Hypotheses' then stem:=s.cues||' Which problem should the '||upper(role)||' treat as the priority hypothesis?'; correct_text:=s.hypothesis; wrong1:='A chronic problem that does not account for the acute cue cluster.'; wrong2:='A knowledge deficit despite evidence of a current physiologic or safety threat.'; wrong3:='A minor comfort problem that would not explain the objective deterioration.'; rc:='The priority hypothesis is '||s.hypothesis||' because it best explains the acute cues and carries the greatest immediate risk.';
  elsif cj='Generate Solutions' then stem:=s.cues||' Which plan is most appropriate for the priority problem?'; correct_text:=s.solution; wrong1:='Reassess at the next routine interval before changing the current plan of care.'; wrong2:='Complete nonurgent teaching first, then address the acute findings if they persist.'; wrong3:='Use comfort measures alone without focused monitoring or escalation.'; rc:=s.solution||' The plan addresses the suspected cause, immediate safety, monitoring, and timely escalation rather than delaying definitive care.';
  elsif cj='Take Action' then stem:=s.cues||' Which action should the '||upper(role)||' take first?'; correct_text:=s.action; wrong1:='Document the findings completely before initiating an intervention.'; wrong2:='Leave the client to finish another stable client''s routine care before responding.'; wrong3:='Wait for the next scheduled set of vital signs before escalating the change.'; rc:=s.action||' The first action addresses the immediate threat before routine documentation, stable-client tasks, or delayed reassessment.';
  else stem:=s.cues||' After treatment is initiated, which finding best demonstrates that the priority problem is improving?'; correct_text:=s.outcome; wrong1:='The charting is complete although the original abnormal findings remain unchanged.'; wrong2:='The client verbalizes teaching while the acute physiologic problem persists.'; wrong3:='No reassessment is performed because the planned intervention has already been started.'; rc:=s.outcome||' Effective evaluation compares the post-intervention state with measurable physiologic and safety goals.'; end if;
  qid:=md5('npq-0054-'||qslug)::uuid; qvid:=md5('npq-0054-v-'||qslug)::uuid;
  insert into public.questions(id,slug,lifecycle_status,current_version) values(qid,qslug,'pilot',1) on conflict on constraint questions_slug_key do update set updated_at=now() returning id into qid;
  insert into public.question_versions(id,question_id,version,stem,item_type,exam_tracks,subject,topic,client_need,clinical_judgment_step,difficulty,rationale_correct,rationale_distractors,memory_rule,source_note,validation_status,professional_role_focus,track_rationale)
  values(qvid,qid,1,stem,'single_best_answer',array[role],s.category,s.topic,s.client_need,cj,case when idx%3=1 then 'medium' else 'hard' end,rc,'The distractors represent common but unsafe reasoning errors: downgrading an acute cue, substituting a nearby concern, delaying escalation, or evaluating process rather than patient response.','Match the response to the NCJMM function and prioritize acute physiologic or safety threats over routine care.','Original NursePrepIQ pilot item aligned to the 2026 NCLEX RN/PN Client Needs and NCJMM framework; AI/editorial review required before any promotion. Not an NCSBN item.','pilot',case when role='rn' then 'RN comprehensive assessment, prioritization, intervention, coordination, teaching, and evaluation.' else 'PN focused data collection, implementation of established care, monitoring, reinforcement, and prompt escalation.' end,case when role='rn' then 'RN framing emphasizes comprehensive assessment and nursing judgment within entry-level RN scope.' else 'PN framing emphasizes focused monitoring, safe implementation, and timely escalation within entry-level PN scope.' end)
  on conflict(question_id,version) do update set stem=excluded.stem,validation_status='pilot' returning id into qvid;
  delete from public.question_options where question_version_id=qvid;
  if pos=1 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',correct_text,true,rc,1),(qvid,'b',wrong1,false,'This response underweights the acute cue cluster.',2),(qvid,'c',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',3),(qvid,'d',wrong3,false,'This delays or incompletely addresses the priority threat.',4);
  elsif pos=2 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',wrong1,false,'This response underweights the acute cue cluster.',1),(qvid,'b',correct_text,true,rc,2),(qvid,'c',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',3),(qvid,'d',wrong3,false,'This delays or incompletely addresses the priority threat.',4);
  elsif pos=3 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',wrong1,false,'This response underweights the acute cue cluster.',1),(qvid,'b',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',2),(qvid,'c',correct_text,true,rc,3),(qvid,'d',wrong3,false,'This delays or incompletely addresses the priority threat.',4);
  else insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',wrong1,false,'This response underweights the acute cue cluster.',1),(qvid,'b',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',2),(qvid,'c',wrong3,false,'This delays or incompletely addresses the priority threat.',3),(qvid,'d',correct_text,true,rc,4); end if;
 end loop;
end loop;
if idx<>108 then raise exception '0054 expected 108 questions, generated %',idx; end if;
end $$;
commit;
-- Expected structural distribution: 108 pilot; 54 RN/54 PN; 18 per NCJMM function; A/B/C/D=27 each; 72 hard/36 medium.
-- Category distribution: 12 each Fundamentals, Adult Health, Pharmacology, Mental Health, Maternal & Newborn, Pediatrics, Management of Care, Safety & Infection Control, NGN Clinical Judgment.