-- NursePrepIQ 0056: PN catch-up: 108 PN-only pilot questions to correct RN/PN production-bank imbalance
-- 18 clinical scenarios x all six NCJMM functions, reframed for PN scope. PN ONLY. Every website category represented.
-- SAFETY: PILOT/UNVALIDATED ONLY. No human/psychometric validation claimed. No auto-publication.
begin;
do $$
declare s record; j int; idx int:=0; role text; cj text; qslug text; qid uuid; qvid uuid; stem text; correct_text text; wrong1 text; wrong2 text; wrong3 text; rc text; pos int;
begin
for s in select * from (values
('Adult Health','Acute Pulmonary Edema','Physiological Adaptation','A client with heart failure suddenly develops severe dyspnea, diffuse crackles, pink frothy sputum, oxygen saturation 82%, and marked anxiety.','Abrupt hypoxemia, diffuse crackles, and pink frothy sputum indicate acute pulmonary edema with impaired gas exchange.','Acute cardiogenic pulmonary edema','Position upright, support oxygenation and ventilation, obtain rapid focused assessment, and administer prescribed acute heart-failure therapy while escalating care.','Place the client upright and immediately support oxygenation while activating urgent treatment.','Oxygenation and work of breathing improve and pulmonary congestion decreases without respiratory arrest.'),
('Adult Health','Pericardial Tamponade','Physiological Adaptation','After cardiac surgery, a client develops hypotension, jugular venous distention, muffled heart sounds, narrowing pulse pressure, and increasing restlessness.','Hypotension with venous distention and muffled heart sounds after cardiac surgery suggests tamponade with impaired cardiac filling.','Cardiac tamponade causing obstructive shock','Activate emergency cardiovascular evaluation, support circulation, monitor closely, and prepare for urgent pericardial decompression.','Treat the findings as cardiac tamponade and obtain immediate emergency intervention.','Blood pressure and perfusion improve after pressure on the heart is relieved.'),
('Adult Health','Acute Pancreatitis Deterioration','Physiological Adaptation','A client with acute pancreatitis develops increasing abdominal pain, heart rate 126/min, blood pressure 86/50 mm Hg, cool skin, and decreasing urine output.','Tachycardia, hypotension, cool skin, and oliguria indicate worsening intravascular depletion and impaired perfusion.','Acute pancreatitis complicated by circulatory instability','Prioritize circulation, maintain prescribed IV fluid resuscitation, monitor urine output and laboratory trends, and escalate for worsening shock.','Respond to the hypotension and oliguria as signs of impaired perfusion and escalate treatment immediately.','Blood pressure, urine output, and peripheral perfusion improve without progressive organ dysfunction.'),
('Adult Health','Neutropenic Fever','Reduction of Risk Potential','A client receiving chemotherapy has an absolute neutrophil count of 300 cells/mm3 and an oral temperature of 38.4 C with chills.','Fever in profound neutropenia is a time-sensitive infection emergency even when localizing symptoms are absent.','Febrile neutropenia with sepsis risk','Initiate neutropenic precautions, obtain prescribed cultures promptly, and expedite broad-spectrum antimicrobial treatment without avoidable delay.','Treat the fever as an oncologic emergency and initiate the febrile-neutropenia pathway immediately.','Antimicrobial therapy begins promptly and the client remains hemodynamically stable without progression to sepsis.'),
('Fundamentals','Dysphagia Aspiration Prevention','Basic Care and Comfort','A client after stroke coughs with thin liquids, has a wet voice after swallowing, and pockets food in one cheek.','Coughing, wet voice, and food pocketing are aspiration-risk cues requiring modification of oral intake and swallowing evaluation.','Impaired swallowing with aspiration risk','Stop unsafe oral intake, position upright, provide oral care, and follow prescribed swallowing evaluation and texture recommendations.','Withhold further unsafe intake and maintain upright positioning while obtaining swallowing guidance.','The client eats and drinks using the prescribed strategy without coughing, wet voice, or oxygen desaturation.'),
('Fundamentals','Fall Risk Orthostatic Hypotension','Safety and Infection Prevention and Control','An older adult becomes dizzy when standing; blood pressure falls from 134/76 supine to 98/58 standing after a new antihypertensive was started.','A symptomatic positional blood-pressure drop indicates orthostatic hypotension and immediate fall risk.','Orthostatic hypotension with fall risk','Return the client to a safe position, reassess symptoms and vital signs, institute fall precautions, and review contributing medications and hydration.','Assist the client back to sitting or lying and prevent unassisted ambulation.','The client changes position without dizziness or falls and blood pressure remains adequate for safe mobility.'),
('Pharmacology','Opioid Respiratory Depression','Pharmacological and Parenteral Therapies','Thirty minutes after IV morphine, a postoperative client is difficult to arouse, respiratory rate is 7/min, and oxygen saturation is 84%.','Marked sedation, bradypnea, and hypoxemia shortly after opioid administration indicate opioid-induced respiratory depression.','Opioid-induced respiratory depression','Stop further opioid administration, stimulate and support airway and ventilation, call for help, and administer prescribed naloxone while monitoring for recurrence.','Prioritize ventilation and administer opioid reversal as authorized rather than waiting for the medication to wear off.','Respiratory rate, oxygenation, and level of consciousness improve without recurrent respiratory depression.'),
('Pharmacology','Insulin Hypoglycemia','Pharmacological and Parenteral Therapies','A conscious client who received rapid-acting insulin becomes shaky, diaphoretic, confused, and has a bedside glucose of 48 mg/dL.','Adrenergic and neuroglycopenic symptoms with glucose 48 mg/dL confirm clinically significant hypoglycemia.','Acute symptomatic hypoglycemia','If swallowing is safe, provide rapid-acting carbohydrate, recheck glucose per protocol, repeat treatment if needed, and follow with longer-acting nutrition when appropriate.','Give rapid-acting carbohydrate immediately and reassess glucose rather than delaying for the next meal tray.','Glucose rises above the treatment threshold and shakiness, diaphoresis, and confusion resolve.'),
('Mental Health','Suicide Risk With Plan','Psychosocial Integrity','A depressed client says, “I bought a gun yesterday and plan to use it tonight when my family leaves.”','A specific plan, access to a lethal means, stated timing, and intent indicate imminent suicide risk.','Imminent risk for suicide','Maintain continuous safety observation, remove access to hazards, initiate emergency suicide precautions, and arrange immediate psychiatric intervention.','Do not leave the client alone; initiate the highest appropriate safety precautions and emergency evaluation.','The client remains safe, access to lethal means is addressed, and a secure treatment disposition is established.'),
('Mental Health','Lithium Dehydration Teaching','Pharmacological and Parenteral Therapies','A client taking lithium develops vomiting and diarrhea from gastroenteritis and asks whether to continue the usual dose despite being unable to keep fluids down.','Acute fluid and sodium losses can raise lithium concentration and increase toxicity risk.','Risk for lithium toxicity during dehydration','Hold further dosing until prompt prescriber guidance is obtained, encourage appropriate hydration as tolerated, and assess for toxicity symptoms and lithium level as indicated.','Contact the prescriber promptly before taking more lithium because dehydration can increase toxicity risk.','The client avoids toxicity, hydration is restored, and lithium management is safely adjusted based on clinical evaluation.'),
('Maternal & Newborn','Postpartum Hemorrhage Uterine Atony','Physiological Adaptation','One hour after vaginal birth, a client saturates a pad in 15 minutes; the uterus is boggy and displaced above the umbilicus.','Heavy bleeding with a boggy enlarged uterus strongly suggests uterine atony, with bladder distention potentially contributing.','Postpartum hemorrhage from uterine atony','Begin fundal massage, assess bladder status, quantify blood loss, summon assistance, and administer prescribed uterotonic and resuscitative treatment.','Perform fundal massage immediately while activating the postpartum-hemorrhage response.','The uterus becomes firm and midline, bleeding decreases, and maternal hemodynamics remain stable.'),
('Maternal & Newborn','Severe Preeclampsia Warning','Reduction of Risk Potential','A pregnant client at 35 weeks has blood pressure 168/112 mm Hg, persistent severe headache, visual spots, and right-upper-quadrant pain.','Severe hypertension with neurologic and hepatic warning symptoms indicates preeclampsia with severe features and seizure or stroke risk.','Preeclampsia with severe features','Institute seizure precautions, perform urgent maternal-fetal assessment, notify the obstetric team, and administer prescribed antihypertensive and seizure-prophylaxis therapy.','Treat the severe blood pressure and warning symptoms as an obstetric emergency.','Blood pressure moves below the severe range and neurologic symptoms improve without seizure or maternal-fetal deterioration.'),
('Pediatrics','Croup At Rest','Physiological Adaptation','A preschool child with a barking cough has inspiratory stridor at rest, suprasternal retractions, and increasing agitation.','Stridor at rest and retractions indicate significant upper-airway obstruction; agitation can worsen airflow limitation.','Moderate-to-severe croup with threatened airway','Keep the child calm, minimize distress, support oxygenation, and administer prescribed corticosteroid and nebulized epinephrine when indicated.','Keep the child with the caregiver in a position of comfort and obtain urgent respiratory treatment.','Stridor at rest and retractions diminish and oxygenation remains adequate without exhaustion.'),
('Pediatrics','Kawasaki Disease Coronary Risk','Reduction of Risk Potential','A child has five days of fever, bilateral nonpurulent conjunctivitis, strawberry tongue, cervical lymphadenopathy, rash, and swollen hands.','Prolonged fever with characteristic mucocutaneous findings suggests Kawasaki disease, which carries coronary-artery complication risk.','Kawasaki disease with coronary artery risk','Notify the pediatric team, support hydration and comfort, and prepare prescribed IV immunoglobulin and anti-inflammatory treatment with cardiac follow-up.','Escalate for prompt Kawasaki treatment rather than managing the prolonged fever as a routine viral illness.','Fever and inflammation resolve and cardiac monitoring shows no new coronary complications.'),
('Management of Care','RN Assignment Unstable Transfusion','Management of Care','A PN/VN caring for a client receiving blood develops an urgent concern when the client reports chills, flank pain, and dyspnea 15 minutes after the transfusion began.','Acute symptoms shortly after transfusion suggest a serious reaction requiring immediate action within PN/VN scope and rapid RN/provider escalation.','Acute transfusion reaction requiring immediate PN/VN action and escalation','Stop the transfusion per protocol, remain with the client, obtain focused findings, maintain appropriate IV access, and immediately notify the RN/provider while activating the reaction protocol.','Stop the transfusion per protocol and immediately escalate the suspected reaction while supporting the client.','The transfusion remains stopped, escalation occurs promptly, and the client receives timely evaluation and treatment without hemodynamic deterioration.'),
('Safety & Infection Control','Needlestick Occupational Exposure','Safety and Infection Prevention and Control','A nurse sustains a hollow-bore needlestick immediately after drawing blood from a client whose bloodborne-pathogen status is unknown.','A fresh hollow-bore needlestick is a significant occupational blood exposure requiring immediate first aid and time-sensitive evaluation.','Occupational bloodborne pathogen exposure','Wash the site, report the exposure immediately, obtain prompt source and exposed-worker evaluation per policy, and initiate indicated prophylaxis without delay.','Wash the puncture site and begin the occupational-exposure protocol immediately.','The exposure is documented and evaluated promptly and indicated prophylaxis and follow-up testing occur within recommended windows.'),
('NGN Clinical Judgment','Pulmonary Embolism Deterioration','Physiological Adaptation','Two days after hip surgery, a client suddenly develops pleuritic chest pain, dyspnea, heart rate 128/min, oxygen saturation 84%, and increasing anxiety.','Sudden hypoxemia, tachycardia, dyspnea, and pleuritic pain after major surgery suggest acute pulmonary embolism.','Acute pulmonary embolism with impaired oxygenation','Support oxygenation, limit exertion, activate urgent evaluation, and prepare prescribed anticoagulation or advanced treatment based on hemodynamic status.','Treat the sudden respiratory deterioration as a pulmonary embolism emergency and escalate immediately.','Oxygenation and hemodynamics stabilize without progression to obstructive shock.'),
('NGN Clinical Judgment','Acute Ischemic Limb After Catheterization','Reduction of Risk Potential','After femoral arterial catheterization, a client reports severe leg pain; the affected foot is pale, cool, numb, and has no palpable pedal pulse.','New pain, pallor, coolness, numbness, and pulse loss after arterial access indicate acute limb ischemia.','Acute arterial occlusion threatening limb perfusion','Perform urgent neurovascular assessment, notify the interventional or vascular team immediately, and prepare for rapid restoration of perfusion.','Treat the absent pulse and neurologic symptoms as a limb-threatening emergency.','Distal perfusion, warmth, sensation, and pulse or Doppler flow return after timely treatment.')
) as x(category,topic,client_need,cues,analysis,hypothesis,solution,action,outcome)
loop
 role:='pn';
 for j in 1..6 loop
  idx:=idx+1; cj:=(array['Recognize Cues','Analyze Cues','Prioritize Hypotheses','Generate Solutions','Take Action','Evaluate Outcomes'])[j]; pos:=((idx-1)%4)+1;
  qslug:=format('0056-%s-%s-%s',role,regexp_replace(lower(s.topic),'[^a-z0-9]+','-','g'),j);
  if cj='Recognize Cues' then stem:=s.cues||' Which finding should the '||upper(role)||' recognize as most important to the immediate clinical picture?'; correct_text:=s.analysis; wrong1:='A stable baseline characteristic is more important than the new change in condition.'; wrong2:='The client''s long-term teaching needs are the most time-sensitive finding.'; wrong3:='The abnormal findings should be considered routine until the next scheduled assessment.'; rc:=s.analysis||' Recognition requires identifying the cue with the strongest connection to immediate physiologic or safety risk.';
  elsif cj='Analyze Cues' then stem:=s.cues||' Which interpretation best explains the combined findings?'; correct_text:=s.analysis; wrong1:='The findings are expected and do not form a clinically meaningful pattern.'; wrong2:='The findings are best explained by anxiety alone despite the objective abnormalities.'; wrong3:='The findings cannot be interpreted until all routine diagnostic studies are complete.'; rc:=s.analysis||' The clustered subjective and objective cues support this interpretation more strongly than benign or delayed explanations.';
  elsif cj='Prioritize Hypotheses' then stem:=s.cues||' Which problem should the '||upper(role)||' treat as the priority hypothesis?'; correct_text:=s.hypothesis; wrong1:='A chronic problem that does not account for the acute cue cluster.'; wrong2:='A knowledge deficit despite evidence of a current physiologic or safety threat.'; wrong3:='A minor comfort problem that would not explain the objective deterioration.'; rc:='The priority hypothesis is '||s.hypothesis||' because it best explains the acute cues and carries the greatest immediate risk.';
  elsif cj='Generate Solutions' then stem:=s.cues||' Which plan is most appropriate for the priority problem?'; correct_text:=s.solution; wrong1:='Reassess at the next routine interval before changing the current plan of care.'; wrong2:='Complete nonurgent teaching first, then address the acute findings if they persist.'; wrong3:='Use comfort measures alone without focused monitoring or escalation.'; rc:=s.solution||' The plan addresses the suspected cause, immediate safety, monitoring, and timely escalation rather than delaying definitive care.';
  elsif cj='Take Action' then stem:=s.cues||' Which action should the '||upper(role)||' take first?'; correct_text:=s.action; wrong1:='Document the findings completely before initiating an intervention.'; wrong2:='Leave the client to finish another stable client''s routine care before responding.'; wrong3:='Wait for the next scheduled set of vital signs before escalating the change.'; rc:=s.action||' The first action addresses the immediate threat before routine documentation, stable-client tasks, or delayed reassessment.';
  else stem:=s.cues||' After treatment is initiated, which finding best demonstrates that the priority problem is improving?'; correct_text:=s.outcome; wrong1:='The charting is complete although the original abnormal findings remain unchanged.'; wrong2:='The client verbalizes teaching while the acute physiologic problem persists.'; wrong3:='No reassessment is performed because the planned intervention has already been started.'; rc:=s.outcome||' Effective evaluation compares the post-intervention state with measurable physiologic and safety goals.'; end if;
  qid:=md5('npq-0056-'||qslug)::uuid; qvid:=md5('npq-0056-v-'||qslug)::uuid;
  insert into public.questions(id,slug,lifecycle_status,current_version) values(qid,qslug,'pilot',1) on conflict on constraint questions_slug_key do update set updated_at=now() returning id into qid;
  insert into public.question_versions(id,question_id,version,stem,item_type,exam_tracks,subject,topic,client_need,clinical_judgment_step,difficulty,rationale_correct,rationale_distractors,memory_rule,source_note,validation_status,professional_role_focus,track_rationale)
  values(qvid,qid,1,stem,'single_best_answer',array[role],s.category,s.topic,s.client_need,cj,case when idx%3=1 then 'medium' else 'hard' end,rc,'The distractors represent common but unsafe reasoning errors: downgrading an acute cue, substituting a nearby concern, delaying escalation, or evaluating process rather than patient response.','Match the response to the NCJMM function and prioritize acute physiologic or safety threats over routine care.','Original NursePrepIQ pilot item aligned to the 2026 NCLEX RN/PN Client Needs and NCJMM framework; AI/editorial review required before any promotion. Not an NCSBN item.','pilot',case when role='rn' then 'RN comprehensive assessment, prioritization, intervention, coordination, teaching, and evaluation.' else 'PN focused data collection, implementation of established care, monitoring, reinforcement, and prompt escalation.' end,case when role='rn' then 'RN framing emphasizes comprehensive assessment and nursing judgment within entry-level RN scope.' else 'PN framing emphasizes focused monitoring, safe implementation, and timely escalation within entry-level PN scope.' end)
  on conflict(question_id,version) do update set stem=excluded.stem,validation_status='pilot' returning id into qvid;
  delete from public.question_options where question_version_id=qvid;
  if pos=1 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',correct_text,true,rc,1),(qvid,'b',wrong1,false,'This response underweights the acute cue cluster.',2),(qvid,'c',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',3),(qvid,'d',wrong3,false,'This delays or incompletely addresses the priority threat.',4);
  elsif pos=2 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',wrong1,false,'This response underweights the acute cue cluster.',1),(qvid,'b',correct_text,true,rc,2),(qvid,'c',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',3),(qvid,'d',wrong3,false,'This delays or incompletely addresses the priority threat.',4);
  elsif pos=3 then insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',wrong1,false,'This response underweights the acute cue cluster.',1),(qvid,'b',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',2),(qvid,'c',correct_text,true,rc,3),(qvid,'d',wrong3,false,'This delays or incompletely addresses the priority threat.',4);
  else insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,'a',wrong1,false,'This response underweights the acute cue cluster.',1),(qvid,'b',wrong2,false,'This is a plausible nearby concern but not the immediate priority.',2),(qvid,'c',wrong3,false,'This delays or incompletely addresses the priority threat.',3),(qvid,'d',correct_text,true,rc,4); end if;
 end loop;
end loop;
if idx<>108 then raise exception '0056 expected 108 questions, generated %',idx; end if;
end $$;
commit;
-- Expected structural distribution: 108 pilot; 54 RN/54 PN; 18 per NCJMM function; A/B/C/D=27 each; 72 hard/36 medium.
-- Category distribution: 12 each Fundamentals, Adult Health, Pharmacology, Mental Health, Maternal & Newborn, Pediatrics, Management of Care, Safety & Infection Control, NGN Clinical Judgment.