-- NursePrepIQ 0063: 24 original GI replacement items calibrated to 2026 NCSBN item-writing guidance.
-- Original NursePrepIQ content; public professional banks were used only to calibrate breadth/style. PILOT ONLY.
begin;
do $$
declare r record; qid uuid; qvid uuid; k text; rr text;
begin
for r in select * from (values
('rn','gerd-teaching','Adult Health','GERD','Health Promotion and Maintenance','Patient Teaching','medium','A client with gastroesophageal reflux disease is reviewing lifestyle changes. Which statement indicates that the teaching has been effective?','I will lie down for 30 minutes after dinner.','I will eat my largest meal shortly before bedtime.','I will avoid meals for several hours before going to bed.','I will drink peppermint tea when heartburn begins.',3,'Avoiding food close to bedtime reduces reflux associated with recumbency.'),
('pn','ostomy-peristomal-skin','Fundamentals','Ileostomy Care','Basic Care and Comfort','Procedure / Skin Care','medium','The nurse is changing an ileostomy pouch. Which finding requires follow-up?','The stoma is moist and red.','The peristomal skin is denuded and weeping.','Liquid stool is present in the pouch.','The stoma protrudes slightly above skin level.',2,'Denuded, weeping peristomal skin indicates impaired skin integrity and usually signals leakage or an ill-fitting barrier.'),
('rn','cirrhosis-encephalopathy-lab','Adult Health','Cirrhosis','Reduction of Risk Potential','Laboratory Interpretation','hard','A client with cirrhosis becomes increasingly confused and develops asterixis. Which laboratory result is most consistent with this change?','Decreased serum ammonia','Increased serum ammonia','Increased serum albumin','Decreased prothrombin time',2,'Confusion and asterixis in cirrhosis are consistent with hepatic encephalopathy, which is commonly associated with impaired ammonia clearance.'),
('pn','hepatitis-a-teaching','Adult Health','Hepatitis A','Safety and Infection Prevention and Control','Infection Prevention','medium','A client with hepatitis A asks how to reduce transmission to family members. Which instruction should the nurse reinforce?','Use a separate bedroom until jaundice resolves.','Wear a mask whenever another person enters the room.','Wash hands thoroughly after toileting and before handling food.','Avoid sharing drinking glasses because saliva is the primary route of spread.',3,'Hepatitis A is transmitted primarily by the fecal-oral route, making meticulous hand hygiene especially important.'),
('rn','crohns-vs-uc','Adult Health','Inflammatory Bowel Disease','Physiological Adaptation','Condition Differentiation','hard','Which finding in a client with inflammatory bowel disease is more characteristic of Crohn disease than ulcerative colitis?','Continuous inflammation beginning in the rectum','Disease limited to the mucosal layer of the colon','Transmural inflammation with skip lesions','Frequent bloody diarrhea as the defining pattern',3,'Crohn disease can involve any part of the gastrointestinal tract and characteristically produces transmural inflammation with skip lesions.'),
('pn','upper-endoscopy-prep','Fundamentals','Upper Endoscopy','Reduction of Risk Potential','Procedure Preparation','medium','A client is scheduled for an upper endoscopy with sedation. Which preprocedure action should the nurse verify?','The client ate a light breakfast 2 hours ago.','The client has maintained the prescribed fasting period.','The client received a cleansing enema.','The client drank oral contrast immediately before transport.',2,'Fasting before upper endoscopy reduces aspiration risk and allows safer visualization and sedation.'),
('rn','bowel-obstruction-pattern','Adult Health','Small Bowel Obstruction','Physiological Adaptation','Cue Interpretation','hard','A client has cramping abdominal pain, vomiting, abdominal distention, and high-pitched bowel sounds. Which interpretation best fits this cluster of findings?','Paralytic ileus with absent intestinal activity','Mechanical intestinal obstruction','Uncomplicated gastroesophageal reflux','Acute hepatitis with impaired bile flow',2,'Cramping pain, vomiting, distention, and high-pitched bowel sounds form a classic pattern of mechanical intestinal obstruction.'),
('pn','lactulose-evaluation','Pharmacology','Hepatic Encephalopathy','Pharmacological Therapies','Treatment Evaluation','medium','A client with cirrhosis and hepatic encephalopathy receives lactulose. Which finding best indicates that the medication is having the intended effect?','The client has two to three soft stools daily and improved mentation.','The client has no bowel movements for 48 hours.','The client develops increasing abdominal distention and confusion.','The client reports dark urine but unchanged cognition.',1,'Lactulose promotes ammonia elimination; improved mentation with regular soft stools supports the intended therapeutic response.'),
('rn','pancreatitis-nutrition','Adult Health','Acute Pancreatitis','Basic Care and Comfort','Nutrition Management','medium','A client recovering from acute pancreatitis is ready to resume oral intake. Which meal selection is most appropriate?','Fried chicken, macaroni and cheese, and whole milk','Baked fish, rice, cooked carrots, and water','Sausage, biscuits with gravy, and coffee','Cheeseburger, french fries, and a milkshake',2,'A lower-fat meal is generally better tolerated during recovery and reduces pancreatic stimulation compared with high-fat choices.'),
('pn','appendectomy-unexpected','Adult Health','Appendectomy','Reduction of Risk Potential','Expected vs Unexpected','medium','Twelve hours after an appendectomy, which finding should the nurse report?','Mild incisional discomfort with movement','Temperature of 37.4 C (99.3 F)','Increasing abdominal rigidity and worsening pain','Decreased appetite after anesthesia',3,'Increasing rigidity and worsening abdominal pain are not expected recovery findings and can signal peritoneal irritation or another postoperative complication.'),
('rn','gi-bleed-bun','Adult Health','Upper GI Bleeding','Reduction of Risk Potential','Laboratory Interpretation','hard','A client is being evaluated for an upper gastrointestinal bleed. Which laboratory pattern can support this suspicion when interpreted with the clinical findings?','A disproportionately elevated BUN relative to creatinine','A markedly decreased serum lipase','An isolated increase in serum calcium','A decreased hemoglobin A1c',1,'Digestion and absorption of blood proteins plus volume depletion can raise BUN disproportionately in upper GI bleeding.'),
('pn','colonoscopy-aftercare','Fundamentals','Colonoscopy','Reduction of Risk Potential','Post-Procedure Care','medium','A client returns after colonoscopy with polypectomy. Which finding should the nurse report promptly?','Passing a small amount of flatus','Mild transient abdominal bloating','Severe abdominal pain with a rigid abdomen','Sleepiness that gradually decreases after sedation',3,'Severe pain with rigidity can indicate perforation and requires prompt evaluation.'),
('rn','tpn-monitoring','Pharmacology','Parenteral Nutrition','Pharmacological and Parenteral Therapies','Monitoring','hard','A client is receiving total parenteral nutrition through a central venous catheter. Which assessment is most important for evaluating a common metabolic complication of this therapy?','Capillary blood glucose','Pupillary response','Deep tendon reflexes','Visual acuity',1,'Parenteral nutrition contains a high glucose load, so blood glucose monitoring is important for detecting hyperglycemia.'),
('pn','celiac-food','Adult Health','Celiac Disease','Health Promotion and Maintenance','Diet Selection','medium','Which lunch selection by a client with celiac disease demonstrates understanding of the prescribed diet?','Turkey on whole-wheat bread with barley soup','Grilled chicken, rice, green beans, and fruit','Pasta salad with rye crackers','Breaded fish with couscous',2,'Rice, unbreaded poultry, vegetables, and fruit are naturally gluten-free choices; wheat, barley, and rye contain gluten.'),
('rn','portal-hypertension-complication','Adult Health','Portal Hypertension','Physiological Adaptation','Risk Recognition','hard','Which complication is most directly associated with portal hypertension in a client with cirrhosis?','Esophageal varices','Achalasia','Pyloric stenosis','Acute appendicitis',1,'Portal hypertension creates collateral venous circulation and can produce esophageal and gastric varices.'),
('pn','cholecystitis-food','Adult Health','Cholecystitis','Basic Care and Comfort','Diet Teaching','medium','Which food should a client with symptomatic gallbladder disease limit because it is most likely to trigger discomfort?','Baked potato','Applesauce','Fried chicken','Steamed rice',3,'High-fat foods stimulate gallbladder contraction and commonly worsen biliary pain.'),
('rn','dumping-syndrome','Adult Health','Postgastrectomy Dumping Syndrome','Physiological Adaptation','Condition Recognition','hard','A client who had gastric surgery reports cramping, palpitations, dizziness, and diarrhea shortly after meals. Which condition best explains these findings?','Dumping syndrome','Achalasia','Acute appendicitis','Paralytic ileus',1,'Rapid movement of hyperosmolar gastric contents into the small intestine after gastric surgery can cause the vasomotor and gastrointestinal findings of dumping syndrome.'),
('pn','ng-tube-decompression','Fundamentals','Nasogastric Decompression','Basic Care and Comfort','Equipment / Procedure','medium','A client with bowel obstruction has a nasogastric tube connected to low intermittent suction. Which finding best indicates that decompression is effective?','Increasing abdominal distention','Decreased nausea and abdominal distention','New absent urine output','Increasing high-pitched pain',2,'Effective gastric decompression should reduce retained gastrointestinal contents, nausea, vomiting, and distention.'),
('rn','ulcer-perforation','Adult Health','Peptic Ulcer Disease','Physiological Adaptation','Complication Recognition','hard','A client with peptic ulcer disease suddenly develops severe generalized abdominal pain and a board-like abdomen. Which complication should the nurse suspect?','Perforation','Dumping syndrome','Hemorrhoids','Lactose intolerance',1,'Sudden severe pain with a rigid, board-like abdomen suggests perforation with peritoneal irritation.'),
('pn','oral-rehydration-child','Pediatrics','Gastroenteritis Dehydration','Basic Care and Comfort','Fluid Teaching','medium','The parent of a child with mild gastroenteritis asks how to give oral rehydration solution. Which instruction should the nurse provide?','Offer small, frequent amounts and increase as tolerated.','Give only plain water until diarrhea stops.','Withhold all fluids for 4 hours after vomiting.','Replace each loose stool with a carbonated beverage.',1,'Small, frequent amounts of oral rehydration solution improve tolerance and replace water and electrolytes more appropriately than plain water or sugary beverages.'),
('rn','variceal-beta-blocker','Pharmacology','Esophageal Varices','Pharmacological and Parenteral Therapies','Medication Purpose','hard','A client with cirrhosis is prescribed a nonselective beta blocker for prevention of recurrent esophageal variceal bleeding. Which explanation best describes the purpose of this therapy?','It reduces portal pressure and the risk of variceal hemorrhage.','It dissolves existing esophageal varices.','It neutralizes gastric acid that causes varices.','It increases clotting-factor synthesis by the liver.',1,'Nonselective beta blockers reduce portal venous pressure and are used to lower the risk of variceal bleeding.'),
('pn','ileostomy-output','Fundamentals','Ileostomy Care','Reduction of Risk Potential','Fluid Risk Recognition','medium','Which finding in a client with a new ileostomy is most concerning for fluid-volume depletion?','Liquid ileostomy output with dizziness and decreased urine output','A pink moist stoma','Passage of flatus into the pouch','Mild awareness of the pouch during movement',1,'High or liquid ileostomy losses can cause substantial fluid and electrolyte loss; dizziness and decreased urine output support volume depletion.'),
('rn','ibd-biologic-infection','Pharmacology','Inflammatory Bowel Disease Biologic Therapy','Pharmacological and Parenteral Therapies','Medication Safety','hard','Before initiating a tumor necrosis factor inhibitor for inflammatory bowel disease, which history is especially important to investigate?','Previous tuberculosis infection or exposure','Seasonal allergic rhinitis','Remote ankle sprain','Corrected myopia',1,'TNF inhibitors suppress immune defenses and can reactivate latent tuberculosis, so TB screening and history are important before therapy.'),
('pn','gerd-med-timing','Pharmacology','GERD Medication','Pharmacological Therapies','Medication Administration','medium','A client is prescribed a proton pump inhibitor for gastroesophageal reflux disease. Which instruction should the nurse reinforce for many once-daily proton pump inhibitors?','Take the medication before the first meal of the day.','Take it only when severe pain occurs.','Crush delayed-release preparations into milk.','Take it with an antacid at exactly the same time.',1,'Many once-daily proton pump inhibitors work best when taken before the first meal so active proton pumps can be inhibited effectively.')
) as x(role,slug,subject,topic,client_need,skill,difficulty,stem,a,b,c,d,keypos,rationale)
loop
 qid:=md5('npq-0063-'||r.role||'-'||r.slug)::uuid; qvid:=md5('npq-0063-v-'||r.role||'-'||r.slug)::uuid;
 insert into public.questions(id,slug,lifecycle_status,current_version) values(qid,'0063-'||r.role||'-'||r.slug,'pilot',1)
 on conflict on constraint questions_slug_key do update set updated_at=now() returning id into qid;
 insert into public.question_versions(id,question_id,version,stem,item_type,exam_tracks,subject,topic,client_need,difficulty,rationale_correct,rationale_distractors,memory_rule,source_note,validation_status,professional_role_focus,track_rationale,body_system,discipline)
 values(qvid,qid,1,r.stem,'single_best_answer',array[r.role],r.subject,r.topic,r.client_need,r.difficulty,r.rationale,
 'Each distractor is clinically plausible in the broader GI domain but does not best answer the specific stem.',
 'Answer the clinical task actually asked: interpret, teach, monitor, evaluate, differentiate, or recognize risk rather than defaulting to priority-action reasoning.',
 'Original NursePrepIQ item calibrated to public 2026 NCSBN item-writing guidance and professional public GI practice-bank breadth. Not copied from or represented as an NCSBN or third-party item. AI/editorial review required before promotion.',
 'pilot',case when r.role='rn' then 'RN assessment, clinical judgment, teaching, coordination, medication management, and evaluation.' else 'PN focused data collection, implementation, reinforcement, monitoring, and escalation within PN scope.' end,
 case when r.role='rn' then 'Entry-level RN framing.' else 'Entry-level PN framing.' end,'Gastrointestinal',
 case when r.subject='Pharmacology' then 'Pharmacology' when r.subject='Fundamentals' then 'Fundamentals' when r.subject='Pediatrics' then 'Pediatrics' else 'Adult Health' end)
 on conflict(question_id,version) do update set stem=excluded.stem,validation_status='pilot' returning id into qvid;
 delete from public.question_options where question_version_id=qvid;
 insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order)
 select qvid,chr((96+n)::integer),opt,(n=r.keypos),case when n=r.keypos then r.rationale else 'This option does not best satisfy the clinical task and evidence in the stem.' end,n
 from unnest(array[r.a,r.b,r.c,r.d]) with ordinality z(opt,n);
end loop;
end $$;
commit;