begin;
create table if not exists public.anthropic_question_maintenance (
 id bigint generated by default as identity primary key,
 question_id uuid references public.questions(id) on delete set null,
 agent text not null check(agent in ('reviewer','generator')),
 model text not null,
 decision text not null,
 reason text,
 confidence numeric check(confidence is null or (confidence>=0 and confidence<=1)),
 raw_result jsonb,
 created_at timestamptz not null default now()
);
create index if not exists anthropic_question_maintenance_question_idx on public.anthropic_question_maintenance(question_id,created_at desc);
alter table public.anthropic_question_maintenance enable row level security;
commit;