-- NursePrepIQ 0069: import Set01 Cardiovascular 50 as reviewed PILOT content.
-- Source: user-provided NCLEX_Set01_Cardiovascular.pdf. Original practice items, not psychometrically pretested.
-- RN-19 and PN-25 are intentionally held for revised clinical wording/options before promotion.
begin;
do $$
declare r record; qid uuid; qvid uuid; opt text; n int; keyarr text[]; rat text; typ text; cfg jsonb;
begin
for r in select * from (values
('RN-1','rn','Management of Care','Prioritization','single_best_answer','The nurse on a cardiac step-down unit receives report on four clients. Which client should the nurse assess first?','A client with new-onset atrial fibrillation on a diltiazem infusion whose heart rate is 88/min|A client 4 hours after a percutaneous coronary intervention via the femoral artery who reports new back pain, with HR 112/min and BP 92/58 mm Hg|A client with chronic heart failure who is requesting acetaminophen for knee pain|A client with stable angina who is NPO for a stress test and is asking for a drink of water','B','New back or flank pain with tachycardia and hypotension after femoral-access PCI suggests life-threatening retroperitoneal bleeding.'),
('RN-2','rn','Pharmacology','Anticoagulants','single_best_answer','A client is receiving a continuous heparin infusion per weight-based protocol. The aPTT is 118 seconds (therapeutic range 60–85). What is the priority action?','Increase the infusion rate per protocol|Hold the infusion per protocol, assess for bleeding, and notify the provider|Administer protamine sulfate IV push|Continue the infusion and recheck the aPTT in 6 hours','B','A supratherapeutic aPTT increases bleeding risk; the protocol-directed response is to hold/reduce heparin, assess for bleeding, and escalate.'),
('RN-3','rn','Adult Health','Heart failure','multiple_response','Which findings support suspected left-sided heart failure? Select all that apply.','Crackles in the lung bases|Jugular venous distention|Orthopnea|Dependent pitting edema|Hepatomegaly|Dyspnea on exertion|S3 heart sound','A,C,F,G','Pulmonary congestion produces crackles, orthopnea and exertional dyspnea; an S3 commonly accompanies volume-overloaded systolic failure.'),
('RN-4','rn','Pharmacology','Nitrates','single_best_answer','A client with substernal chest pressure has an order for sublingual nitroglycerin 0.4 mg. Which information requires follow-up before administration?','The client took aspirin 325 mg 30 minutes ago|The client took sildenafil 10 hours ago|The blood pressure is 142/88 mm Hg|The client reports headache with previous nitroglycerin use','B','Recent sildenafil is a contraindication to nitrate administration because the combination can cause profound hypotension.'),
('RN-5','rn','Adult Health','Acute coronary syndrome','single_best_answer','A client arrives with crushing chest pain radiating to the left jaw that began 40 minutes ago. SpO2 is 96% on room air. Which action should the nurse take first?','Obtain a 12-lead ECG|Draw blood for troponin|Apply oxygen at 4 L/min|Complete a detailed health history','A','A 12-lead ECG should be obtained promptly to identify acute ischemia/STEMI; routine oxygen is not indicated with adequate saturation.'),
('RN-6','rn','Adult Health','Post-cardiac surgery','single_best_answer','Six hours after CABG, which finding requires immediate action?','Mediastinal chest tube drainage 90 mL in the past hour|Temperature 99.5 F (37.5 C)|Chest tube drainage abruptly decreased from 150 mL/hr to 10 mL/hr with BP 86/60 and new JVD|Incisional pain rated 6/10','C','Abruptly decreased drainage plus hypotension and JVD suggests obstructed drainage with cardiac tamponade, an emergency.'),
('RN-7','rn','Adult Health','Dysrhythmias','single_best_answer','The nurse finds a client unresponsive with no carotid pulse; the monitor shows ventricular fibrillation. Help and the code cart are called. What is next?','Administer epinephrine 1 mg IV|Begin high-quality chest compressions|Obtain a 12-lead ECG|Deliver two rescue breaths','B','Pulseless VF requires immediate high-quality CPR while defibrillation is prepared.'),
('RN-8','rn','Pharmacology','Antidysrhythmics','single_best_answer','Which statement by a client discharged on oral amiodarone indicates understanding?','I can stop it when my rhythm is normal|I will report a new dry cough or shortness of breath right away|I will drink grapefruit juice each morning|I do not need sunscreen','B','New cough or dyspnea may signal serious amiodarone pulmonary toxicity and warrants prompt evaluation.'),
('RN-9','rn','Pharmacology','Beta blockers','single_best_answer','Before metoprolol 50 mg PO, HR is 50/min, BP 96/58, and the client is lightheaded. What should the nurse do?','Administer and recheck in 1 hour|Administer half the dose|Hold the medication and notify the provider|Have the client lie down, then administer','C','Symptomatic bradycardia and hypotension are reasons to hold the beta blocker and notify the prescriber.'),
('RN-10','rn','Adult Health','Hypertension diet','single_best_answer','Which lunch selection best demonstrates DASH-diet understanding?','Deli turkey sandwich and dill pickle|Grilled chicken on mixed greens with oil/vinegar and fresh berries|Canned chicken noodle soup and saltines|Frozen macaroni and cheese and diet soda','B','DASH emphasizes fruits, vegetables and lean proteins while limiting sodium-rich processed foods.'),
('RN-11','rn','Pharmacology','Statins','single_best_answer','A client starting atorvastatin asks which adverse effect should be reported.','Unexplained muscle pain, tenderness, or weakness|Facial flushing|Dark green stools|Increased appetite','A','Unexplained muscle symptoms may indicate statin-associated myopathy or rhabdomyolysis and require evaluation.'),
('RN-12','rn','Adult Health','Peripheral arterial disease','multiple_response','Which lower-extremity findings are consistent with peripheral arterial disease? Select all that apply.','Thin shiny hairless skin|Diminished or absent pedal pulses|Brown ankle discoloration|Leg pain relieved by dangling the legs|Toe ulcer with a pale base|Moderate ankle edema','A,B,D,E','Arterial insufficiency causes trophic changes, weak pulses, dependency relief of ischemic rest pain, and distal pale ulcers.'),
('RN-13','rn','Adult Health','Deep vein thrombosis','single_best_answer','A client has a left-calf DVT and is receiving heparin. Which AP action requires intervention?','Apply prescribed warm moist pack|Massage the left calf for discomfort|Encourage fluids|Report bleeding gums during mouth care','B','Massaging an extremity with DVT is unsafe because clot dislodgement can cause pulmonary embolism.'),
('RN-14','rn','Adult Health','Abdominal aortic aneurysm','single_best_answer','A client with a 5.8-cm AAA suddenly develops severe tearing back pain, BP 84/50, HR 128. What is the priority action?','Palpate the abdomen|Give PRN oral analgesic|Activate emergency response and prepare for emergency surgery|Place prone','C','This presentation suggests ruptured AAA with shock and requires immediate emergency/surgical response.'),
('RN-15','rn','Adult Health','Infective endocarditis','single_best_answer','Which new finding in a client being treated for mitral-valve infective endocarditis requires immediate reporting?','Temperature 100.2 F|Fatigue after ambulation|Sudden left-sided weakness and slurred speech|Splinter hemorrhages','C','Sudden focal neurologic deficits may represent embolic stroke from left-sided endocarditis.'),
('RN-16','rn','Adult Health','Pacemakers','single_best_answer','Which statement after permanent pacemaker insertion indicates need for further teaching?','I will carry my pacemaker ID card|I will keep my cell phone in my shirt pocket over the pacemaker|I will avoid lifting the affected arm over my head until follow-up|I will tell airport security staff about my pacemaker','B','A cell phone should not be stored directly over the pacemaker generator.'),
('RN-17','rn','Adult Health','Hypertensive emergency','single_best_answer','A client has BP 228/134 with severe headache and blurred vision and receives nicardipine. Which first-hour goal is appropriate?','Reduce BP to 120/80 immediately|Reduce mean arterial pressure by no more than 25%|Maintain current BP until CT|Reduce systolic BP below 100','B','Controlled initial BP reduction avoids hypoperfusion; excessive rapid lowering can cause ischemia.'),
('RN-18','rn','Adult Health','Heart failure monitoring','highlight','Highlight the findings in this note that require follow-up.','Three-pillow orthopnea|Weight 84 kg, 82 kg yesterday|Fine bilateral basilar crackles|BP 132/82|Potassium 4.2|SpO2 91% room air|Eating most of breakfast','A,B,C,F','Orthopnea, rapid weight gain, crackles and reduced oxygen saturation indicate worsening congestion and require follow-up.'),
('RN-19','rn','Pharmacology','Angina','cloze_dropdown','A hospitalized client with stable angina has chest pain 6/10. Five minutes after one SL nitroglycerin 0.4 mg, pain is 5/10 and BP 126/78. Complete the priority sequence.','Obtain a 12-lead ECG and activate the facility chest-pain/ACS escalation pathway|Administer another prescribed SL nitroglycerin while continuing reassessment if no contraindication is present','A,B','Persistent ischemic chest pain after the first nitroglycerin dose requires prompt ACS evaluation/escalation; additional prescribed nitroglycerin may be given while reassessment continues.'),
('RN-20','rn','Adult Health','Heart failure case: Recognize cues','multiple_response','Which findings in the linked HFrEF case are consistent with worsening heart failure?','SpO2 88% room air|Temperature 98.4 F|Bilateral crackles to mid-scapula|Weight 3 kg above dry weight|BNP 1450 pg/mL|JVD at 45 degrees|Creatinine 1.1 mg/dL','A,C,D,E,F','Hypoxemia, crackles, rapid weight gain, markedly elevated BNP and JVD support decompensated heart failure.'),
('RN-21','rn','Adult Health','Heart failure case: Analyze cues','matrix_grid','Classify each linked-case finding as more consistent with left-sided or right-sided heart failure.','Crackles in bilateral lung fields|Jugular venous distention|+3 pitting ankle edema|Orthopnea|SpO2 88% room air','A','Pulmonary congestion and hypoxemia reflect left-sided failure; JVD and peripheral edema reflect systemic venous congestion/right-sided failure.'),
('RN-22','rn','Adult Health','Heart failure case: Prioritize hypotheses','cloze_dropdown','Complete the linked-case hypothesis and precipitating factor.','Acute decompensated heart failure|Diuretic nonadherence and high dietary sodium intake','A,B','The cue cluster supports acute decompensated HF precipitated by stopping the loop diuretic and high sodium intake.'),
('RN-23','rn','Adult Health','Heart failure case: Generate solutions','multiple_response','Which prescriptions should the nurse anticipate for the linked HFrEF case? Select all that apply.','Furosemide 40 mg IV|0.9% sodium chloride 1000 mL bolus|Oxygen titrated to maintain SpO2 at least 92%|Daily weights before breakfast|Potassium chloride supplement|Fluid restriction 1.5-2 L/day|Place supine','A,C,D,E,F','Treatment addresses congestion, hypoxemia, fluid monitoring and hypokalemia; a saline bolus and supine positioning would worsen the presentation.'),
('RN-24','rn','Adult Health','Heart failure case: Take action','single_best_answer','Which action should the nurse take first for the linked HFrEF case?','Administer prescribed IV furosemide|Place in high-Fowler position and apply oxygen|Reinforce 2-g sodium diet|Obtain standing weight','B','Immediate positioning and oxygen address severe hypoxemia and breathing before other interventions.'),
('RN-25','rn','Adult Health','Heart failure case: Evaluate outcomes','matrix_grid','Classify each 24-hour reassessment finding as effective or not effective treatment response.','SpO2 95% room air|Weight decreased 1.5 kg|Crackles only in lung bases|Potassium 3.1 mEq/L|HR 124 irregularly irregular|Urine output 1800 mL/8 hr','A','Improved oxygenation, weight, crackles and diuresis indicate response; worsening hypokalemia and uncontrolled ventricular rate require further intervention.'),
('PN-1','pn','Fundamentals','Scope of practice','single_best_answer','Which cardiac client is most appropriate for RN assignment to the LPN/VN?','Stable client 2 days after MI awaiting discharge|Client admitted 30 minutes ago with new chest pain|Client on titrated nitroglycerin infusion|New HF diagnosis needing initial teaching plan','A','Stable clients with predictable outcomes are generally appropriate for LPN/VN care; unstable assessment, titration and initial teaching require RN judgment.'),
('PN-2','pn','Fundamentals','Blood pressure measurement','single_best_answer','Using a standard adult BP cuff on a client with a large upper arm is expected to cause what effect?','Falsely low reading|Falsely high reading|Accurate reading|Widened pulse pressure only','B','A cuff that is too small requires excessive pressure to occlude the artery and can falsely elevate the reading.'),
('PN-3','pn','Fundamentals','Apical pulse','single_best_answer','Where should the LPN/VN place the stethoscope to count an adult apical pulse?','Second ICS right sternal border|Fifth ICS left midclavicular line|Third ICS left anterior axillary line|Fourth ICS right midclavicular line','B','The adult apical impulse is normally auscultated at the fifth intercostal space near the left midclavicular line.'),
('PN-4','pn','Pharmacology','Digoxin administration','single_best_answer','Before digoxin 0.125 mg PO, the apical pulse is 54/min for 1 minute. What should the LPN/VN do?','Administer and recheck|Withhold and report to RN/provider|Recount radial pulse and give if above 60|Give with full glass of water','B','Bradycardia is a reason to withhold digoxin and report according to the prescription/facility parameters.'),
('PN-5','pn','Pharmacology','Digoxin toxicity','multiple_response','Which findings may indicate digoxin toxicity? Select all that apply.','Nausea and loss of appetite|Yellow-green halos|Heart rate 48/min|New confusion|BP 162/96|Increased thirst','A,B,C,D','GI symptoms, visual disturbance, bradycardia/dysrhythmia and confusion are classic toxicity cues.'),
('PN-6','pn','Pharmacology','Nitroglycerin teaching','single_best_answer','Which statement about sublingual nitroglycerin indicates need for further teaching?','I will sit before taking it|If pain is not better 5 minutes after the first tablet, I will call 911|I will keep tablets in a plastic pill organizer in my glove compartment|I may get a headache','C','Nitroglycerin should be protected from heat, light and moisture in its original container; a hot glove compartment/pill organizer is inappropriate.'),
('PN-7','pn','Pharmacology','Loop diuretics','single_best_answer','Which foods should the LPN/VN suggest to a client taking furosemide?','Bananas, oranges and baked potatoes|White rice, bread and pasta|Cheese, milk and yogurt|Canned vegetables and pickles','A','Loop diuretics can increase potassium loss; these foods are potassium-rich choices.'),
('PN-8','pn','Fundamentals','Orthostatic hypotension','single_best_answer','Which instruction is most important for an older adult newly taking an antihypertensive?','Take only with headache|Sit at the bedside for a few minutes before standing|Increase salt if dizzy|Stop medication if tired','B','Slow position changes reduce orthostatic hypotension and fall risk.'),
('PN-9','pn','Pharmacology','Enoxaparin','single_best_answer','Which action is correct when administering enoxaparin from a prefilled syringe?','Expel the air bubble|Inject into abdomen at least 2 inches from umbilicus|Massage after injection|Aspirate before injecting','B','Enoxaparin is administered subcutaneously in the abdomen away from the umbilicus; rubbing and aspiration are avoided.'),
('PN-10','pn','Pharmacology','Warfarin','single_best_answer','Which finding in a client taking warfarin should be reported immediately?','INR 2.5|INR 4.8 with bleeding gums|Mild bruise after blood draw|Question about vitamin K foods','B','Markedly supratherapeutic anticoagulation with active bleeding requires prompt evaluation.'),
('PN-11','pn','Fundamentals','Cardiac catheterization','single_best_answer','One hour after femoral cardiac catheterization, what positioning instruction should the LPN/VN reinforce?','Sit fully upright if leg straight|Keep affected leg straight and remain at protocol-allowed position until prescribed time passes|Bend knee slowly|Get to chair after eating','B','Femoral access requires prescribed positioning and keeping the affected leg straight to reduce bleeding risk.'),
('PN-12','pn','Adult Health','Chest pain','single_best_answer','During morning care a client reports sudden chest pain. What should the LPN/VN do first?','Finish bath quickly|Stop activity and have client rest|Document the pain|Continue care with slow breaths','B','Stopping exertion immediately reduces myocardial oxygen demand; assessment and RN escalation follow promptly.'),
('PN-13','pn','Fundamentals','DVT prevention','multiple_response','Which actions help prevent postoperative DVT? Select all that apply.','Ankle pumps and leg exercises|Sequential compression devices as prescribed|Pillow under knees|Early ambulation as prescribed|Adequate fluid intake|Cross legs at knees','A,B,D,E','Leg exercises, compression, ambulation and adequate hydration promote venous return; knee pressure/crossing legs impedes flow.'),
('PN-14','pn','Adult Health','Peripheral arterial disease','single_best_answer','Which PAD teaching statement indicates understanding?','Use heating pad on feet|Avoid heating pads on legs and feet|Elevate legs above heart for pain|Wear tight socks','B','Reduced perfusion/sensation increases burn risk from direct heat; constriction and elevation can further impair arterial flow.'),
('PN-15','pn','Adult Health','Venous insufficiency','single_best_answer','Which instruction should be reinforced for a venous stasis ulcer?','Keep legs dangling|Elevate legs above heart several times daily|Avoid walking|Cross legs while sitting','B','Leg elevation improves venous return and reduces edema in chronic venous insufficiency.'),
('PN-16','pn','Fundamentals','Compression stockings','single_best_answer','When is the best time to apply prescribed graduated compression stockings?','After walking an hour|Morning before getting out of bed|At bedtime|After evening shower','B','Applying stockings before dependency-related edema develops improves fit and effectiveness.'),
('PN-17','pn','Adult Health','Heart failure self-care','single_best_answer','Which statement shows understanding of daily weights for heart failure?','Weigh whenever swollen|Weigh every morning after urinating, before breakfast, on same scale|Call if 5 lb gained in a month|Weigh weekly in coat and shoes','B','Daily weights under consistent conditions detect fluid retention early.'),
('PN-18','pn','Adult Health','Sodium restriction','single_best_answer','Which snack is appropriate on a 2-g sodium diet?','Salted pretzels|Fresh apple with unsalted peanut butter|Canned tomato soup|Hot dog','B','Fresh fruit and unsalted nut butter are lower-sodium choices than processed or canned foods.'),
('PN-19','pn','Adult Health','Hypertension risk factors','multiple_response','Which hypertension risk factors can the client modify? Select all that apply.','Cigarette smoking|Family history|Obesity|High sodium intake|Increasing age|Excess alcohol|Physical inactivity','A,C,D,F,G','Smoking, body weight, sodium intake, alcohol use and physical activity are modifiable; age and family history are not.'),
('PN-20','pn','Mental Health','Therapeutic communication','single_best_answer','A client recovering from MI says, "I am worried about being intimate with my wife again." What is the best response?','Do not worry; focus on recovery|Many people have that concern after a heart attack. What questions do you have?|Ask your cardiologist|Sex is unsafe for several months','B','Normalizing the concern and using an open-ended question encourages therapeutic discussion without dismissing or giving inaccurate advice.'),
('PN-21','pn','Adult Health','Cardiac rehabilitation','single_best_answer','Which finding during treadmill cardiac rehabilitation means the activity should stop?','HR 12/min above rest|Mild sweating|Chest tightness and dizziness|RR 22/min','C','Chest discomfort and dizziness may indicate ischemia/activity intolerance and require stopping activity and escalation.'),
('PN-22','pn','Adult Health','Pacemaker care','single_best_answer','Which instruction should be reinforced the day after left-chest permanent pacemaker insertion?','Raise left arm overhead repeatedly|Avoid raising left arm above shoulder until provider allows|Resume swimming tomorrow|Keep cell phone over insertion site','B','Temporary movement restrictions reduce early lead-dislodgement risk; follow the implanting team’s instructions.'),
('PN-23','pn','Adult Health','Heart failure','single_best_answer','Which finding in an older adult with HF should be reported to the RN first?','Trace ankle edema late day|New restlessness/confusion with SpO2 89%|Fatigue walking to dining room|Nocturia twice nightly','B','New mental-status change with hypoxemia suggests worsening oxygenation and is the priority.'),
('PN-24','pn','Pharmacology','Diuretics and digoxin','matrix_grid','Classify each finding in a client taking furosemide and digoxin as expected or report to RN.','Increased urination|Potassium 3.2 mEq/L|Apical pulse 54/min|Yellow-tinged vision|BP 126/78','A','Diuresis and normal BP are expected; hypokalemia, bradycardia and visual changes increase concern for digoxin toxicity and require reporting.'),
('PN-25','pn','Adult Health','Acute pulmonary edema','bow_tie','An 81-year-old with HF becomes suddenly restless and dyspneic: coarse crackles, RR 32, SpO2 86% room air, pink frothy sputum. Choose the condition, 2 immediate actions, and 2 parameters to monitor.','Acute pulmonary edema|High-Fowler position|Apply oxygen per emergency protocol/prescription|Oxygen saturation|Respiratory rate and lung sounds','A,B,C,D,E','The cue cluster indicates acute pulmonary edema with severe hypoxemia. Upright positioning and immediate oxygen support are priorities while urgent RN/provider/emergency escalation occurs.')
) x(src,role,subject,topic,item_type,stem,opts,keys,rationale)
loop
 qid:=md5('set01-cardio-'||lower(r.src))::uuid; qvid:=md5('set01-cardio-v-'||lower(r.src))::uuid;
 insert into public.questions(id,slug,lifecycle_status,current_version) values(qid,'set01-cardio-'||lower(r.src),'pilot',1)
 on conflict(slug) do update set lifecycle_status='pilot',updated_at=now() returning id into qid;
 keyarr:=string_to_array(r.keys,','); typ:=r.item_type; rat:=r.rationale; cfg:='{}'::jsonb;
 if r.src='RN-18' then cfg=jsonb_build_object('segments',jsonb_build_array(
  jsonb_build_object('id','a','text','Three-pillow orthopnea','correct',true),jsonb_build_object('id','b','text','Weight 84 kg (82 kg yesterday)','correct',true),jsonb_build_object('id','c','text','Fine bilateral basilar crackles','correct',true),jsonb_build_object('id','d','text','BP 132/82','correct',false),jsonb_build_object('id','e','text','Potassium 4.2','correct',false),jsonb_build_object('id','f','text','SpO2 91% room air','correct',true),jsonb_build_object('id','g','text','Eating most of breakfast','correct',false))); end if;
 if r.src='RN-19' then cfg=jsonb_build_object('blanks',jsonb_build_array(
  jsonb_build_object('id','first','options',jsonb_build_array('Obtain a 12-lead ECG and activate the facility chest-pain/ACS escalation pathway','Wait 15 minutes and reassess','Ambulate the client'),'correct','Obtain a 12-lead ECG and activate the facility chest-pain/ACS escalation pathway'),
  jsonb_build_object('id','then','options',jsonb_build_array('Administer another prescribed SL nitroglycerin while continuing reassessment if no contraindication is present','Document pain as resolved','Offer a warm drink'),'correct','Administer another prescribed SL nitroglycerin while continuing reassessment if no contraindication is present'))); end if;
 if r.src='RN-22' then cfg=jsonb_build_object('blanks',jsonb_build_array(
  jsonb_build_object('id','dx','options',jsonb_build_array('acute decompensated heart failure','community-acquired pneumonia','acute kidney injury','pulmonary embolism'),'correct','acute decompensated heart failure'),
  jsonb_build_object('id','cause','options',jsonb_build_array('diuretic nonadherence and high dietary sodium intake','elevated creatinine','hypokalemia','prolonged immobility'),'correct','diuretic nonadherence and high dietary sodium intake'))); end if;
 if r.src='RN-21' then cfg=jsonb_build_object('columns',jsonb_build_array(jsonb_build_object('id','left','label','Left-sided'),jsonb_build_object('id','right','label','Right-sided')),'rows',jsonb_build_array(
  jsonb_build_object('id','r1','label','Crackles in bilateral lung fields','correct','left'),jsonb_build_object('id','r2','label','Jugular venous distention','correct','right'),jsonb_build_object('id','r3','label','+3 pitting ankle edema','correct','right'),jsonb_build_object('id','r4','label','Orthopnea','correct','left'),jsonb_build_object('id','r5','label','SpO2 88% room air','correct','left'))); end if;
 if r.src='RN-25' then cfg=jsonb_build_object('columns',jsonb_build_array(jsonb_build_object('id','effective','label','Effective'),jsonb_build_object('id','not','label','Not effective')),'rows',jsonb_build_array(
  jsonb_build_object('id','r1','label','SpO2 95% room air','correct','effective'),jsonb_build_object('id','r2','label','Weight decreased 1.5 kg','correct','effective'),jsonb_build_object('id','r3','label','Crackles only in lung bases','correct','effective'),jsonb_build_object('id','r4','label','Potassium 3.1 mEq/L','correct','not'),jsonb_build_object('id','r5','label','HR 124 irregularly irregular','correct','not'),jsonb_build_object('id','r6','label','Urine output 1800 mL/8 hr','correct','effective'))); end if;
 if r.src='PN-24' then cfg=jsonb_build_object('columns',jsonb_build_array(jsonb_build_object('id','expected','label','Expected'),jsonb_build_object('id','report','label','Report to RN')),'rows',jsonb_build_array(
  jsonb_build_object('id','r1','label','Increased urination','correct','expected'),jsonb_build_object('id','r2','label','Potassium 3.2 mEq/L','correct','report'),jsonb_build_object('id','r3','label','Apical pulse 54/min','correct','report'),jsonb_build_object('id','r4','label','Yellow-tinged vision','correct','report'),jsonb_build_object('id','r5','label','BP 126/78','correct','expected'))); end if;
 if r.src='PN-25' then cfg=jsonb_build_object('groups',jsonb_build_array(
  jsonb_build_object('id','condition','label','Condition','choose',1,'options',jsonb_build_array(jsonb_build_object('id','pe','label','Acute pulmonary edema','correct',true),jsonb_build_object('id','pna','label','Pneumonia','correct',false),jsonb_build_object('id','anx','label','Anxiety attack','correct',false))),
  jsonb_build_object('id','actions','label','Actions','choose',2,'options',jsonb_build_array(jsonb_build_object('id','upright','label','Raise head of bed to high-Fowler position','correct',true),jsonb_build_object('id','oxygen','label','Apply oxygen per emergency protocol/prescription','correct',true),jsonb_build_object('id','fluids','label','Encourage oral fluids','correct',false),jsonb_build_object('id','flat','label','Lay client flat','correct',false))),
  jsonb_build_object('id','monitor','label','Monitor','choose',2,'options',jsonb_build_array(jsonb_build_object('id','spo2','label','Oxygen saturation','correct',true),jsonb_build_object('id','resp','label','Respiratory rate and lung sounds','correct',true),jsonb_build_object('id','glucose','label','Blood glucose','correct',false),jsonb_build_object('id','bowel','label','Bowel sounds','correct',false))))); end if;
 insert into public.question_versions(id,question_id,version,stem,item_type,exam_tracks,subject,topic,client_need,difficulty,rationale_correct,rationale_distractors,memory_rule,source_note,validation_status,professional_role_focus,track_rationale,body_system,discipline,source_id,case_set_id,response_config,scoring_method)
 values(qvid,qid,1,r.stem,typ,array[r.role],r.subject,r.topic,
 case when r.role='rn' then case when r.subject='Pharmacology' then 'Pharmacological and Parenteral Therapies' else 'Physiological Adaptation' end else case when r.subject='Pharmacology' then 'Pharmacological Therapies' else 'Physiological Adaptation' end end,
 'medium',rat,'Distractors are reviewed against the clinical task; the Teaching Rationale explains why the keyed response is best.','Identify the clinical task and use safety, assessment, scope, and physiologic priority rather than pattern matching.',
 'User-provided Set 1 Cardiovascular practice bank; AI-assisted clinical/editorial review. Not human or psychometrically validated.','pilot',
 case when r.role='rn' then 'Entry-level RN clinical judgment.' else 'Entry-level PN data collection, implementation, reinforcement, monitoring and escalation.' end,
 case when r.role='rn' then 'NCLEX-RN' else 'NCLEX-PN' end,'Cardiovascular',r.subject,'Set01-Cardiovascular-'||r.src,
 case when r.src like 'RN-2%' and r.src in ('RN-20','RN-21','RN-22','RN-23','RN-24','RN-25') then 'Set01-Cardiovascular-RN-HFrEF-Case' else null end,cfg,
 case when typ in ('multiple_response','matrix_grid','highlight','bow_tie') then 'plus_minus' else 'zero_one' end)
 on conflict(question_id,version) do update set stem=excluded.stem,item_type=excluded.item_type,response_config=excluded.response_config,source_id=excluded.source_id,case_set_id=excluded.case_set_id,scoring_method=excluded.scoring_method,validation_status='pilot' returning id into qvid;
 delete from public.question_options where question_version_id=qvid;
 n:=0; foreach opt in array string_to_array(r.opts,'|') loop n:=n+1;
  insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order)
  values(qvid,chr(96+n),opt,(chr(64+n)=any(keyarr)),
   case when chr(64+n)=any(keyarr) then rat else 'This choice does not best satisfy the clinical task or the priority evidence in the stem.' end,n);
 end loop;
end loop;
end $$;
commit;