-- NursePrepIQ 0073: RN master Set 2 Respiratory MC/SATA pilot import.
-- Source: user-provided NCLEX-RN Master Edition. Original practice items; not psychometrically pretested.
begin;
do $$
declare r record; qid uuid; qvid uuid; optrec record; n int; keyarr text[]; typ text; caseid text;
begin
insert into public.question_case_studies(id,title,case_stem,initial_data,source_note) values('RNMaster-Set02-Case','Unfolding Case Study — Respiratory System','A 68-year-old client with chronic obstructive pulmonary disease (60 pack-year smoking history) is admitted with 3 days of increasing dyspnea and a cough producing thick yellow-green sputum. Nurses'' notes, 1400: Client is sitting in a tripod position using accessory neck muscles and pursed-lip breathing. Restless but oriented. Barrel chest and clubbing of the fingers noted. Diminished breath sounds with expiratory wheezes bilaterally and coarse crackles in the right lower lobe. Vital signs: T 101.3°F (38.5°C), HR 108/min, RR 30/min, BP 146/88 mm Hg, SpO2 84% on room air. ABG on room air: pH 7.31, PaCO2 62 mm Hg, HCO3 31 mEq/L, PaO2 52 mm Hg. Previous baseline: pH 7.37, PaCO2 50 mm Hg, HCO3 30 mEq/L. WBC 15,800/mm3. Chest x-ray shows a right lower lobe infiltrate.','{}'::jsonb,'User-provided RN master Set 2 case study.') on conflict(id) do update set case_stem=excluded.case_stem,updated_at=now();
for r in select * from (values
('Set02-RN-1','1','Management of Care','Prioritization','single_best_answer','The nurse receives report on four clients on a medical unit. Which client should the nurse assess first?','A client with pneumonia who has a temperature of 101°F (38.3°C) and a productive cough|A client with asthma whose peak flow is 45% of personal best and who is speaking in 2- to 3-word phrases|A client with COPD whose SpO2 is 90% on 2 L/min nasal cannula|A client with a chest tube whose water-seal chamber shows fluctuation with respirations','B','A peak flow below 50% of personal best with inability to speak in full sentences indicates a severe asthma exacerbation. The other findings are less urgent or expected.'),
('Set02-RN-2','2','Reduction of Risk Potential','Chest tubes','single_best_answer','The nurse notes continuous bubbling in the water-seal chamber of a client''s chest drainage system. What should the nurse do first?','Clamp the chest tube close to the client''s chest|Check the system for a leak, starting at the insertion site and moving toward the drainage unit|Increase the suction to the prescribed maximum|Document the finding as expected','B','Continuous bubbling in the water-seal chamber indicates an air leak. Check the dressing and connections systematically from client to unit.'),
('Set02-RN-3','3','Reduction of Risk Potential','Chest tubes','single_best_answer','While a client is being repositioned, the chest tube becomes disconnected from the drainage system. What is the nurse''s immediate action?','Clamp the tube and leave it clamped until the provider arrives|Submerge the end of the chest tube 1–2 inches (2.5–5 cm) in a bottle of sterile water|Remove the chest tube and apply an occlusive dressing|Instruct the client to hold their breath while the nurse obtains a new drainage system','B','Submerging the tube in sterile water creates a temporary water seal that prevents air from entering the pleural space.'),
('Set02-RN-5','5','Reduction of Risk Potential','Arterial blood gases','single_best_answer','A postoperative client who received several doses of IV opioids is drowsy. ABG: pH 7.29, PaCO2 58 mm Hg, HCO3 25 mEq/L, PaO2 70 mm Hg. How should the nurse interpret these results?','Uncompensated respiratory acidosis|Compensated metabolic acidosis|Uncompensated respiratory alkalosis|Partially compensated metabolic alkalosis','A','The pH is acidotic and PaCO2 is elevated while HCO3 is normal, indicating uncompensated respiratory acidosis from hypoventilation.'),
('Set02-RN-6','6','Physiological Adaptation','COPD oxygen therapy','single_best_answer','A client with severe COPD and chronic CO2 retention is receiving oxygen at 2 L/min by nasal cannula. SpO2 is 90% and the client is alert. A family member asks to increase oxygen to 6 L/min. What is the nurse''s best response?','I''ll increase it right away, since more oxygen is always better.|An oxygen level around 88 to 92 percent is the goal. Too much oxygen can make the client retain carbon dioxide and become very drowsy.|Oxygen is addictive, so we try to use as little as possible.|Only the respiratory therapist can change the oxygen.','B','For clients with chronic hypercapnia, a target SpO2 of 88–92% is typical; excessive oxygen can worsen CO2 retention.'),
('Set02-RN-7','7','Safety and Infection Control','Tuberculosis screening','single_best_answer','A newly hired nurse has a tuberculin skin test read at 72 hours with 12 mm of induration. The nurse has no known risk factors other than hospital employment. What is the appropriate next step?','Repeat the skin test in 2 weeks|Obtain a chest x-ray to evaluate for active disease|Begin airborne precautions immediately|No follow-up is needed because a reaction under 15 mm is negative','B','For healthcare workers, 10 mm or more is positive. A chest x-ray and symptom evaluation follow to assess for active disease.'),
('Set02-RN-8','8','Pharmacological and Parenteral Therapies','Antituberculars','multiple_response','The nurse is teaching a client starting rifampin, isoniazid, pyrazinamide, and ethambutol for active tuberculosis. Which statements indicate understanding? Select all that apply.','My urine and tears may turn orange-red.|I''ll avoid drinking alcohol while taking these medications.|I can stop the medications once my cough goes away.|I''ll report any changes in my vision or color perception.|I''ll take vitamin B6 as prescribed to prevent numbness in my hands and feet.|My birth control pills will work the same as before.','A,B,D,E','Rifampin discolors body fluids and reduces hormonal contraceptive effectiveness; hepatotoxicity risk makes alcohol unsafe; pyridoxine reduces isoniazid neuropathy; ethambutol can cause optic neuritis.'),
('Set02-RN-9','9','Pharmacological and Parenteral Therapies','Inhaled medications','single_best_answer','A client is prescribed albuterol and fluticasone by metered-dose inhaler, both due at 0900. Which action indicates correct technique?','Use fluticasone first, then albuterol 5 minutes later|Use albuterol first, wait about 5 minutes, then use fluticasone and rinse the mouth|Use both inhalers at the same time|Swallow water after albuterol to prevent thrush','B','The bronchodilator opens the airways before the inhaled corticosteroid; rinsing after corticosteroid reduces oral candidiasis.'),
('Set02-RN-10','10','Physiological Adaptation','Status asthmaticus','single_best_answer','A client is being treated for a severe asthma attack. Which change is most concerning?','Wheezing louder than on arrival|Absence of wheezing with markedly diminished breath sounds|Heart rate increased after albuterol|Productive cough with thick white sputum','B','A silent chest can mean airflow is so limited that wheezing is no longer audible, signaling impending respiratory failure.'),
('Set02-RN-11','11','Reduction of Risk Potential','Pulmonary embolism','single_best_answer','A client develops sudden dyspnea, pleuritic chest pain, and tachycardia 3 days after abdominal surgery. Which diagnostic test is anticipated to confirm the suspected diagnosis?','Pulmonary function tests|CT pulmonary angiography|Sputum culture|Abdominal ultrasound','B','CT pulmonary angiography is the standard test to confirm pulmonary embolism when contrast is appropriate.'),
('Set02-RN-12','12','Physiological Adaptation','Mechanical ventilation','multiple_response','The high-pressure alarm sounds on a client''s mechanical ventilator. Which conditions could cause this alarm? Select all that apply.','Accumulation of secretions in the airway|Client biting on the endotracheal tube|Disconnection of ventilator tubing|Kinked ventilator tubing|Client coughing or fighting the ventilator|Leak in the endotracheal tube cuff','A,B,D,E','High-pressure alarms indicate increased resistance: secretions, biting, kinks, coughing, or bronchospasm. Disconnection and cuff leaks cause low-pressure alarms.'),
('Set02-RN-13','13','Safety and Infection Control','Ventilator-associated pneumonia','multiple_response','Which interventions should the nurse include in a ventilator-associated pneumonia prevention bundle? Select all that apply.','Elevate head of bed 30–45 degrees|Perform oral care per protocol|Instill normal saline before each suctioning|Participate in daily sedation interruption and assessment of readiness to wean|Change ventilator circuit every 24 hours|Use an endotracheal tube with subglottic secretion drainage when available','A,B,D,F','Head elevation, oral care, sedation interruption/weaning assessment, and subglottic secretion drainage reduce VAP risk.'),
('Set02-RN-14','14','Reduction of Risk Potential','Airway suctioning','single_best_answer','The nurse observes a new graduate suction a client''s tracheostomy. Which action requires intervention?','Hyperoxygenating before suctioning|Applying suction while inserting the catheter|Limiting each suction pass to 10 seconds|Using sterile technique throughout','B','Suction is applied only while withdrawing the catheter; applying suction during insertion removes oxygen and traumatizes mucosa.'),
('Set02-RN-15','15','Safety and Infection Control','Tracheostomy','single_best_answer','A client returns from surgery with a new tracheostomy. Which items should the nurse ensure are at the bedside?','An obturator and a spare tracheostomy tube of the same size and one size smaller|A tongue depressor and penlight|A padded tongue blade and bite block|A spare nasal cannula and petroleum jelly','A','An obturator and replacement tubes allow rapid airway reestablishment if the tracheostomy becomes dislodged.'),
('Set02-RN-16','16','Physiological Adaptation','Pneumonia in older adults','single_best_answer','An 84-year-old client in long-term care is suspected of having pneumonia. Which finding is most likely to be the earliest sign?','High fever with shaking chills|New-onset confusion|Pleuritic chest pain|Rust-colored sputum','B','Older adults often present atypically with acute confusion, falls, or functional decline rather than high fever.'),
('Set02-RN-17','17','Physiological Adaptation','Epiglottitis','single_best_answer','A 4-year-old has fever 104°F (40°C), drooling, and sits upright leaning forward. What action should the nurse avoid?','Allow child to remain on parent''s lap|Inspect the child''s throat with a tongue depressor|Keep emergency intubation equipment at bedside|Provide humidified oxygen as tolerated','B','Throat inspection can trigger laryngospasm and complete airway obstruction in epiglottitis.'),
('Set02-RN-18','18','Reduction of Risk Potential','Thoracentesis','single_best_answer','Which finding after a thoracentesis should the nurse report immediately?','Mild soreness at puncture site|Sudden shortness of breath with diminished breath sounds on affected side|Small amount of serous drainage on dressing|Request to resume eating','B','Sudden dyspnea with decreased breath sounds suggests pneumothorax, a serious thoracentesis complication.'),
('Set02-RN-19','19','Physiological Adaptation','ARDS','single_best_answer','A client with sepsis is being evaluated for ARDS. Which finding is most characteristic?','Hypoxemia that does not improve despite increasing oxygen concentration|Elevated central venous pressure and peripheral edema|Unilateral wheezing that clears with coughing|Hypercapnia that corrects with oxygen therapy','A','Refractory hypoxemia is the hallmark of ARDS because fluid-filled or collapsed alveoli create intrapulmonary shunting.'),
('Set02-RN-23','23','Pharmacological and Parenteral Therapies','Case study: Generate solutions','multiple_response','Which prescriptions does the nurse anticipate for this client? Select all that apply.','Oxygen by Venturi mask titrated to SpO2 88–92%|Nebulized albuterol and ipratropium|Systemic corticosteroid|IV antibiotics after obtaining sputum and blood cultures|Lorazepam IV every 4 hours for restlessness|Noninvasive positive-pressure ventilation (BiPAP) if acidosis worsens|Nonrebreather mask at 15 L/min to keep SpO2 above 98%','A,B,C,D,F','COPD exacerbation management includes controlled oxygen, bronchodilators, systemic corticosteroids, antibiotics for bacterial infection, and BiPAP for worsening hypercapnic acidosis.'),
('Set02-RN-24','24','Physiological Adaptation','Case study: Take action','single_best_answer','Two hours later, the client is difficult to arouse and responds only to painful stimuli. SpO2 is 93%. Which action should the nurse take first?','Allow the client to rest|Call rapid response and anticipate repeat ABG and ventilatory support|Administer scheduled nebulizer treatment|Increase oxygen to a nonrebreather mask','B','Decreasing consciousness with hypercapnia suggests worsening CO2 narcosis and requires urgent ventilation assessment and support.')
) x(src,rn,client_need,topic,item_type,stem,opts,keys,rationale)
loop
 qid:=md5('rnmaster-'||lower(r.src))::uuid; qvid:=md5('rnmaster-v-'||lower(r.src))::uuid;
 insert into public.questions(id,slug,lifecycle_status,current_version) values(qid,'rnmaster-'||lower(r.src),'pilot',1) on conflict(slug) do update set lifecycle_status='pilot',updated_at=now() returning id into qid;
 keyarr:=string_to_array(r.keys,','); typ:=r.item_type; caseid:=case when r.rn::int between 20 and 25 then 'RNMaster-Set02-Case' else null end;
 insert into public.question_versions(id,question_id,version,stem,item_type,exam_tracks,subject,topic,client_need,difficulty,rationale_correct,rationale_distractors,memory_rule,source_note,validation_status,professional_role_focus,track_rationale,body_system,discipline,source_id,case_set_id,case_study_id,case_sequence,response_config,scoring_method)
 values(qvid,qid,1,r.stem,typ,array['rn'],r.client_need,r.topic,r.client_need,'medium',r.rationale,'Each distractor should be evaluated against the clinical task and priority evidence in the stem.','Identify the clinical task, compare every option with the cue pattern, and prioritize airway, breathing, circulation, safety, and scope as applicable.','User-provided NCLEX-RN Master Edition; imported to PILOT for clinical/editorial validation. Not human or psychometrically validated.','pilot','Entry-level RN clinical judgment.','NCLEX-RN','Respiratory',case when r.client_need like 'Pharmacological%' then 'Pharmacology' when r.client_need='Management of Care' then 'Management of Care' when r.client_need='Safety and Infection Control' then 'Safety & Infection Control' else 'Adult Health' end,'RNMaster-'||r.src,caseid,caseid,case when caseid is not null then r.rn::int-19 else null end,'{}'::jsonb,case when typ='multiple_response' then 'plus_minus' else 'zero_one' end)
 on conflict(question_id,version) do update set stem=excluded.stem,item_type=excluded.item_type,source_id=excluded.source_id,case_set_id=excluded.case_set_id,case_study_id=excluded.case_study_id,case_sequence=excluded.case_sequence,validation_status='pilot' returning id into qvid;
 delete from public.question_options where question_version_id=qvid; n:=0;
 for optrec in select unnest(string_to_array(r.opts,'|')) as txt loop n:=n+1; insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order) values(qvid,chr(96+n),optrec.txt,(upper(chr(96+n))=any(keyarr)),case when upper(chr(96+n))=any(keyarr) then r.rationale else null end,n); end loop;
end loop;
end $$;
commit;