-- 0076: RN Master Set 3 standalone MC/SATA import + canonical production promotion (19 items).
begin;
do $$
declare r record; qid uuid; qvid uuid; optrec record; n int; keyarr text[]; gate text; kc int;
begin
for r in select * from (values
('Set03-RN-1','Management of Care','Prioritization','single_best_answer','The nurse on a neuroscience unit receives report on four clients. Which client should the nurse assess first?','A client with a head injury whose Glasgow Coma Scale score decreased from 14 to 11 in the past hour|A client with multiple sclerosis who reports fatigue after physical therapy|A client who reports a headache 6 hours after a lumbar puncture|A client with Parkinson''s disease whose carbidopa-levodopa is due in 30 minutes','A','A drop of 2 or more points on the GCS indicates neurological deterioration, possibly from increasing ICP, and requires immediate assessment. The other situations are expected or can safely wait briefly.','Neurologic','Management of Care'),
('Set03-RN-2','Physiological Adaptation','Increased intracranial pressure','single_best_answer','The nurse is monitoring a client at risk for increased intracranial pressure. Which finding is the earliest indicator of rising ICP?','Fixed, dilated pupils|Restlessness and new confusion|Bradycardia with widened pulse pressure|Decerebrate posturing','B','A change in level of consciousness is the earliest and most sensitive sign of increasing ICP. Pupil changes, Cushing''s triad, and abnormal posturing are late signs.','Neurologic','Adult Health'),
('Set03-RN-3','Physiological Adaptation','Increased intracranial pressure','multiple_response','Which findings are late signs of increased intracranial pressure? Select all that apply.','Widening pulse pressure|Bradycardia|Irregular respiratory pattern|Tachycardia with narrowing pulse pressure|Fixed, dilated pupil|Decorticate or decerebrate posturing','A,B,C,E,F','Cushing''s triad (systolic hypertension with widened pulse pressure, bradycardia, and irregular respirations) signals brainstem compression. Fixed pupils and abnormal posturing indicate impending herniation. Tachycardia with narrowing pulse pressure suggests shock.','Neurologic','Adult Health'),
('Set03-RN-4','Reduction of Risk Potential','ICP management','multiple_response','Which interventions should the nurse include in the plan of care for a client with increased intracranial pressure? Select all that apply.','Elevate the head of the bed to 30 degrees|Keep the head and neck in a midline position|Cluster all care activities together to allow long rest periods|Administer a prescribed stool softener|Maintain normothermia|Encourage the client to cough forcefully to clear secretions','A,B,D,E','Head elevation and midline alignment promote venous drainage. Stool softeners prevent Valsalva straining, and fever increases cerebral metabolic demand. Clustering many activities causes sustained ICP spikes, so care is spaced out. Coughing raises ICP.','Neurologic','Adult Health'),
('Set03-RN-5','Pharmacological and Parenteral Therapies','Thrombolytics','single_best_answer','A client with an acute ischemic stroke is being evaluated for IV alteplase. Which finding must be addressed before administration?','Symptom onset 2 hours ago|Blood glucose of 110 mg/dL|Blood pressure of 198/112 mm Hg|NIH Stroke Scale score of 8','C','BP must be below 185/110 mm Hg before alteplase is given, and below 180/105 mm Hg afterward, to reduce the risk of intracranial hemorrhage. The onset time falls within the treatment window, and the glucose is normal.','Neurologic','Pharmacology'),
('Set03-RN-6','Physiological Adaptation','Stroke','single_best_answer','A client is admitted with an ischemic stroke affecting the left cerebral hemisphere. Which finding does the nurse expect?','Left-sided hemiplegia|Neglect of the left side of the body|Difficulty expressing words (aphasia)|Impulsive behavior and poor judgment','C','The left hemisphere controls language in most people and the right side of the body. Left hemisphere strokes commonly cause aphasia and right-sided weakness. Left-sided neglect and impulsivity are typical of right hemisphere strokes.','Neurologic','Adult Health'),
('Set03-RN-7','Safety and Infection Control','Dysphagia','single_best_answer','A client admitted 2 hours ago with an acute stroke has oral medications due. What should the nurse do first?','Crush the medications and mix them in applesauce|Perform a bedside swallow screen per protocol before giving anything by mouth|Give the medications with thickened liquids|Ask the client whether they have difficulty swallowing','B','Clients with stroke remain NPO, including for medications, until a swallow screen is passed, because aspiration risk is high. Self-report is unreliable, and thickened liquids should be used only after screening and on the recommendation of speech-language pathology.','Neurologic','Safety & Infection Control'),
('Set03-RN-8','Pharmacological and Parenteral Therapies','Status epilepticus','single_best_answer','A client has had a tonic-clonic seizure lasting 6 minutes and has not regained consciousness. Which medication does the nurse anticipate administering first?','IV lorazepam|Oral levetiracetam|IV phenytoin|Oral carbamazepine','A','A seizure lasting 5 minutes or longer, or repeated seizures without recovery, is status epilepticus. A benzodiazepine (IV lorazepam, or IM midazolam if there is no IV access) is first-line. A longer-acting antiepileptic such as levetiracetam or fosphenytoin follows.','Neurologic','Pharmacology'),
('Set03-RN-9','Safety and Infection Control','Seizure management','single_best_answer','A client begins having a tonic-clonic seizure in bed. Which action by the assistive personnel requires the nurse to intervene?','Turning the client onto their side|Loosening clothing around the client''s neck|Inserting a padded tongue blade between the client''s teeth|Noting the time the seizure began','C','Nothing should be placed in the mouth during a seizure. It can break teeth, cause injury, or obstruct the airway. Side-lying positioning, loosening clothing, and timing the seizure are appropriate.','Neurologic','Safety & Infection Control'),
('Set03-RN-10','Pharmacological and Parenteral Therapies','Antiepileptics','single_best_answer','A client taking phenytoin reports unsteady walking. The nurse notes horizontal nystagmus. The phenytoin level is 27 mcg/mL (therapeutic: 10–20 mcg/mL). What should the nurse do?','Administer the next dose and reassess in 4 hours|Hold the next dose, implement fall precautions, and notify the provider|Administer the dose with food to reduce side effects|Encourage the client to ambulate to improve balance','B','Nystagmus and ataxia with a supratherapeutic level indicate phenytoin toxicity. The nurse holds the dose, protects the client from falls, and notifies the provider.','Neurologic','Pharmacology'),
('Set03-RN-11','Physiological Adaptation','Autonomic dysreflexia','single_best_answer','A client with a T4 spinal cord injury reports a pounding headache and blurred vision. BP is 210/118 mm Hg, HR is 50/min, and the skin above the injury is flushed and diaphoretic. What should the nurse do first?','Administer a prescribed antihypertensive|Raise the head of the bed to a sitting position|Check the urinary catheter for kinks|Notify the provider','B','Autonomic dysreflexia is a medical emergency. Sitting the client upright (and lowering the legs) uses orthostatic effects to lower BP immediately. The nurse then finds and removes the trigger (most often bladder distention, then bowel) and gives antihypertensives if BP remains elevated.','Neurologic','Adult Health'),
('Set03-RN-12','Physiological Adaptation','Spinal cord injury','single_best_answer','A client is admitted with a complete C4 spinal cord injury. Which assessment is the nurse''s priority?','Bladder distention|Respiratory rate, depth, and effectiveness of cough|Sensation in the lower extremities|Skin integrity over the sacrum','B','The phrenic nerve (C3–C5) innervates the diaphragm. Injuries at or near C4 can impair breathing, and swelling can extend the level of injury, so respiratory function is the priority.','Neurologic','Adult Health'),
('Set03-RN-13','Physiological Adaptation','Myasthenia gravis','single_best_answer','A client with myasthenia gravis is admitted with an upper respiratory infection. Which finding requires immediate action by the nurse?','Ptosis that worsens in the evening|Fatigue after walking to the bathroom|Weak cough with difficulty swallowing secretions|Double vision when reading','C','Infection can trigger myasthenic crisis. A weak cough and difficulty managing secretions indicate respiratory muscle and bulbar weakness, which threaten the airway. Ptosis, fatigue, and diplopia are typical findings.','Neurologic','Adult Health'),
('Set03-RN-14','Physiological Adaptation','Guillain-Barré syndrome','single_best_answer','A client is admitted with Guillain-Barré syndrome. Weakness began in the feet and has progressed to the thighs over 2 days. Which assessment is most important for the nurse to monitor frequently?','Deep tendon reflexes in the arms|Vital capacity and negative inspiratory force|Pain level in the legs|Bowel sounds','B','Ascending paralysis can reach the respiratory muscles. Declining vital capacity and negative inspiratory force signal the need for intubation before respiratory failure develops.','Neurologic','Adult Health'),
('Set03-RN-15','Pharmacological and Parenteral Therapies','Antiparkinson agents','single_best_answer','The nurse is teaching a client who is starting carbidopa-levodopa. Which client statement indicates a need for further teaching?','"I''ll get up slowly from sitting or lying down."|"I''ll take my dose with a high-protein shake to protect my stomach."|"My urine or sweat may turn darker."|"I''ll report any new jerky or twisting movements."','B','High-protein meals compete with levodopa for absorption and reduce its effectiveness. Orthostatic hypotension, harmless darkening of body fluids, and dyskinesias are appropriate teaching points.','Neurologic','Pharmacology'),
('Set03-RN-16','Health Promotion and Maintenance','Multiple sclerosis','single_best_answer','A client with relapsing-remitting multiple sclerosis asks how to reduce symptom flare-ups. Which recommendation should the nurse include?','"Take hot baths to relax your muscles."|"Avoid overheating, such as hot tubs and exercising in hot weather."|"Exercise vigorously until you are fatigued."|"Stop your disease-modifying medication when you feel well."','B','Heat can temporarily worsen MS symptoms (Uhthoff''s phenomenon). Moderate exercise with rest periods and continuous use of disease-modifying therapy are recommended.','Neurologic','Fundamentals'),
('Set03-RN-17','Psychosocial Integrity','Caregiver role strain','single_best_answer','The daughter of a client with moderate Alzheimer''s disease tells the nurse, "I''m exhausted. Mom wakes up all night, and I haven''t had a break in months." What is the nurse''s best response?','"You''re doing a wonderful job. Just keep going."|"It sounds like you''re overwhelmed. Let''s talk about respite care and support resources that might help."|"Have you considered placing her in a nursing home?"|"Most caregivers feel this way. It will get easier."','B','The nurse acknowledges the caregiver''s feelings and explores concrete support such as respite care, adult day programs, and support groups. The other responses offer false reassurance or jump to a decision the caregiver hasn''t raised.','Neurologic','Mental Health'),
('Set03-RN-18','Physiological Adaptation','Bacterial meningitis','multiple_response','A college student is admitted with suspected bacterial meningitis. Which findings support this diagnosis? Select all that apply.','Nuchal rigidity|Photophobia|Positive Kernig''s sign|Petechial rash on the trunk and legs|Fever and severe headache|Bradycardia with hypothermia','A,B,C,D,E','Meningeal irritation causes nuchal rigidity, photophobia, and positive Kernig''s and Brudzinski''s signs, along with fever and headache. A petechial rash suggests meningococcal infection. The nurse initiates droplet precautions until the client has received 24 hours of effective antibiotics.','Neurologic','Adult Health'),
('Set03-RN-19','Reduction of Risk Potential','Glasgow Coma Scale','single_best_answer','A client opens the eyes only to painful stimuli, speaks inappropriate words, and withdraws from painful stimuli. What is the client''s Glasgow Coma Scale score?','7|9|11|13','B','Eye opening to pain = 2, inappropriate words = 3, withdrawal from pain = 4, for a total of 9. A score of 8 or less generally indicates the need for airway protection.','Neurologic','Adult Health')
) x(src,client_need,topic,item_type,stem,opts,keys,rationale,body_system,discipline) loop
 qid:=md5('rnmaster-'||lower(r.src))::uuid; qvid:=md5('rnmaster-v-'||lower(r.src))::uuid;
 insert into public.questions(id,slug,lifecycle_status,current_version) values(qid,'rnmaster-'||lower(r.src),'pilot',1)
 on conflict(slug) do update set updated_at=now() returning id into qid;
 keyarr:=string_to_array(r.keys,',');
 insert into public.question_versions(id,question_id,version,stem,item_type,exam_tracks,subject,topic,client_need,difficulty,rationale_correct,rationale_distractors,memory_rule,source_note,validation_status,professional_role_focus,track_rationale,body_system,discipline,source_id,response_config,scoring_method)
 values(qvid,qid,1,r.stem,r.item_type,array['rn'],r.client_need,r.topic,r.client_need,'medium',r.rationale,'Review each distractor against the clinical cues and task in the stem.','Identify the task, interpret the cues, then choose the safest evidence-based RN action or conclusion.','User-provided NCLEX-RN Master Edition; AI-assisted/deterministic validation, not human or psychometric validation.','pilot','Entry-level RN clinical judgment.','NCLEX-RN',r.body_system,r.discipline,'RNMaster-'||r.src,'{}'::jsonb,case when r.item_type='multiple_response' then 'plus_minus' else 'zero_one' end)
 on conflict(question_id,version) do update set stem=excluded.stem,item_type=excluded.item_type,source_id=excluded.source_id,validation_status='pilot' returning id into qvid;
 delete from public.question_options where question_version_id=qvid; n:=0;
 for optrec in select unnest(string_to_array(r.opts,'|')) as txt loop
  n:=n+1; insert into public.question_options(question_version_id,option_key,option_text,is_correct,rationale,display_order)
  values(qvid,chr(96+n),optrec.txt,(upper(chr(96+n))=any(keyarr)),case when upper(chr(96+n))=any(keyarr) then r.rationale else null end,n);
 end loop;
 select count(*) filter(where is_correct) into kc from public.question_options where question_version_id=qvid;
 if (r.item_type='single_best_answer' and kc<>1) or (r.item_type='multiple_response' and kc<2) then raise exception 'Key integrity failed %',r.src; end if;
 update public.question_versions set key_consistency_status='pass',key_consistency_checked_at=now(),key_consistency_notes='Set03 source key/options passed deterministic consistency validation.' where id=qvid;
 foreach gate in array array['schema','clinical','nclex_alignment','editorial'] loop
  insert into public.question_validation_events(question_id,question_version,gate,outcome,validator,notes,evidence)
  values(qid,1,gate,'pass','NursePrepIQ RN Master Set03 import','AI-assisted/deterministic review of supplied RN master item; not human or psychometric validation.',jsonb_build_object('source_id','RNMaster-'||r.src,'human_review',false,'psychometric_validation',false));
 end loop;
 if not public.question_ready_for_production(qid,1) then raise exception 'Production readiness failed %',r.src; end if;
 perform public.promote_question_to_production(qid,1);
end loop;
if (select count(*) from public.question_versions qv join public.questions q on q.id=qv.question_id where qv.source_id like 'RNMaster-Set03-RN-%' and q.lifecycle_status='active' and qv.validation_status='production_validated')<>19 then raise exception 'Set03 did not yield 19 production questions'; end if;
end $$;
commit;