'use client';
import {useEffect,useMemo,useState} from 'react';import {useRouter} from 'next/navigation';import {createClient} from '@/lib/supabase/client';
type Profile={display_name:string|null;email:string|null;exam_track:'rn'|'pn'|null;exam_date:string|null;daily_goal:number|null;onboarding_complete:boolean|null};type Attempt={is_correct:boolean|null;created_at:string};const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const learning=[
 {system:'Cardiovascular',title:'Heart Failure',desc:'Congestion, left vs. right patterns, perfusion, and priority cues.',href:'/learn/heart-failure',ready:true},
 {system:'Cardiovascular',title:'Acute Coronary Syndrome',desc:'Recognize ischemic warning signs and time-sensitive deterioration.',href:'/practice/cardiovascular?topic=Acute%20Coronary%20Syndrome',ready:true},
 {system:'Cardiovascular',title:'Dysrhythmias',desc:'Connect rhythm changes to perfusion and clinical stability.',href:'/practice/cardiovascular?topic=Dysrhythmias',ready:true},
 {system:'Respiratory',title:'COPD',desc:'Ventilation, baseline changes, fatigue, and worsening respiratory status.',href:'/practice/respiratory?topic=COPD',ready:true},
 {system:'Respiratory',title:'Pneumonia',desc:'Oxygenation, infection-related deterioration, and perfusion cues.',href:'/practice/respiratory?topic=Pneumonia',ready:true},
 {system:'Respiratory',title:'Asthma',desc:'Airflow limitation and recognition of impending respiratory failure.',href:'/practice/respiratory?topic=Asthma',ready:true},
 {system:'Respiratory',title:'Pulmonary Embolism',desc:'Sudden cardiopulmonary changes, risk cues, and urgent priorities.',href:'/practice/respiratory?topic=Pulmonary%20Embolism',ready:true},
 {system:'Neurologic',title:'Stroke & Seizures',desc:'Neurologic changes, safety, and time-sensitive priorities.',href:'#',ready:false},
 {system:'Renal',title:'Renal & Urinary',desc:'Fluid balance, kidney function, dialysis, and urinary disorders.',href:'#',ready:false},
 {system:'Endocrine',title:'Diabetes & Endocrine',desc:'Glucose emergencies, thyroid, adrenal, and metabolic disorders.',href:'#',ready:false},
];
export default function Dashboard(){const router=useRouter();const [profile,setProfile]=useState<Profile|null>(null),[attempts,setAttempts]=useState<Attempt[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{let active=true;(async()=>{const s=createClient();const {data:{user},error:ue}=await s.auth.getUser();if(!active)return;if(ue||!user){router.replace('/auth?track=rn');return}let p:any=null,a:any[]=[],pe:any=null,ae:any=null;for(let x=0;x<2;x++){const z=await Promise.all([s.from('profiles').select('display_name,email,exam_track,exam_date,daily_goal,onboarding_complete').eq('id',user.id).maybeSingle(),s.from('question_attempts').select('is_correct,created_at').eq('user_id',user.id).order('created_at',{ascending:false})]);p=z[0].data;pe=z[0].error;a=z[1].data||[];ae=z[1].error;if(![pe?.message,ae?.message].some(m=>m?.toLowerCase().includes('jwt issued at future')))break;await s.auth.refreshSession();await sleep(1200)}if(!active)return;if(pe){setError(pe.message);setLoading(false);return}if(!p?.onboarding_complete){router.replace(`/onboarding?track=${p?.exam_track==='pn'?'pn':'rn'}`);return}if(ae&&!ae.message?.toLowerCase().includes('jwt issued at future'))setError(ae.message);setProfile(p);setAttempts(a);setLoading(false)})();return()=>{active=false}},[router]);const track=profile?.exam_track==='pn'?'PN':'RN',name=profile?.display_name?.trim()||profile?.email?.split('@')[0]||'Student',total=attempts.length,correct=attempts.filter(a=>a.is_correct===true).length,accuracy=total?Math.round(correct/total*100):null,dailyGoal=profile?.daily_goal||20,today=new Date().toLocaleDateString('en-CA'),todayCount=attempts.filter(a=>new Date(a.created_at).toLocaleDateString('en-CA')===today).length;const streak=useMemo(()=>{const days=new Set(attempts.map(a=>new Date(a.created_at).toLocaleDateString('en-CA')));let n=0,d=new Date();while(days.has(d.toLocaleDateString('en-CA'))){n++;d.setDate(d.getDate()-1)}return n},[attempts]);if(loading)return <main className="grid min-h-screen place-items-center bg-slate-50"><p className="font-bold text-slate-500">Loading your NursePrepIQ dashboard…</p></main>;
return <main className="min-h-screen bg-slate-50"><header className="bg-[var(--deep-navy)] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5"><a href="/" className="text-xl font-black">NursePrep<span className="text-[var(--aqua)]">IQ</span></a><div className="flex items-center gap-4 text-sm font-bold"><button onClick={()=>router.push('/practice')} className="rounded-lg px-3 py-2 text-cyan-100 hover:bg-white/10 hover:text-white">Practice Questions</button><span>NCLEX-{track} Prep</span><button onClick={async()=>{await createClient().auth.signOut();location.href='/'}} className="rounded-lg border border-white/20 px-3 py-2">Sign out</button></div></div></header><section className="dashboard-hero"><div className="mx-auto max-w-7xl px-6 py-12"><p className="font-bold text-cyan-200">YOUR NCLEX-{track} PREP DASHBOARD</p><h1 className="mt-2 text-4xl font-black text-white">Welcome, {name}.</h1><p className="mt-3 text-slate-200">Learn one thing well, practice it, and understand every mistake.</p></div></section><div className="mx-auto max-w-7xl px-6 py-10">{error&&<div className="mb-5 rounded-xl bg-rose-50 p-3 font-semibold text-rose-800">{error}</div>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Readiness',total>=10?`${accuracy}% baseline`:'Building'],['Questions',String(total)],['Accuracy',accuracy===null?'—':`${accuracy}%`],['Study streak',`${streak} day${streak===1?'':'s'}`]].map(([a,b])=><div key={a} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><p className="text-sm font-bold text-slate-500">{a}</p><p className="mt-2 text-2xl font-black text-[var(--deep-navy)]">{b}</p></div>)}</div>
<div className="mt-7 grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><section className="rounded-[2rem] bg-white p-7 shadow-sm ring-1 ring-slate-200"><div className="flex justify-between gap-4"><div><p className="text-sm font-black text-[var(--teal)]">TODAY'S PLAN</p><h2 className="mt-1 text-2xl font-black text-[var(--deep-navy)]">Build your clinical reasoning</h2></div><span className="h-fit rounded-full bg-cyan-50 px-3 py-1 text-xs font-black text-[var(--teal)]">{todayCount}/{dailyGoal} Q</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-cyan-50 p-4"><b>1. Learn</b><p className="mt-1 text-sm text-slate-600">Choose a system below and strengthen the core pattern.</p></div><div className="rounded-2xl bg-slate-50 p-4"><b>2. Practice</b><p className="mt-1 text-sm text-slate-600">Answer track-aligned NCLEX-style questions.</p></div><div className="rounded-2xl bg-slate-50 p-4"><b>3. Improve</b><p className="mt-1 text-sm text-slate-600">Use remediation to understand every mistake.</p></div></div></section><section className="rounded-[2rem] bg-[var(--deep-navy)] p-7 text-white"><p className="text-sm font-black text-[var(--aqua)]">PRACTICE QUESTION LIBRARY</p><h2 className="mt-2 text-2xl font-black">Choose what you need to strengthen.</h2><p className="mt-3 leading-7 text-slate-200">Your answers feed the performance cards and future personalized study recommendations.</p><button onClick={()=>router.push('/practice')} className="mt-6 w-full rounded-xl bg-[var(--aqua)] py-3 font-extrabold text-[var(--deep-navy)]">Open Practice Questions →</button></section></div>
<section className="mt-8"><div><p className="text-sm font-black tracking-wider text-[var(--teal)]">LEARNING LIBRARY</p><h2 className="mt-1 text-3xl font-black text-[var(--deep-navy)]">Learn by system — not just Heart Failure.</h2><p className="mt-2 text-slate-600">Move between cardiovascular and respiratory topics now. More systems will unlock as their learning and question banks are completed.</p></div><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{learning.map(x=><article key={x.system+x.title} className={`rounded-2xl bg-white p-5 shadow-sm ring-1 ${x.ready?'ring-slate-200':'ring-slate-100 opacity-70'}`}><div className="flex items-center justify-between gap-3"><span className="text-xs font-black uppercase tracking-wider text-[var(--teal)]">{x.system}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${x.ready?'bg-cyan-50 text-[var(--teal)]':'bg-slate-100 text-slate-500'}`}>{x.ready?'AVAILABLE':'COMING'}</span></div><h3 className="mt-3 text-xl font-black text-[var(--deep-navy)]">{x.title}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-slate-600">{x.desc}</p>{x.ready?<button onClick={()=>router.push(x.href)} style={{color:'#fff'}} className="mt-4 w-full rounded-xl bg-[var(--deep-navy)] py-3 font-extrabold transition hover:bg-[var(--navy)] focus:outline-none focus:ring-2 focus:ring-[var(--aqua)]">{x.title==='Heart Failure'?'Start Lesson':'Learn & Practice'} <span style={{color:'#20d6d2'}}>→</span></button>:<div className="mt-4 rounded-xl bg-slate-50 py-3 text-center text-sm font-bold text-slate-400">In development</div>}</article>)}</div></section></div></main>}
