'use client';
import {useEffect,useMemo,useState} from 'react';import {useRouter} from 'next/navigation';import {createClient} from '@/lib/supabase/client';
type Profile={display_name:string|null;email:string|null;exam_track:'rn'|'pn'|null;exam_date:string|null;daily_goal:number|null;onboarding_complete:boolean|null};type Attempt={is_correct:boolean|null;created_at:string};type Q={subject:string;topic:string};
const systems=['Cardiovascular','Respiratory','Neurologic','Renal & Urinary','Endocrine','Gastrointestinal','Musculoskeletal','Hematologic','Immune','Integumentary','Sensory'];
const disciplines=['Adult Health','Fundamentals','Pharmacology','Mental Health','Maternal & Newborn','Pediatrics','Management of Care','Safety & Infection Control','NGN Clinical Judgment'];
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
export default function Dashboard(){const router=useRouter();const [profile,setProfile]=useState<Profile|null>(null),[attempts,setAttempts]=useState<Attempt[]>([]),[bank,setBank]=useState<Q[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{let active=true;(async()=>{const s=createClient();const {data:{user},error:ue}=await s.auth.getUser();if(!active)return;if(ue||!user){router.replace('/auth?track=rn');return}let p:any=null,a:any[]=[],q:any[]=[],pe:any=null,ae:any=null;for(let x=0;x<2;x++){const z=await Promise.all([s.from('profiles').select('display_name,email,exam_track,exam_date,daily_goal,onboarding_complete').eq('id',user.id).maybeSingle(),s.from('question_attempts').select('is_correct,created_at').eq('user_id',user.id).order('created_at',{ascending:false})]);p=z[0].data;pe=z[0].error;a=z[1].data||[];ae=z[1].error;if(![pe?.message,ae?.message].some(m=>m?.toLowerCase().includes('jwt issued at future')))break;await s.auth.refreshSession();await sleep(1000)}if(!p?.onboarding_complete){router.replace('/onboarding');return}const t=p.exam_track==='pn'?'pn':'rn';const {data:b,error:be}=await s.from('question_versions').select('subject,topic').contains('exam_tracks',[t]);q=b||[];if(!active)return;if(pe||be)setError((pe||be)?.message||'Could not load question bank');setProfile(p);setAttempts(a);setBank(q);setLoading(false)})();return()=>{active=false}},[router]);
const track=profile?.exam_track==='pn'?'PN':'RN',name=profile?.display_name?.trim()||profile?.email?.split('@')[0]||'Student',total=attempts.length,correct=attempts.filter(a=>a.is_correct).length,accuracy=total?Math.round(correct/total*100):null;
const count=(label:string,type:'system'|'discipline')=>bank.filter(q=>type==='discipline'?q.subject===label:(q.topic||'').toLowerCase().includes(label.toLowerCase().replace(' & urinary','').replace('gastrointestinal',''))).length;
if(loading)return <main className="grid min-h-screen place-items-center"><b>Loading your NursePrepIQ dashboard…</b></main>;
const Card=({name,type}:{name:string,type:'system'|'discipline'})=>{const n=count(name,type);return <article className="group rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-1 hover:shadow-lg"><div className="flex items-center justify-between"><h3 className="text-lg font-black text-[var(--deep-navy)]">{name}</h3><span className="rounded-full bg-cyan-50 px-3 py-1 text-sm font-black text-[var(--teal)]">{n} Q</span></div><p className="mt-2 text-sm text-slate-500">{n?'Production questions available for your track.':'Question bank expanding.'}</p><button disabled={!n} onClick={()=>router.push('/practice')} className="mt-5 w-full rounded-xl bg-[var(--deep-navy)] py-3 font-extrabold text-white disabled:bg-slate-200 disabled:text-slate-400">Learn & Practice →</button></article>};
return <main className="min-h-screen bg-slate-50"><header className="sticky top-0 z-20 bg-[var(--deep-navy)] text-white shadow"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><a href="/" className="text-xl font-black">NursePrep<span className="text-[var(--aqua)]">IQ</span></a><div className="flex items-center gap-3 text-sm font-bold"><span>NCLEX-{track}</span><button onClick={()=>router.push('/practice')} className="rounded-lg bg-white/10 px-3 py-2">Practice</button><button onClick={async()=>{await createClient().auth.signOut();location.href='/'}}>Sign out</button></div></div></header><section className="dashboard-hero"><div className="mx-auto max-w-7xl px-6 py-12"><p className="font-bold text-cyan-200">YOUR NCLEX-{track} LEARNING SPACE</p><h1 className="mt-2 text-4xl font-black text-white">Welcome, {name}.</h1><p className="mt-3 text-lg text-slate-200">Choose a body system or nursing discipline. Learn the pattern, practice the judgment, then ask AI when you want to go deeper.</p></div></section><div className="mx-auto max-w-7xl px-6 py-9">{error&&<p className="mb-5 rounded-xl bg-rose-50 p-3 text-rose-800">{error}</p>}<div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm font-bold text-slate-500">Questions answered</p><p className="mt-1 text-3xl font-black">{total}</p></div><div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm font-bold text-slate-500">Accuracy</p><p className="mt-1 text-3xl font-black text-[var(--teal)]">{accuracy===null?'—':accuracy+'%'}</p></div><div className="rounded-2xl bg-[var(--deep-navy)] p-5 text-white"><p className="text-sm font-bold text-cyan-100">Available for NCLEX-{track}</p><p className="mt-1 text-3xl font-black">{bank.length} questions</p></div></div>
<section className="mt-10"><p className="text-sm font-black tracking-widest text-[var(--teal)]">LEARNING LIBRARY</p><h2 className="mt-1 text-3xl font-black text-[var(--deep-navy)]">Learn by System</h2><p className="mt-2 text-slate-600">Start with the body system—not a disease label. Counts update from the production question bank for your exam track.</p><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{systems.map(x=><Card key={x} name={x} type="system"/>)}</div></section>
<section className="mt-12 pb-12"><h2 className="text-3xl font-black text-[var(--deep-navy)]">Learn by Discipline</h2><p className="mt-2 text-slate-600">Build broad NCLEX competence across the major nursing disciplines and clinical-judgment domains.</p><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{disciplines.map(x=><Card key={x} name={x} type="discipline"/>)}</div></section></div></main>}