import Link from 'next/link';

export default async function AdultHealthPage({ searchParams }: { searchParams: Promise<{ track?: string }> }) {
  const params = await searchParams; const track = params.track === 'pn' ? 'pn' : 'rn';
  const cardio=[{name:'Heart Failure',slug:'Heart Failure',description:'Congestion, perfusion, priority cues, monitoring, and role-specific decisions.',count:'4 track-aligned questions'},{name:'Acute Coronary Syndrome',slug:'Acute Coronary Syndrome',description:'Recognize ischemic changes, prioritize assessment, and respond to deterioration.',count:'2 track-aligned questions'},{name:'Dysrhythmias',slug:'Dysrhythmias',description:'Connect rhythm changes with perfusion, symptoms, safety, and escalation.',count:'2 track-aligned questions'},{name:'Hypertension',slug:'Hypertension',description:'Differentiate routine management from findings that require prompt action.',count:'2 track-aligned questions'},{name:'Peripheral Vascular Disease',slug:'Peripheral Vascular Disease',description:'Assess circulation, recognize limb threats, and apply vascular safety principles.',count:'2 track-aligned questions'}];
  const respiratory=[{name:'COPD',slug:'COPD',description:'Ventilation, baseline changes, respiratory fatigue, and deterioration.'},{name:'Pneumonia',slug:'Pneumonia',description:'Oxygenation, infection-related deterioration, mentation, and perfusion cues.'},{name:'Asthma',slug:'Asthma',description:'Airflow limitation, acute exacerbation, and recognition of impending respiratory failure.'},{name:'Pulmonary Embolism',slug:'Pulmonary Embolism',description:'Sudden dyspnea, thromboembolic risk, prioritization, and urgent escalation.'}];
  const neurologic=[{name:'Stroke',slug:'Stroke',description:'Time-sensitive neurologic changes, airway and swallowing safety, perfusion, and outcome evaluation.'},{name:'Seizures',slug:'Seizures',description:'Seizure safety, observation, postictal assessment, escalation, and response to care.'},{name:'Increased Intracranial Pressure',slug:'Increased Intracranial Pressure',description:'Recognize worsening neurologic status, protect cerebral perfusion, and prioritize intervention.'},{name:'Meningitis',slug:'Meningitis',description:'Recognize serious infection patterns, apply precautions, monitor deterioration, and evaluate response.'}];
  const renal=[{name:'Acute Kidney Injury',slug:'Acute Kidney Injury',description:'Urine output, fluid and electrolyte changes, perfusion, deterioration, and recovery.'},{name:'Chronic Kidney Disease & Dialysis',slug:'Chronic Kidney Disease & Dialysis',description:'Dialysis access safety, volume status, treatment response, and renal care priorities.'},{name:'UTI & Pyelonephritis',slug:'UTI & Pyelonephritis',description:'Lower versus upper urinary infection, systemic deterioration, treatment, and monitoring.'},{name:'Urinary Retention',slug:'Urinary Retention',description:'Recognize bladder distention, assess voiding, follow retention protocols, and evaluate emptying.'}];
  const cta='mt-5 inline-flex w-full items-center justify-center rounded-xl bg-[var(--deep-navy)] px-4 py-3 text-sm font-extrabold shadow-sm transition hover:bg-[var(--navy)] focus:outline-none focus:ring-2 focus:ring-[var(--aqua)] focus:ring-offset-2';
  const Group=({label,title,items,route,count}:{label:string,title:string,items:any[],route:string,count:string})=><><div className="mt-12"><p className="text-xs font-black tracking-wider text-[var(--teal)]">{label}</p><h2 className="text-2xl font-black text-[var(--deep-navy)]">{title}</h2></div><div className="mt-5 grid gap-5 md:grid-cols-2">{items.map(topic=><article key={topic.slug} className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-cyan-200"><div className="flex justify-between gap-3"><h3 className="text-xl font-black text-[var(--deep-navy)]">{topic.name}</h3><span className="h-fit rounded-full bg-cyan-50 px-3 py-1 text-xs font-black text-[var(--teal)]">AVAILABLE</span></div><p className="mt-2 text-sm leading-6 text-slate-600">{topic.description}</p><p className="mt-3 text-xs font-bold text-slate-400">{topic.count||count}</p><Link href={`${route}?topic=${encodeURIComponent(topic.slug)}&track=${track}`} style={{color:'#fff'}} className={cta}>Start {topic.name} Practice <span style={{color:'#20d6d2'}} className="ml-2">→</span></Link></article>)}</div></>;
  return <main className="min-h-screen bg-slate-50"><header className="bg-[var(--deep-navy)] px-6 py-5 text-white"><div className="mx-auto flex max-w-5xl items-center justify-between"><Link href={`/practice?track=${track}`} className="text-xl font-black">NursePrep<span className="text-[var(--aqua)]">IQ</span></Link><Link href={`/practice?track=${track}`} className="text-sm font-bold text-cyan-100 hover:text-white">← Practice Library</Link></div></header><section className="mx-auto max-w-5xl px-6 py-12"><p className="font-black tracking-wider text-[var(--teal)]">ADULT HEALTH</p><h1 className="mt-2 text-4xl font-black text-[var(--deep-navy)]">Choose a body system and topic.</h1><p className="mt-3 max-w-3xl text-lg text-slate-600">Practice stays aligned with your NCLEX-{track.toUpperCase()} path. Shared clinical knowledge appears where appropriate; professional decisions remain track-specific.</p><Group label="CARDIOVASCULAR" title="Cardiovascular topics" items={cardio} route="/practice/cardiovascular" count=""/><Group label="RESPIRATORY" title="Respiratory topics" items={respiratory} route="/practice/respiratory" count="4 track-specific questions"/><Group label="NEUROLOGIC" title="Neurologic topics" items={neurologic} route="/practice/neurologic" count="3 track-specific questions"/><Group label="RENAL & URINARY" title="Renal & Urinary topics" items={renal} route="/practice/renal-urinary" count="3 track-specific questions"/><div className="mt-12"><p className="font-black tracking-wider text-slate-400">MORE ADULT HEALTH SYSTEMS</p><div className="mt-4 grid gap-4 md:grid-cols-2">{[{name:'Endocrine',description:'Diabetes, thyroid, adrenal, and metabolic disorders.'},{name:'Gastrointestinal',description:'GI assessment, nutrition, liver, and bowel disorders.'}].map(system=><article key={system.name} className="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><h2 className="font-black text-[var(--deep-navy)]">{system.name}</h2><p className="mt-1 text-sm text-slate-600">{system.description}</p><p className="mt-4 text-sm font-bold text-slate-400">Question set in development</p></article>)}</div></div></section></main>;
}
