import Link from 'next/link';

export default async function AdultHealthPage({ searchParams }: { searchParams: Promise<{ track?: string }> }) {
  const params = await searchParams;
  const track = params.track === 'pn' ? 'pn' : 'rn';
  const systems = [
    { name: 'Respiratory', description: 'Oxygenation, ventilation, airway, and respiratory disorders.' },
    { name: 'Neurologic', description: 'Neurologic assessment, stroke, seizures, and intracranial care.' },
    { name: 'Renal & Urinary', description: 'Fluid balance, renal function, dialysis, and urinary disorders.' },
    { name: 'Endocrine', description: 'Diabetes, thyroid, adrenal, and metabolic disorders.' },
    { name: 'Gastrointestinal', description: 'GI assessment, nutrition, liver, and bowel disorders.' },
  ];
  const cardio = [
    { name: 'Heart Failure', slug: 'Heart Failure', description: 'Congestion, perfusion, priority cues, monitoring, and role-specific decisions.', count: '4 track-aligned questions' },
    { name: 'Acute Coronary Syndrome', slug: 'Acute Coronary Syndrome', description: 'Recognize ischemic changes, prioritize assessment, and respond to deterioration.', count: 'RN/PN pilot set' },
    { name: 'Dysrhythmias', slug: 'Dysrhythmias', description: 'Connect rhythm changes with perfusion, symptoms, safety, and escalation.', count: 'RN/PN pilot set' },
    { name: 'Hypertension', slug: 'Hypertension', description: 'Differentiate routine management from findings that require prompt action.', count: 'RN/PN pilot set' },
    { name: 'Peripheral Vascular Disease', slug: 'Peripheral Vascular Disease', description: 'Assess circulation, recognize limb threats, and apply vascular safety principles.', count: 'RN/PN pilot set' },
  ];
  return <main className="min-h-screen bg-slate-50"><header className="bg-[var(--deep-navy)] px-6 py-5 text-white"><div className="mx-auto flex max-w-5xl items-center justify-between"><Link href={`/practice?track=${track}`} className="text-xl font-black">NursePrep<span className="text-[var(--aqua)]">IQ</span></Link><Link href={`/practice?track=${track}`} className="text-sm font-bold text-cyan-100 hover:text-white">← Practice Library</Link></div></header><section className="mx-auto max-w-5xl px-6 py-12"><p className="font-black tracking-wider text-[var(--teal)]">ADULT HEALTH • CARDIOVASCULAR</p><h1 className="mt-2 text-4xl font-black text-[var(--deep-navy)]">Choose a cardiovascular topic.</h1><p className="mt-3 max-w-2xl text-lg text-slate-600">Practice stays aligned with your NCLEX-{track.toUpperCase()} path. Shared clinical knowledge appears where appropriate; professional decisions remain track-specific.</p><div className="mt-9 grid gap-5 md:grid-cols-2">{cardio.map(topic=><article key={topic.slug} className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-3"><h2 className="text-xl font-black text-[var(--deep-navy)]">{topic.name}</h2><span className="shrink-0 rounded-full bg-cyan-50 px-3 py-1 text-xs font-black text-[var(--teal)]">AVAILABLE</span></div><p className="mt-2 text-sm leading-6 text-slate-600">{topic.description}</p><p className="mt-3 text-xs font-bold text-slate-400">{topic.count}</p><Link href={`/practice/cardiovascular?topic=${encodeURIComponent(topic.slug)}&track=${track}`} style={{color:'#ffffff'}} className="mt-5 inline-flex w-full items-center justify-center rounded-xl bg-[var(--deep-navy)] px-4 py-3 text-sm font-extrabold shadow-sm transition hover:bg-[var(--navy)] focus:outline-none focus:ring-2 focus:ring-[var(--aqua)] focus:ring-offset-2">Start {topic.name} Practice <span style={{color:'#20d6d2'}} className="ml-2">→</span></Link></article>)}</div><div className="mt-12"><p className="font-black tracking-wider text-slate-400">MORE ADULT HEALTH SYSTEMS</p><div className="mt-4 grid gap-4 md:grid-cols-2">{systems.map(system=><article key={system.name} className="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><h2 className="font-black text-[var(--deep-navy)]">{system.name}</h2><p className="mt-1 text-sm text-slate-600">{system.description}</p><p className="mt-4 text-sm font-bold text-slate-400">Question set in development</p></article>)}</div></div></section></main>;
}
